### ISSUE TITLE
How does evolve.py implement the fine-tuning of the tracker?

### ISSUE THREAD

**Issue by lynxhawk** [mikel-brostrom/yolo_tracking#1006]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I only know it is based on genetic algorithm NSGA-II. I don't know much about genetic algorithms. How does evolve.py implement the fine-tuning of the tracker? Can you recommend some information？
I would appreciate it if you could answer.

**Comment by mikel-brostrom** [comment]
You can check out the paper here:

https://ieeexplore.ieee.org/document/996017

The implementation I use comes from [optuna](https://github.com/optuna/optuna)
