### ISSUE TITLE
does this project support replacing yolov7 with yolov8 as the target detector？

### ISSUE THREAD

**Issue by starytosky** [mikel-brostrom/yolo_tracking#1013]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thank you very much for providing such a project, but I have a question whether the project supports the use of yolov7 as the detector？

**Comment by mikel-brostrom** [comment]
I don't have plans of implementing Yolov7 support here. But it should be fairly easy to add given the already existing examples. Feel free to leave a PR for Yolov7! :rocket:
