### ISSUE TITLE
Have you ever tested the Re-ID for multi-camera?

### ISSUE THREAD

**Issue by mj2323** [mikel-brostrom/yolo_tracking#1026]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thank you for your amazing work.

Unlike bytetrack and oc-sort, strongsort, bot-sort, and deep oc-sort have a Re-ID function. This means that the same object can be judged through the embedding vector of the object. I wonder if you have tested it for multi-camera of Re-ID tracking models?

For reference, I associate tracklets with shape features and spatio-temporal constraints across all cameras via batch processing.

**Comment by mikel-brostrom** [comment]
All the ReID models are trained on multi-camera setups

**Comment by mikel-brostrom** [comment]
The process of training a ReID model is the following:

Train set: contains images of individuals captured by multiple cameras in various scenarios. The model learns to generate embeddings for each person

Test set: in the Market-1501 dataset is divided into two main subsets: the query set and the gallery set.

- Query Set: The query set consists of images of individuals, each associated with a specific identity (person). These query images are used to initiate the search for the corresponding person in the gallery set.
- Gallery Set: The gallery set contains images of individuals from different camera views. For each query image, the model searches through the gallery set to find the person with the closest matching embedding (i.e., the most similar appearance) across different cameras.

Evaluation: The model's performance is evaluated based on its ability to correctly match individuals across different cameras.

**Comment by mikel-brostrom** [comment]
> For reference, I associate tracklets with shape features and spatio-temporal constraints across all cameras via batch processing.

You could extract features for all detections in each camera perspective and then calculate the cosine distance between each detection feature in a specific camera perspective and the rest of the features from all the remaining camera perspectives
