### ISSUE TITLE
How to tracking in  multiple cameras

### ISSUE THREAD

**Issue by geohuz** [mikel-brostrom/yolo_tracking#1033]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

In YoloV8 documentation, I found "Multithreaded Tracking", I'm not sure how does this related to the realtime tracking with tracking method like deepsort and I need advice on the situaion that tracking realtime with multiple cameras.

**Comment by mikel-brostrom** [comment]
The idea (https://docs.ultralytics.com/modes/track/#multithreaded-tracking) is still the same for this repo. An example: https://github.com/TRINHHOANGANH/yolo_tracking/blob/master/Final/test_thread_model.py
