### ISSUE TITLE
NameError: name 'get_yolo_inferer' is not defined

### ISSUE THREAD

**Issue by raketa76** [mikel-brostrom/yolo_tracking#1038]
### Search before asking

- [x] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

NameError: name 'get_yolo_inferer' is not defined

from detectors import get_yolo_inferer

Which package should this module be imported from? From ultralytics? This is the import from the top of the file track.py , in the google collab it works well, but not on my pc. This is normal, I think, because there is no place from where he actually imports it.

**Comment by mikel-brostrom** [comment]
You need to clone the repo for this. Not pip install.
