### ISSUE TITLE
To predict a new detection without detection result from a object detector

### ISSUE THREAD

**Issue by rose-jinyang** [mikel-brostrom/yolo_tracking#1042]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I found that this method does NOT estimate new position of object without detection of object.
In general, there are cases when there is NOT a detection result of an object at certain moment.
I think that new position estimation of an object should be done in even such case.
Do your methods support such cases?

**Comment by mikel-brostrom** [comment]
You are right, at the moment this is not supported. We have this in our backlog
