### ISSUE TITLE
yolo model yolo_nas_s doesnt work

### ISSUE THREAD

**Issue by Syavaprd** [mikel-brostrom/yolo_tracking#1044]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

 File "/content/yolo_tracking/boxmot/trackers/deepocsort/deep_ocsort.py", line 531, in _get_features
    features = self.embedder(im_crops).cpu()
ValueError: tile cannot extend outside image

Error with  yolo model yolo_nas_s 

### Environment

!pip install -v -e /content/yolo_tracking/.

### Minimal Reproducible Example

!python3 /content/yolo_tracking/examples/track.py --yolo-model yolo_nas_s --tracking-method deepocsort --source /content/drive/MyDrive/firstvideo.mp4 --classes 0 --conf 0.3 --iou 0.5  --reid-model lmbn_n_cuhk03_d.pt

**Comment by mikel-brostrom** [comment]
Can reproduce. WIll have a look at it right away.

**Comment by mikel-brostrom** [comment]
Weird. This:

`preds[:, [0, 2]] = torch.clip(preds[:, [0, 2]], min=0)`

works. THis does not:

`preds[:, [0, 2]] = torch.clip(preds[:, [0, 2]], min=0, max=im_w)`

**Comment by mikel-brostrom** [comment]
I tested this. Seems to work, but let me know :smile:
