### ISSUE TITLE
load custom yolov8 model 

### ISSUE THREAD

**Issue by prince0310** [mikel-brostrom/yolo_tracking#1045]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

```python3  examples/track.py  --source /home/alien/Downloads/39.avi  --save  --yolo-model /home/alien/Downloads/Mobile_Final.pt```

i have used this and got 

```Traceback (most recent call last):
  File "examples/track.py", line 280, in <module>
    main(opt)
  File "examples/track.py", line 275, in main
    run(vars(opt))
  File "/home/alien/.local/lib/python3.8/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "examples/track.py", line 99, in run
    model = Yolo(
TypeError: 'NoneType' object is not callable
```

### Environment

`

### Minimal Reproducible Example

`

**Comment by mikel-brostrom** [comment]
You are running the yolo examples. How did you install the repo?

**Comment by mikel-brostrom** [comment]
I see what the issue is... You model has to contain yolov8 in its name, i.e.

python3  examples/track.py  --source /home/alien/Downloads/39.avi  --save  --yolo-model /home/alien/Downloads/yolov8_Mobile_Final.pt

**Comment by prince0310** [comment]
ok let me try by renaming it
