### ISSUE TITLE
Why id is not showing while using tracker in custom model 

### ISSUE THREAD

**Issue by prince0310** [mikel-brostrom/yolo_tracking#1046]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

when i have implemented my custom model detection is working fine but id is not showing on to of the bounding box . 

`python3  examples/track.py --tracking-method deepocsort --source /home/alien/Downloads/39.avi  --save  --yolo-model /home/alien/Downloads/yolov8_Mobile_Final.pt`

**Comment by mikel-brostrom** [comment]
Sorry, have no issue with this.  Which ultralytics version do you have installed?

**Comment by prince0310** [comment]
ultralytics==8.0.124

**Comment by mikel-brostrom** [comment]
Ah, wait you only want to show the video? Use `--show`

**Comment by prince0310** [comment]
i am already using --show

**Comment by prince0310** [comment]
however its working fine in default yolo models

**Comment by mikel-brostrom** [comment]
hm... Don't have a custom model to debug this

**Comment by prince0310** [comment]
@mikel-brostrom its latest version of ultralytics 
[you can use this model to debug ](https://github.com/prince0310/Men-wome-detection-using-yolov8-.git)

**Comment by mikel-brostrom** [comment]
Sorry but have no issue with this. Tried it with the provided model on a newly cloned repo.

![Screenshot from 2023-08-09 15-46-38](https://github.com/mikel-brostrom/yolo_tracking/assets/18719680/0d57895f-5b37-4f0d-ae05-c05db3731573)
