### ISSUE TITLE
Fatal destinatio path

### ISSUE THREAD

**Issue by lakyfarky** [mikel-brostrom/yolo_tracking#1050]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

I am running the google colab tutorial to evaluate MOT16 and got this errors:

File "/usr/local/lib/python3.10/dist-packages/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/usr/local/lib/python3.10/dist-packages/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 92, in __init__
    raise TrackEvalException('GT file not found for sequence: ' + seq)
trackeval.utils.TrackEvalException: GT file not found for sequence: MOT16-14

GT file not found /usr/local/lib/python3.10/dist-packages/examples/val_utils/data/MOT16/test//MOT16-14/gt/gt.txt

Seems that root directory is python env directory which cause tons of errors?

### Environment

Google colab

### Minimal Reproducible Example

!python examples/val.py --tracking-method deepocsort --benchmark MOT16 --imgsz 320 --conf 0.2 --split "test"

**Comment by mikel-brostrom** [comment]
Notice that in order to run `val.py` you have to install the repo by:

```bash
git clone https://github.com/mikel-brostrom/yolo_tracking.git
pip install -v -e .
```

**Comment by lakyfarky** [comment]
I ran a basic installation snippet that install boxmot==10.0.17, then I install 10.0.24 and still got the same error.

```
!pip install --upgrade pip setuptools
!git clone https://github.com/mikel-brostrom/yolo_tracking.git  # clone repo
!pip install ultralytics
!pip install -v -e .
!pip install boxmot==10.0.24
```

error: FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.10/dist-packages/assets/MOT17-mini/train'

Then I ran new command with path to MOT17-mini
```
!python examples/val.py --tracking-method deepocsort --benchmark "/content/yolo_tracking/assets/MOT17-mini" --imgsz 320 --conf 0.2
```

and got same error in different format

File "/usr/local/lib/python3.10/dist-packages/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/usr/local/lib/python3.10/dist-packages/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-11-FRCNN.txt

**Comment by mikel-brostrom** [comment]
Sorry. This is not how the package is supposed to be installed. Follow the README. Cannot help you unless you do so

**Comment by mikel-brostrom** [comment]
If you want to run the yolo examples. The installation is as simple as :

```
git clone https://github.com/mikel-brostrom/yolo_tracking.git
pip install -v -e .
```
