### ISSUE TITLE
Unique ID issues

### ISSUE THREAD

**Issue by Harini-tech** [mikel-brostrom/yolo_tracking#1055]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

In Yolov5 and Strongsort with OSNet 
![frame1](https://github.com/mikel-brostrom/yolo_tracking/assets/89398191/baba20ba-8bc1-4737-87ba-d4c840188819)
![frame2](https://github.com/mikel-brostrom/yolo_tracking/assets/89398191/40424037-162d-4b82-b120-b96bb025458c)
![frame3](https://github.com/mikel-brostrom/yolo_tracking/assets/89398191/55ffa917-146b-4fda-9501-c5be8b9ccf79)
If person pass the pole means new object ID is created, How to make the Unique object ID ?

In above image person Object Id 60 is changed into Object Id 103 for the same person.

**Comment by mikel-brostrom** [comment]
You may benefit from multiple predictions ahead with the KFs. But this is not something that we provide at the moment.

**Comment by Harini-tech** [comment]
I have updated code with yolov5 but I'm still facing the same issues.
