### ISSUE TITLE
Tracking Example: Multiple Errors

### ISSUE THREAD

**Issue by JPhiDev** [mikel-brostrom/yolo_tracking#1059]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I have used your repository before and everything has worked very well. I see there have been quite a few updates since my last clone.

I cloned to my new Orin Nano and ran the example "track.py" just to verify everything is working and I keep getting the following errors. Not sure why. Yolov8 runs by itself. I haven't made any edits to your example. I just can't run your "track.py" example like I have before. I installed using your installation directions.
I am not sure if this is a bug or if have done something wrong, but not sure where to start on this considering I have successfully run this example with no problems before.

Thank you for the help in advanced!
![error](https://github.com/mikel-brostrom/yolo_tracking/assets/78062088/98f9f480-db0e-44e1-833c-0a3b5b735de4)

**Comment by mikel-brostrom** [comment]
There has been so many changes in the repo lately that I would recommend you to start from a clean slate. Start from scratch with the environment as well. The old won't do
