### ISSUE TITLE
How can I test half of the MOT17 dataset？

### ISSUE THREAD

**Issue by Gloria949** [mikel-brostrom/yolo_tracking#1065]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I have seen your experiment "Evaluation of the params evolved for first half of MOT17 on the complete MOT17
" and I would like to know how to conduct testing experiments on the first or second half of the MOT17 sequence, just like many ablation experiments in papers.

The model I am using is yolov8n+botsort+osnet

**Comment by mikel-brostrom** [comment]
I used this script to split the data: https://github.com/mikel-brostrom/yolo_tracking/blob/split-ds-by-factor/split.py :smile:

**Comment by Gloria949** [comment]
Thank you very much for your reply. My problem has been resolved.：）
