### ISSUE TITLE
How to get the segmentation tracking result as your demo video?

### ISSUE THREAD

**Issue by dedoogong** [mikel-brostrom/yolo_tracking#1069]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I found only the first frame shows the seg+box prediction result when I use webcam. 
I debugged the code and saw the self.mask is empty after the first frame. 
However, your demo video always shows the segmentation results very well. 
Please, give me some hint, how to do it?

**Comment by mikel-brostrom** [comment]
Sorry. This feature is now working at the moment

**Comment by mikel-brostrom** [comment]
Working on this at the moment

**Comment by mikel-brostrom** [comment]
This is once again working for yolov8 :rocket: and the ind output from the trackers can now be used for other non-yolov8 models to match tracks with segmentation masks and pose estimations.
