### ISSUE TITLE
what is ‘ts’ under the part Complete in README.md?

### ISSUE THREAD

**Issue by Alhambra-H** [mikel-brostrom/yolo_tracking#1076]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/101339907/2ea9767c-c101-49f3-aeca-3164d882565d)

**Comment by mikel-brostrom** [comment]
README updated :smile: . Should be tracks

**Comment by Alhambra-H** [comment]
> README updated 😄 . Should be tracks

i guess so! thank U! 
But why the performance of deepocsort is worse than bytesort which is built in yolov8?
i both use the yolov8n.pt and the same video, but many cars and trunks that can be detect by bytesort can not be detect using deepocsort. i am confused.....

**Comment by Alhambra-H** [comment]
> They should always be tuned for your specific use-ca
thanks for ur replying!
i also tried the track.py and code in Complete.Both using Deepocsort. But the results seem to be different.in this time, i use the same config, the performance of code in Complete is worse...
