### ISSUE TITLE
To Increase FPS

### ISSUE THREAD

**Issue by Harini-tech** [mikel-brostrom/yolo_tracking#1077]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

To Increase the FPS , can Extract the features in YOLOV5 Network for Strong sort.

**Comment by mikel-brostrom** [comment]
The reid models are trained to be as separate as possible in embedding space. This is not the case for yolov5, hence I cannot recommend to use yolov5 for feature extraction.

**Comment by Harini-tech** [comment]
Thank you very much. I'm new to object tracking and won't be using Strongsort with multiple cameras since its feature extraction consumes more FPS. My goal is to achieve accurate tracking while maintaining an FPS of around 60 for video input. Kindly suggest a suitable tracker.

**Comment by mikel-brostrom** [comment]
Either bytetrack or ocsort for maximum FPS

**Comment by Harini-tech** [comment]
Executing "strongsort" with a custom Reid model file can i achieve an FPS of around 60 ?

**Comment by mikel-brostrom** [comment]
Nope

**Comment by Harini-tech** [comment]
I require assistance in extracting features from the YOLOv5 network for the purpose of using them in the StrongSort.
can you provide more context in below comment.
https://github.com/ultralytics/yolov5/issues/10598#issuecomment-1366563940

**Comment by mikel-brostrom** [comment]
Extracting features using Yolov5 is a question for Ultralytics

**Comment by Harini-tech** [comment]
I am currently working on a task that involves feature extraction using **YOLOv5** for **StrongSort**. Could you please provide guidance on how to resolve this problem ?

**Comment by mikel-brostrom** [comment]
Yolov5 related questions should be asked here: https://github.com/ultralytics/yolov5. We don't even support Yolov5 anymore.
