### ISSUE TITLE
argparse not working?

### ISSUE THREAD

**Issue by lonnylundsten** [mikel-brostrom/yolo_tracking#1079]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Argparse seems to have stopped working. Recent downloads of the code don't allow me to save text, save mot, adjust vid stride etc. 

### Environment

-- various

### Minimal Reproducible Example

flags seem to have no effect.
--save --save-txt --save-mot --vid-stride 60

**Comment by mikel-brostrom** [comment]
Should be fixed now

`--save` works
`--save-mot` was working as well
`--vid-stride` had to be added

Let me know :smile:

**Comment by lonnylundsten** [comment]
Yes, those are working now. Thank you. When using --save-mot, it is saving to the source directory rather than the runs/track/exp directory. It would be nice if the final outputs all landed in the same location. That may be why I mistakingly thought --save-mot wasn't working. Maybe if I use the --project and --name flags that can direct where these get saved. Either way, these are working as expected so thanks again!

```
Results saved to /content/drive/MyDrive/yolo_tracking/runs/track/exp
55 labels saved to /content/drive/MyDrive/yolo_tracking/runs/track/exp/labels
MOT results saved to /content/drive/Shareddrives/Machine_Learning_Data/MBARI-MB-Benthic/mb-benthic-test-video/benthic_short_test_files/output003.mp4.txt
```

**Comment by lonnylundsten** [comment]
Also, '--line-width' doesn't seem to be working either.

**Comment by lonnylundsten** [comment]
I was able to fix the line width issue by adding the following to /examples/track.py:

```
line 85:         line_width=args.line_width

line 192: parser.add_argument('--line_width', default=None, type=int,
                        help='The line width of the bounding boxes. If None, it is scaled to the image size.')
```

**Comment by mikel-brostrom** [comment]
Added `line_width` arg! But pleas `git pull`. MOT are saved under `track/expN/mot/....txt` in later releases of this repo
