### ISSUE TITLE
HybirdSORT

### ISSUE THREAD

**Issue by Zhengzhiyang0000** [mikel-brostrom/yolo_tracking#1081]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Hello, I recently came across a HybirdSORT tracking algorithm, any plans to integrate it? Here is the link
https://github.com/ymzis69/HybirdSORT

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
It is not providing boosts on any of the main metrics compared to the existing methods in this package. Will wait till a more relevant methods is published :smile: . But thanks for letting me know, added to my pile of papers :smile:

**Comment by Zhengzhiyang0000** [comment]
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/95676739/eb740daf-01a1-40fc-9aea-13854c72f211)
Here are the results from his paper

**Comment by mikel-brostrom** [comment]
Aha, dancetrack results! Ok, so very good results on highly occluded with non-linear motion.

**Comment by mikel-brostrom** [comment]
I now consider implementing this :+1:. Thanks for pointing this out @Zhengzhiyang0000

**Comment by mikel-brostrom** [comment]
Hybridsort working here: https://github.com/mikel-brostrom/yolo_tracking/pull/1087. Will be merged tomorrow to master after checking HOTA

**Comment by mikel-brostrom** [comment]
HybridSORT now available @Zhengzhiyang0000 in master!

**Comment by koihoo** [comment]
> 

hi，thanks your greate work！please tell me how to use my own yolov8.py with HybridSORT?
i use following command
`python examples/track.py --yolo-model /weights/yolov8.pt --tracking-method hybridsort --source TundraSwan2.mp4 `

**Comment by mikel-brostrom** [comment]
Yup, that is the right way :smile:
