### ISSUE TITLE
Fatal destination path during the custom object tracking evaluation

### ISSUE THREAD

**Issue by lakyfarky** [mikel-brostrom/yolo_tracking#1086]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

Hi, I followed [custom tracking evaluation](https://github.com/mikel-brostrom/yolo_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) and step 0 is okay. I set my dataset into the corresponding structure and then this error happens:
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/63816990/d2bd96cc-976a-43fc-92ab-d9fa0e35432b)

### Environment

Google colab

### Minimal Reproducible Example

!python examples/val.py --yolo-model "/content/drive/MyDrive/master/el_yolov8s.pt" --benchmark MOTCUSTOM --split test --tracking-method strongsort

**Comment by mikel-brostrom** [comment]
Thx for pointing this out @lakyfarky! CHeck this line of code. Adapt it to your needs:

https://github.com/mikel-brostrom/yolo_tracking/blob/7ff8de0f344dfd9a8cab1c4f2b4fa729a8ba98e8/examples/val.py#L238

**Comment by lakyfarky** [comment]
Thanks, it works until the tracking step. I rewrite code as in [multi-class eval](https://github.com/mikel-brostrom/yolo_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) to adapt script to my classes. Error is distractor class 'person_on_vehicle'. 

``` 
!python examples/val.py --yolo-model "/content/drive/MyDrive/master/yolov8s_vd.pt" --benchmark MOTCUSTOM --split val --tracking-method strongsort --classes 0 1 2 3 4 5 6 7 8 9
```

2023-08-21 08:10:05.689 | ERROR    | __main__:eval:256 - 
Eval Config:
USE_PARALLEL         : True                          
NUM_PARALLEL_CORES   : 4                             
BREAK_ON_ERROR       : True                          
RETURN_ON_ERROR      : False                         
LOG_ON_ERROR         : /content/yolo_tracking/examples/val_utils/error_log.txt
PRINT_RESULTS        : True                          
PRINT_ONLY_COMBINED  : False                         
PRINT_CONFIG         : True                          
TIME_PROGRESS        : True                          
DISPLAY_LESS_PROGRESS : False                         
OUTPUT_SUMMARY       : True                          
OUTPUT_EMPTY_CLASSES : True                          
OUTPUT_DETAILED      : True                          
PLOT_CURVES          : True                          

MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : /content/yolo_tracking/examples/val_utils/data/MOTCUSTOM/val
TRACKERS_FOLDER      : /content/yolo_tracking/runs/val/exp4
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['mot']                       
CLASSES_TO_EVAL      : ['pedestrian', 'people', 'bicycle', 'car', 'van', 'truck', 'tricycle', 'awning-tricycle', 'bus', 'motor']
BENCHMARK            :                               
SPLIT_TO_EVAL        : val                           
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   :                               
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'MOTCUSTOM-01': None}        
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          

CLEAR Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity'] 
THRESHOLD            : 0.5                           
PRINT_CONFIG         : True                          

Identity Config:
METRICS              : ['HOTA', 'CLEAR', 'Identity'] 
THRESHOLD            : 0.5                           
PRINT_CONFIG         : True                          

Evaluating 1 tracker(s) on 1 sequence(s) for 10 class(es) on MotChallenge2DBox dataset using the following metrics: HOTA, CLEAR, Identity, Count


Evaluating mot

Tracker mot was unable to be evaluated.
'person_on_vehicle'

**Comment by mikel-brostrom** [comment]
TrackEval is not build for multi-class evaluations

**Comment by mikel-brostrom** [comment]
Check this out: https://github.com/mikel-brostrom/yolo_tracking/issues/927

**Comment by lakyfarky** [comment]
Thanks, I'll try it.
