### ISSUE TITLE
C++

### ISSUE THREAD

**Issue by G7b9** [mikel-brostrom/yolo_tracking#1094]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Are you considering supporting an implementation in C++?

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Yup, but don't have time at the moment. Meanwhile you can check out: https://github.com/viplix3/BoTSORT-cpp/tree/main
