### ISSUE TITLE
Observed a bug when trying to predict on a custom sequence where track.py 's MOT.txt output gene

### ISSUE THREAD

**Issue by Jumabek** [mikel-brostrom/yolo_tracking#1099]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug
Possibly due to using geenrator for the sequence results on track.py
```
  results = yolo.track(
        source=args.source,
        conf=args.conf,
        iou=args.iou,
        show=args.show,
        stream=True,
        device=args.device,
        show_conf=args.show_conf,
        save_txt=args.save_txt,
        show_labels=args.show_labels,
        save=args.save,
        verbose=args.verbose,
        exist_ok=args.exist_ok,
        project=args.project,
        name=args.name,
        classes=args.classes,
        imgsz=args.imgsz,
        vid_stride=args.vid_stride,
        line_width=args.line_width
    )

```

Below is the MOT log of the custom sequence from the below command. 

Bug is where more frames are generated  in MOT output than available frames in the sequence. For instance there are total of 766 frames. but 910 are logged by track.py

```
[Sequence]
name=VIRAT_S_010000_06_000728_000762
imDir=img1
frameRate=30
seqLength=766
imWidth=1920
imHeight=1080
imExt=.jpg
```

`python examples/track.py --tracking-method strongsort --yolo-model yolox_m --source /home/juma/code/luqmon_tracking/examples/val_utils/data/VIRAT-S/train/VIRAT_S_010000_06_000728_000762/img1 --save --save-mot
`

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/4343873/d251a0bd-9ef2-4e03-be5c-4696da294874)

[VIRAT_S_010000_06_000728_000762.txt](https://github.com/mikel-brostrom/yolo_tracking/files/12502179/VIRAT_S_010000_06_000728_000762.txt)

### Environment

- YOLO tracking 10.0.42
- mikel's ultralytics 
- Ubuntu 2022.04

### Minimal Reproducible Example

Link for data https://drive.google.com/file/d/13Tp-vxLI5AzJAOj1BZKqCKWGx2m1ET7U/view?usp=drive_link

After unzipping the data, run the command

`python examples/track.py --tracking-method strongsort --yolo-model yolox_m --source /home/juma/code/luqmon_tracking/examples/val_utils/data/VIRAT-S/train/VIRAT_S_010000_06_000728_000762/img1 --save --save-mot
`

**Comment by Jumabek** [comment]
I would be glad to contribute the fix with your supervision @mikel-brostrom

**Comment by mikel-brostrom** [comment]
I am not entirely sure this is fixable as TrackEval uses these files to compare the generate output with the one specified in this file. What would be perfect is that somebody implement HOTA in PYMOTMETRICS. Then all those files would not be needed :smile:

**Comment by Jumabek** [comment]
I understand, thank you for the response @mikel-brostrom .
