### ISSUE TITLE
Tracker file not found: mot//MOT17-02-FRCNN.txt

### ISSUE THREAD

**Issue by uopop** [mikel-brostrom/yolo_tracking#1100]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I ran the instructions in the readme file：
python3 examples/val.py --yolo-model yolox_s.pt    --reid-model osnet_ain_x1_0_msmt17.pt  --tracking-method ocsort     --benchmark MOT17
The following error occurred：
2023-09-03 16:02:14.655 | SUCCESS  | __main__:eval:220 - Evaluation succeeded
val: yolo_model=yolox_s.pt, reid_model=/root/autodl-tmp/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt, tracking_method=ocsort, name=exp, classes=['0'], project=/root/autodl-tmp/yolo_tracking/runs/val, exist_ok=False, gsi=False, benchmark=MOT17-mini, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], save=False, processes_per_device=2
2023-09-03 16:02:14.967 | ERROR    | __main__:eval:255 - Traceback (most recent call last):
  File "/root/autodl-tmp/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/root/autodl-tmp/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-02-FRCNN.txt
I feel like it's a path issue, but I don't know how to solve it. I hope to receive help. Thank you very much！

**Comment by mikel-brostrom** [comment]
Post the whole output please. The tracking threads are crashing way before this:

```bash
File "/root/autodl-tmp/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in init
raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-02-FRCNN.txt
I feel like it's a path issue, but I don't know how to solve it. I hope to receive help. Thank you very much！
```

**Comment by Gloria949** [comment]
Hello, I have also encountered a similar issue. The terminal has already output "Evaluation succeeded", but after that, an error message will be reported that the file cannot be found. My terminal information is as follows:


`2023-09-08 18:17:48.325 | SUCCESS  | __main__:eval:230 - Evaluation succeeded
val: yolo_model=/home/extend/zhy/code/yolo_tracking-masterold/runs/train/exp28/weights/yolov8fema.pt, reid_model=pretrained/lmbn_n_market.pth, tracking_method=ocsort, name=exp, classes=['0'], project=/home/extend/zhy/code/yolo_tracking-masterold/examples/runs/val, exist_ok=False, gsi=False, benchmark=MOT17, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[0, 1, 0, 1, 0, 1], processes_per_device=2
2023-09-08 18:17:48.683 | ERROR    | __main__:eval:267 - Traceback (most recent call last):
  File "/home/extend/zhy/code/yolo_tracking-masterold/examples/val_utils/scripts/run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "/home/extend/zhy/code/yolo_tracking-masterold/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: labels//MOT17-02-SDP.txt`


When I rerun the command, this issue still occurs. It appears that the program did not successfully write to the MOT.txt file, and the corresponding label folder cannot be found in the corresponding directory. There are only some dataset images that appear to have not been successfully detected.
Therefore, I speculate that there was a problem with the detector model that resulted in the failure to successfully detect the target and execute the write file code.

**Comment by mikel-brostrom** [comment]
Again. Please, provide the COMPLETE output. I cannot help you without it

**Comment by vankhoa21991** [comment]
You should remove --save from the config if you have one.

**Comment by fangfang0304** [comment]
> ### Search before asking
> * [x]  I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.
> 
> ### Question
> I ran the instructions in the readme file： python3 examples/val.py --yolo-model yolox_s.pt --reid-model osnet_ain_x1_0_msmt17.pt --tracking-method ocsort --benchmark MOT17 The following error occurred： 2023-09-03 16:02:14.655 | SUCCESS | **main**:eval:220 - Evaluation succeeded val: yolo_model=yolox_s.pt, reid_model=/root/autodl-tmp/yolo_tracking/examples/weights/osnet_x0_25_msmt17.pt, tracking_method=ocsort, name=exp, classes=['0'], project=/root/autodl-tmp/yolo_tracking/runs/val, exist_ok=False, gsi=False, benchmark=MOT17-mini, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], save=False, processes_per_device=2 2023-09-03 16:02:14.967 | ERROR | **main**:eval:255 - Traceback (most recent call last): File "/root/autodl-tmp/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py", line 84, in dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)] File "/root/autodl-tmp/yolo_tracking/examples/val_utils/trackeval/datasets/mot_challenge_2d_box.py", line 124, in **init** raise TrackEvalException( trackeval.utils.TrackEvalException: Tracker file not found: mot//MOT17-02-FRCNN.txt I feel like it's a path issue, but I don't know how to solve it. I hope to receive help. Thank you very much！

hi, I have also encountered a similar issue.did u solve this problem? @uopop

**Comment by mikel-brostrom** [comment]
Are you following `Evaluation` under: https://github.com/mikel-brostrom/yolo_tracking#yolov8--yolo-nas--yolox-examples

**Comment by fangfang0304** [comment]
> Are you following `Evaluation` under: https://github.com/mikel-brostrom/yolo_tracking#yolov8--yolo-nas--yolox-examples

yes

**Comment by mikel-brostrom** [comment]
Please provide the FULL output of the run

**Comment by fangfang0304** [comment]
> Please provide the FULL output of the run

val: yolo_model=D:/yolov8_tracking-master/examples/weights/try.pt, reid_model=D:/yolov8_tracking-master/examples/weights/osnet_x0_25_msmt17.pt, tracking_method=deepocsort, name=exp, classes=['0'], project=D:\yolov8_tracking-master\examples\runs\val, exist_ok=False, benchmark=MOT17-mini, split=train, eval_existing=False, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
2024-01-17 21:54:06.772 | ERROR    | __main__:eval:260 - Traceback (most recent call last):
  File "D:\yolov8_tracking-master\examples\val_utils\scripts\run_mot_challenge.py", line 84, in <module>
    dataset_list = [trackeval.datasets.MotChallenge2DBox(dataset_config)]
  File "D:\yolov8_tracking-master\examples\val_utils\trackeval\datasets\mot_challenge_2d_box.py", line 124, in __init__
    raise TrackEvalException(
trackeval.utils.TrackEvalException: Tracker file not found: labels//MOT17-05-FRCNN.txt

thank you!

**Comment by mikel-brostrom** [comment]
Probably something failed when generating the predictions txts for MOT evaluation. You have just not noticed that it failed.
