### ISSUE TITLE
Association matching bug

### ISSUE THREAD

**Issue by Hojest** [mikel-brostrom/yolo_tracking#1111]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

There is a problem when i using ocsort to make predictions

in yolo_tracking/boxmot/utils/association.py
Line: 143:
scores = np.repeat(detections[:, -1][:, np.newaxis], trackers.shape[0], axis=1)

if you print the detections, you can find the [-1] array is the index column(0,1,2,3,4...), so it's clearly incorrect to mulitiply it with the angle_diff_cost  in the following line 149:
angle_diff_cost = angle_diff_cost * scores
 
i guess maybe in previous version, the [-1]clomun of detections is the conf column, but after revision or update, it's changed.
Actually i downloaded the code version in June before, but the same error.
So hopefully you could help me figure out whether this issue is a bug or the regular process (but i truely doubt it according to these paper, OCSORT Deep-OCSORT).
I use the official  ultralytics and change the det.data because i cannot install your custom version, but i search the det boxes return, it's the same way, so in your custom version of ultralytics, the last column will be the INDEX column too. 

### Environment

Name: ultralytics
Version: 8.0.145
Summary: Ultralytics YOLOv8 for SOTA object detection, multi-object tracking, instance segmentation, pose estimation and image classification.
Home-page: https://github.com/ultralytics/ultralytics

### Minimal Reproducible Example

python examples/track.py --yolo-model ANYMODEL --tracking-method ocsort --source ANYSOURCE --device 0 --classes 0

**Comment by mikel-brostrom** [comment]
Thanks for reporting this bug @Hojest . Fixed. Merging as soon as the CI passes, updating the scores in README as well :rocket:
