### ISSUE TITLE
bytetracker results are not accurate in recent updates

### ISSUE THREAD

**Issue by jhamed-dp** [mikel-brostrom/yolo_tracking#1113]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

I've been using byte-tracker in my project since version 10.0.15. results are accurate for my stream objects. I have recently updated my project with the latest version using `pip install -U boxmot`. but object tracking accuracy drops and actually is awful.
there are no other changes in other scripts. after downgrading to the previous version everything is correct now again.

### Environment

- python 3.8.10
- boxmot 10.0.42

### Minimal Reproducible Example

`self.tracker = {1: BYTETracker(
                track_thresh=self.args.bytetracker_config.track_thresh,  # tracking confidence threshold
                track_buffer=self.args.bytetracker_config.track_buffer,  # the frames for keep lost tracks
                match_thresh=self.args.bytetracker_config.match_thresh,  # matching threshold for tracking
            )}`

**Comment by mikel-brostrom** [comment]
Do you have results on your custom dataset? I am afraid I cannot help you otherwise. Lower MOTA often indicated problems with Kalman Filter, lower IDF1 with association and/or appearance extraction...

**Comment by jhamed-dp** [comment]
@mikel-brostrom
thanks, I was unaware of changes in output shape from (N, 7) to (N, 8).
