### ISSUE TITLE
The question is about the shape of output

### ISSUE THREAD

**Issue by Bulua** [mikel-brostrom/yolo_tracking#1114]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

`preds = self.inference(im, *args, **kwargs)`
this preds is：
preds:
    [0] (1, 56, 4620)
    [1]:
        [0] has there items
            [0] (1, 65, 44, 80)
            [1] (1, 65, 22, 40)
            [2] (1, 65, 11, 20)
        [1] (1, 51, 4620)

what is means of 56、65 and 51？

**Comment by mikel-brostrom** [comment]
I don't know what you are running. I cannot help you without a minimal example to reproduce your output

**Comment by Bulua** [comment]
> I don't know what you are running. I cannot help you without a minimal example to reproduce your output

According to the problem, I traced it to ultralytics.utils.ops.py -> func: non_max_suppression(). I don’t quite understand what the masks in the variable prediction represent?

**Comment by mikel-brostrom** [comment]
I still don't know what you are running

**Comment by Bulua** [comment]
Oh, i'm so sorry, i am running yolo_tracking/examples/track.py
