### ISSUE TITLE
Why does ByteTrack not use the feature model

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/yolo_tracking#1116]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Why does ByteTrack not use the feature model, I see that the original algorithm uses the tracking model。Is there any consideration

**Comment by mikel-brostrom** [comment]
The [original implementation](https://github.com/ifzhang/ByteTrack) does NOT include a ReID model
