### ISSUE TITLE
IoU is not a great fit for small/fast moving objects

### ISSUE THREAD

**Issue by colonelpanic8** [mikel-brostrom/yolo_tracking#1118]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

IoU is not a great fit for small/fast moving objects because there can easily be no overlap in cases where detections are actually quite close.

There are other metrics where the tolerance for discrepancy between the distance between detections does not depend on the size of the detected object like centroid distance.

Ideally, the Tracker class should abstract over the distance metric that is used. IoU could be the default, but in some cases centroid distance + perhaps a separate box size comparison might be more appropriate.

IOU is hard coded e.g. here:
https://github.com/mikel-brostrom/yolo_tracking/blob/05172962914805dab99acb3d2d8592797dbf38a7/boxmot/trackers/strongsort/sort/tracker.py#L147

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/1246

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/pull/1247
