### ISSUE TITLE
TypeError: create_tracker() missing 1 required positional argument: 'per_class'

### ISSUE THREAD

**Issue by zhang-mu-zhi** [mikel-brostrom/yolo_tracking#1120]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

When I try to run the following command：

python track-dp.py --yolo-model yolov8s.pt --tracking-method strongsort  --source 2.mp4 --yolo-model yolov8s.pt --img 640 --reid-model osnet_x0_25_market1501.pt --save

There is an error:

(yolov8_deepsort_10.1) E:\yolov5_deepsort\deepsort\mikel-brostrom\v10.1\yolo_tracking-v.10.1\examples>python track-dp.py --yolo-model
 yolov8s.pt --tracking-method strongsort  --source 2.mp4 --yolo-model yolov8s.pt --img 640 --reid-model osnet_x0_25_market1501.pt --s
ave
track-dp: yolo_model=yolov8s.pt, reid_model=osnet_x0_25_market1501.pt, tracking_method=strongsort, source=2.mp4, imgsz=[640], conf=0.
5, device=, show=False, save=True, classes=None, project=E:\yolov5_deepsort\deepsort\mikel-brostrom\v10.1\yolo_tracking-v.10.1\runs\t
rack, name=exp, exist_ok=False, half=False, vid_stride=1, hide_label=False, hide_conf=False, save_txt=False
Traceback (most recent call last):
  File "track-dp.py", line 229, in <module>
    main(opt)
  File "track-dp.py", line 224, in main
    run(vars(opt))
  File "D:\Anaconda\envs\yolov8_deepsort_10.1\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track-dp.py", line 96, in run
    predictor.run_callbacks('on_predict_start')
  File "D:\Anaconda\envs\yolov8_deepsort_10.1\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 339, in run_callbacks    
    callback(self)
  File "track-dp.py", line 35, in on_predict_start
    tracker = create_tracker(
TypeError: create_tracker() missing 1 required positional argument: 'per_class'

what should I do？

### Environment

pip install boxmot
pip install requirements.txt
conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

### Minimal Reproducible Example

>python track-dp.py --yolo-model
 yolov8s.pt --tracking-method strongsort  --source 2.mp4 --yolo-model yolov8s.pt --img 640 --reid-model osnet_x0_25_market1501.pt --s
ave

**Comment by mikel-brostrom** [comment]
The error is clear IMO:

```py
create_tracker(..., per_class=False)
```

**Comment by zhang-mu-zhi** [comment]
> IMO 的错误很明显。你只是在争论中遗漏了：
> 
> ```python
> create_tracker(..., per_class=False)
> ```

Following your suggestion, I changed track.py file line 35 from:

        tracker = create_tracker(
            predictor.args.tracking_method,
            predictor.args.tracking_config,
            predictor.args.reid_model,
            predictor.device,
            predictor.args.half,
        )

to

        tracker = create_tracker(
            predictor.args.tracking_method,
            predictor.args.tracking_config,
            predictor.args.reid_model,
            predictor.device,
            predictor.args.half,
            per_class=False
        )

But there is another error：

(yolov8_deepsort_10.1) E:\yolov5_deepsort\deepsort\mikel-brostrom\v10.1\yolo_tracking-v.10.1\examples>python track-dp.py --yolo-model
 yolov8s.pt --tracking-method strongsort  --source 2.mp4 --yolo-model yolov8s.pt --img 640 --reid-model osnet_x0_25_market1501.pt --s
ave
track-dp: yolo_model=yolov8s.pt, reid_model=osnet_x0_25_market1501.pt, tracking_method=strongsort, source=2.mp4, imgsz=[640], conf=0.
5, device=, show=False, save=True, classes=None, project=E:\yolov5_deepsort\deepsort\mikel-brostrom\v10.1\yolo_tracking-v.10.1\runs\t
rack, name=exp, exist_ok=False, half=False, vid_stride=1, hide_label=False, hide_conf=False, save_txt=False
Traceback (most recent call last):
  File "track-dp.py", line 230, in <module>
    main(opt)
  File "track-dp.py", line 225, in main
    run(vars(opt))
  File "D:\Anaconda\envs\yolov8_deepsort_10.1\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "track-dp.py", line 97, in run
    predictor.run_callbacks('on_predict_start')
  File "D:\Anaconda\envs\yolov8_deepsort_10.1\lib\site-packages\ultralytics\yolo\engine\predictor.py", line 339, in run_callbacks    
    callback(self)
  File "track-dp.py", line 35, in on_predict_start
    tracker = create_tracker(
  File "D:\Anaconda\envs\yolov8_deepsort_10.1\lib\site-packages\boxmot\tracker_zoo.py", line 30, in create_tracker
    max_dist=cfg.max_dist,
AttributeError: 'types.SimpleNamespace' object has no attribute 'max_dist'

what should I do？

The boxmot I installed is：
boxmot                    10.0.43                  pypi_0    pypi

Are these errors caused by the boxmot version?

**Comment by mikel-brostrom** [comment]
I have no issues running:

```py
from pathlib import Path
from boxmot import create_tracker


tracker = create_tracker(
    'deepocsort',
    '/home/mikel.brostrom/yolo_tracking/boxmot/configs/deepocsort.yaml',
    Path('mobilenetv2_x1_4_dukemtmcreid.pt'),
    'cpu',
    True,
    False
)
```

**Comment by zhang-mu-zhi** [comment]
> 我运行时没有任何问题：
> 
> ```python
> from pathlib import Path
> from boxmot import create_tracker
> 
> 
> tracker = create_tracker(
>     'deepocsort',
>     '/home/mikel.brostrom/yolo_tracking/boxmot/configs/deepocsort.yaml',
>     Path('mobilenetv2_x1_4_dukemtmcreid.pt'),
>     'cpu',
>     True,
>     False
> )
> ```

I am so sorry. I still can't successfully run the entire code. And I don't know where I went wrong.
Can you keep this issue open?
I'll keep trying to fix this error until I find the right solution.

**Comment by mikel-brostrom** [comment]
You must have introduced custom modifications that broke the tracker loading

**Comment by zhang-mu-zhi** [comment]
> 您必须引入了破坏跟踪器加载的自定义修改

I don't know where I went wrong before. But I only need to follow the steps of REDME to complete the identification and counting of yolov8 on the coco data set.

I'm sorry for the previous question, please close or delete this question.
Thank you very much for sharing

**Comment by mikel-brostrom** [comment]
per_class enables that all the objects associated to a specific class are handled sparately.
