### ISSUE TITLE
When I runned it,it got the following error.How can I solve it?Thx,plz

### ISSUE THREAD

**Issue by ZareAlucard** [mikel-brostrom/yolo_tracking#1123]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied

**Comment by mikel-brostrom** [comment]
I have no idea what you are trying to run here. `setup.py` is not something you need to run in order to get this repo running
