### ISSUE TITLE
Finetune Clip-ReID on custom dataset

### ISSUE THREAD

**Issue by NQHuy1905** [mikel-brostrom/yolo_tracking#1124]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Anyone have tried to finetune Clip Reid yet. I have check Clip-Reid repo but they only have train from scratch

**Comment by mikel-brostrom** [comment]
You may need to add custom functionality to the Clip-ReID repo for loading pretrained weights and then fine-tune on your own dataset.
