### ISSUE TITLE
ERROR: Could not build wheels for numpy, which is required to install pyproject.toml-based projects

### ISSUE THREAD

**Issue by karimda** [mikel-brostrom/yolo_tracking#1127]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

How can I resolve this issue when trying to install Boxmot or install the different requirements in txt file? I have found that the numpy 1.23.1 is compatible with 3.8.x Python/3.9.x Python version. Unfortunately, I wanted to install 3.8.x python version but on python site, these versions are still under maintenance and do not released yet. Additionally, I have tried other solutions with the installed 3.11 python version, but right now the issue is still persistent.

So, what are your recommendations, please? thank you.

### Environment

Python3.11

### Minimal Reproducible Example

pip install boxmot

**Comment by mikel-brostrom** [comment]
Python 3.8, 3.9 and 3.10 is tested in the pipeline. All three should work
