### ISSUE TITLE
How can I set ByteTrack parameters such as --track_buffer in command line?

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#1128]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, @mikel-brostrom,
How can I set ByteTrack parameters such as --track_buffer in command line?
Do you have solutions and do you have manual such parameters?

Thank you,

**Comment by mikel-brostrom** [comment]
Sorry, this is not possible. You have to set the parameters in the corresponding config file https://github.com/mikel-brostrom/yolo_tracking/tree/master/boxmot/configs of the tracking method you are using
