### ISSUE TITLE
RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'

### ISSUE THREAD

**Issue by hungconth** [mikel-brostrom/yolo_tracking#1129]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/76127579/bb2d3ee0-be50-4312-b240-7381adafdf07)

### Environment

- Python 3.10
- cpu, window11
- 

### Minimal Reproducible Example

I get the error "RuntimeError: "slow_conv2d_cpu" not implemented for 'Half'" at the line "tracks = tracker.update(dets, frame)". Please help me
## my code:
    
    import cv2
    import numpy as np
    from pathlib import Path
    import torch
    from boxmot import DeepOCSORT
    from ultralytics import YOLO
    
    tracker = DeepOCSORT(
        model_weights=Path('osnet_x0_25_msmt17.pt'), # which ReID model to use
        device='cpu',
        fp16=True,
    )
    
    color = (0, 0, 255)  # BGR
    thickness = 2
    fontscale = 0.5
    
    cap = cv2.VideoCapture("video_1.mp4")
    
    model = YOLO("yolov8n.pt")
    while(True):
        ret, frame = cap.read()
        frame = cv2.resize(frame,(1280,720))
    
        results = model(frame, save=True, imgsz=960)[0]  # predict on an image
        print("boxs:",results)
    
        t1 = results[0].boxes.xyxy
        t2 = results[0].boxes.conf
        t3 = results[0].boxes.cls
    
        dets = np.array(torch.cat([t1, t2.unsqueeze(1), t3.unsqueeze(1)], dim=1))
    
    
        tracks = tracker.update(dets, frame) # --> (x, y, x, y, id, conf, cls, ind)
    
        xyxys = tracks[:, 0:4].astype('int') # float64 to int
        ids = tracks[:, 4].astype('int') # float64 to int
        confs = tracks[:, 5]
        clss = tracks[:, 6].astype('int') # float64 to int
        inds = tracks[:, 7].astype('int') # float64 to int
    
        if tracks.shape[0] != 0:
            for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
                frame = cv2.rectangle(
                    frame,
                    (xyxy[0], xyxy[1]),
                    (xyxy[2], xyxy[3]),
                    color,
                    thickness
                )
                cv2.putText(
                    frame,
                    f'id: {id}, conf: {conf}, c: {cls}',
                    (xyxy[0], xyxy[1]-10),
                    cv2.FONT_HERSHEY_SIMPLEX,
                    fontscale,
                    color,
                    thickness
                )
    
        cv2.imshow('preview',frame)
        
        if cv2.waitKey(1) & 0xFF == ord('q'):
            break
    cap.release()
    cv2.destroyAllWindows()

**Comment by mikel-brostrom** [comment]
Half is not supported on `CPU`. THat is a GPU only feature

**Comment by hungconth** [comment]
My laptop doesn't have GPU, I solve this problem by replacing fp16=True to fp16=False, it works for me

**Comment by hungconth** [comment]
> Half is not supported on `CPU`. That flag is a GPU only feature

My laptop doesn't have GPU, I solve this problem by replacing fp16=True to fp16=False, it works for me

**Comment by mikel-brostrom** [comment]
Yes. `fp16=True` is not compatible `device='cpu'`. I will add a check for this
