### ISSUE TITLE
Include SUSHI as tracker

### ISSUE THREAD

**Issue by jesuscanram** [mikel-brostrom/yolo_tracking#1131]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

I have been looking into the state of the art, and the SUSHI tracker proposed in https://openaccess.thecvf.com/content/CVPR2023/papers/Cetintas_Unifying_Short_and_Long-Term_Tracking_With_Graph_Hierarchies_CVPR_2023_paper.pdf is the most performing I have found in the MOT17 benchmark. 

They also have made their code publicly available in https://github.com/dvl-tum/SUSHI, so I was thinking it could be a good incorporation as a tracker.

### Use case

I think it could be included into the boxmot as a new tracker. 

### Are you willing to submit a PR?

- [X] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
SUSHI is an offline only tracking method as far as I know. I only focus on real-time tracking. It may be possible to re-engineer it for real-time purposes. I would be more than happy to have look at your PR if you decide to submit one :smile:

**Comment by jokober** [comment]
also keep in mind that BoxMOT only supports IOU which might be a problem if you have fast moving objects. There is an issue here: https://github.com/mikel-brostrom/yolo_tracking/issues/1118
