### ISSUE TITLE
Use your own object detection model

### ISSUE THREAD

**Issue by xiangyangaa** [mikel-brostrom/yolo_tracking#1134]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

What should I do if I want to use my own improved YOLO v7 model as an object detection model in a multi-target tracking task?

**Comment by mikel-brostrom** [comment]
You have code examples here: https://github.com/mikel-brostrom/yolo_tracking#custom-object-detection-model-example
