### ISSUE TITLE
yolo_nas cannot filter out some target classes

### ISSUE THREAD

**Issue by chenke225** [mikel-brostrom/yolo_tracking#1136]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

The postprocess of yolov8 detector uses non_max_supperssion to filter the target for required classes. But, the postprocess of yolo_nas has no target classes filtering, so it cause yolo_nas to output all detected targets, resulting difficulties in following tracker processing, because there are so many detections to be processed, which constitues the workload of the tracks multiply.
Is there any way to make yolo_nas filter out the classes of target?

**Comment by mikel-brostrom** [comment]
Yup, I see. On it.

**Comment by chenke225** [comment]
hi, mikel,
thank you very much.

**Comment by chenke225** [comment]
@mikel-brostrom 
I have successfully added object class filters, enabling the extraction of user-specified object categories in the 'yolonas.py' postprocess() function. Will this addition introduce any new problems?
```
def postprocess(self, path, preds, im, im0s):

        results = []
        for i, pred in enumerate(preds):

            if pred is None:
                pred = torch.empty((0, 6))
                r = Results(
                    path=path,
                    boxes=pred,
                    orig_img=im0s[i],
                    names=self.names
                )
                results.append(r)
            else:
                pred[:, :4] = ops.scale_boxes(im.shape[2:], pred[:, :4], im0s[i].shape)
                # filter boxes by classes   ################################################
                 pred = pred[torch.isin(pred[:, 5].cpu(), torch.as_tensor(self.args.classes))]   # added by chenke

                r = Results(
                    path=path,
                    boxes=pred,
                    orig_img=im0s[i],
                    names=self.names
                )
            results.append(r)
        return results
```
THX.
