### ISSUE TITLE
Detector comparison for MOT?

### ISSUE THREAD

**Issue by ajtao** [mikel-brostrom/yolo_tracking#1142]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I was wondering if the owner of this repo or anyone else has performed a study to compare the impact of different detectors (yolox, yolov5, yolov6, … etc) upon the tracking metrics for a given tracker? Ideally this’d be done at similar inference cost but I suppose any data would be a step forward.

I had one experience where I compared Yolox-x to Yolov8-L and while the yolov8 detection metrics were indeed higher, for some reason my tracking results ended up being superior with yolox. It’s entirely possible that there this was user error on my side, which is why I was trying to see what others have found.

**Comment by mikel-brostrom** [comment]
I haven't seen a detector comparison yet. One difficulty in all this is that MOT datasets only have people in them. So while YolovA may have a higher mAP COCO score than YolovB. YolovB may still be better at detecting people. You would need to look into people specific metrics so be sure, beforehand, that a certain Yolo method is better than another on MOT.

**Comment by ajtao** [comment]
It's a good point that coco mAP != pedestrian mAP, although what was really weird was that i did retrain yolov8-L and achieved higher detection scores than my yolox-x detector on a pedestrian type dataset. It's why i suspected some user error on my part. I did visualize things and found that yolox-x appeared to be resolving partially occluded humans better than yolov8.

Anyways, thank you for the quick reply. Probably a good intern project :).

**Comment by sourabhyadav** [comment]
@ajtao - I've been looking into comparing yolov5 and yolov8 models for MOT recently, but I'm not able to run yolov5 in the latest master branch. I encountered the following error:  'Your model name has to contain either yolox, yolo_nas or yolov8'. 
Just wanted to know if you tried yolov5 as a model? And if yes, then how?

**Comment by mikel-brostrom** [comment]
Are you trying to load an old yolov5 model, trained using the yolov5 repo?
