### ISSUE TITLE
yolox cannot detect objects in classes other than class 0 "person" in examples/track.py

### ISSUE THREAD

**Issue by chenke225** [mikel-brostrom/yolo_tracking#1143]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Is only class 0 "person" applicable to  yolox detector in  boxmot package ? when using examples/track.py with yolox+strongsort, only "person" object can be detected by yolox. I check examples/detectors/yolox.py, there always set exp.num_classes =1 , please see below with mark <------------------.
```
class YoloXStrategy(YoloInterface):
    def __init__(self, model, device, args):

        self.args = args
        self.pt = False
        self.stride = 32  # max stride in YOLOX

        # model_type one of: 'yolox_n', 'yolox_s', 'yolox_m', 'yolox_l', 'yolox_x'
        model_type = self.get_model_from_weigths(YOLOX_ZOO.keys(), model)

        if model_type == 'yolox_n':
            exp = get_exp(None, 'yolox_nano')
        else:
            exp = get_exp(None, model_type)

        LOGGER.info(f'Loading {model_type} with {str(model)}')

        # download crowdhuman bytetrack models
        if not model.exists() and model.stem == model_type:
            LOGGER.info('Downloading pretrained weights...')
            gdown.download(
                url=YOLOX_ZOO[model_type + '.pt'],
                output=str(model),
                quiet=False
            )
            # needed for bytetrack yolox people models 
            # update with your custom model needs      
            exp.num_classes = 1              # <-----------------------------------
        elif model.stem == model_type:
            exp.num_classes = 1             # <-------------------------------------
        ckpt = torch.load(
            str(model),
            map_location=torch.device('cpu')
        )

        self.model = exp.get_model()
        self.model.eval()
        self.model.load_state_dict(ckpt["model"])   ###########
        self.model = fuse_model(self.model)
        self.model.to(device)
        self.model.eval()
```
when running

```
    self.model.load_state_dict(ckpt["model"])  
```
with exp.num_classes = 2, exception has occurred.

Exception has occurred: RuntimeError
Error(s) in loading state_dict for YOLOX:
	size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
  File "/home/chenke/yolo_tracking/examples/detectors/yolox.py", line 85, in __init__
    self.model.load_state_dict(ckpt["model"])
  File "/home/chenke/yolo_tracking/examples/track.py", line 92, in run
    model = m(
  File "/home/chenke/yolo_tracking/examples/track.py", line 198, in <module>
    run(opt)
RuntimeError: Error(s) in loading state_dict for YOLOX:
	size mismatch for head.cls_preds.0.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.0.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for head.cls_preds.1.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.1.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).
	size mismatch for head.cls_preds.2.weight: copying a param with shape torch.Size([1, 64, 1, 1]) from checkpoint, the shape in current model is torch.Size([2, 64, 1, 1]).
	size mismatch for head.cls_preds.2.bias: copying a param with shape torch.Size([1]) from checkpoint, the shape in current model is torch.Size([2]).

Please give your suggestions.
Thank you very much.

**Comment by mikel-brostrom** [comment]
YOLOX loads YoloX crowdhuman models by default. You will need to make some adjusments to [yolo_tracking](https://github.com/mikel-brostrom/yolo_tracking/tree/master)/[examples](https://github.com/mikel-brostrom/yolo_tracking/tree/master/examples)/[detectors](https://github.com/mikel-brostrom/yolo_tracking/tree/master/examples/detectors)/yolox.py to get it working on your custom weights

**Comment by chenke225** [comment]
thank you a lot.
