### ISSUE TITLE
frame=results[0].plot()

### ISSUE THREAD

**Issue by wolfgang1021** [mikel-brostrom/yolo_tracking#1148]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Dear Mr. Mikel Brostrom,
first of all thank you very much for your code, they are great.
I would like to ask if your code has a function similar to "results[0].plot()" in Yolov8.
For example:

        Tracking_frame = results[0].plot()
        cv2.imshow("YOLO_Tracking", Tracking_frame)
        if cv2.waitKey(1) & 0xFF == ord("q"):
            break
    else:
        break

thanks for your answer.

**Comment by wolfgang1021** [comment]
and one more question, 
AttributeError: 'Yolov8Strategy' object has no attribute 'stride'
:D

**Comment by mikel-brostrom** [comment]
`I would like to ask if your code has a function similar to "results[0].plot()" in Yolov8.`

There is not a built in plot function in boxmot. I recommend you to use:

https://github.com/mikel-brostrom/yolo_tracking#custom-object-detection-model-example

**Comment by wolfgang1021** [comment]
Thank you for your prompt answer. Can I import "botsort" in the same way as "deepsort" in the example?

**Comment by mikel-brostrom** [comment]
Yup! Everything is tested and passing so your safe to go :smile:

**Comment by wolfgang1021** [comment]
Hi Mr. Mikel Brostrom,
Based on your suggestion, I wrote a code.
import cv2
import numpy as np
from pathlib import Path
import torch
from boxmot import BoTSORT

from ultralytics import YOLO

tracker = BoTSORT( model_weights=Path('weights/osnet_ibn_x1_0.pt'), device=0, fp16=False)
weight=('weights/yolov5su.pt')
model=YOLO(weight)

vid = cv2.VideoCapture(0)
.#
.#

while True:
    ret, im = vid.read()
    results = model(source=im, save=False, device=0)

   # # substitute by your object detector, input to tracker has to be N X (x, y, x, y, conf, cls)
    dets = np.array(results[0].boxes.data.cpu().numpy())


    tracks = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls, ind)

    xyxys = tracks[:, 0:4].astype('int')
    ids = tracks[:, 4].astype('int')
    confs = np.round(tracks[:, 5], 2)
    clss = tracks[:, 6].astype('int')
    inds = tracks[:, 7].astype('int')
.#
.#
.

vid.release()
cv2.destroyAllWindows()
It works for a video. But this happens when I want to detect the computer camera:
1. works normally when there is a target in the camera;
2. when there is no target it gives an error as follows:
0: 480x640 (no detections), 100.0ms
Speed: 4.0ms preprocess, 100.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
Traceback (most recent call last):
  File "D:\work\Trackor0.1\YT_01.py", line 43, in <module>
    xyxys = tracks[:, 0:4].astype('int')
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

Could you help me?

**Comment by wolfgang1021** [comment]
Hi Mr. Mikel Brostrom,
Based on your suggestion, I wrote a code.

import cv2
import numpy as np
from pathlib import Path
import torch
from boxmot import BoTSORT
from ultralytics import YOLO

tracker = BoTSORT( model_weights=Path('weights/osnet_ibn_x1_0.pt'), device=0, fp16=False)
weight=('weights/yolov5su.pt')
model=YOLO(weight)
vid = cv2.VideoCapture(0)
...
while True:
ret, im = vid.read()
results = model(source=im, save=False, device=0)
dets = np.array(results[0].boxes.data.cpu().numpy())
tracks = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls, ind)
xyxys = tracks[:, 0:4].astype('int')
ids = tracks[:, 4].astype('int')
confs = np.round(tracks[:, 5], 2)
clss = tracks[:, 6].astype('int')
inds = tracks[:, 7].astype('int')
...
vid.release()
cv2.destroyAllWindows()

It works for a video. But this happens when I want to detect the computer camera:
1. works normally when there is a target in the camera;
2. when there is no target it gives an error as follows:
0: 480x640 (no detections), 100.0ms
Speed: 4.0ms preprocess, 100.0ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
Traceback (most recent call last):
File "D:\work\Trackor0.1\YT_01.py", line 43, in
xyxys = tracks[:, 0:4].astype('int')
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
Could you help me?

**Comment by mikel-brostrom** [comment]
You are missing `if tracks.shape[0] != 0:` from the [complete example](https://github.com/mikel-brostrom/yolo_tracking#custom-object-detection-model-example)

**Comment by wolfgang1021** [comment]
Hi Mr. Mikel Brostrom,
the following is my complete code. I did not miss "if tracks.shape[0] != 0:", but it cannot run when no target is detected:

import cv2
import numpy as np
from pathlib import Path
import torch
from boxmot import BoTSORT
from ultralytics import YOLO
from ultralytics.utils.plotting import colors

tracker = BoTSORT(
    model_weights=Path('weights/osnet_ibn_x1_0.pt'),
    device=0,
    fp16=False
)
weight=('weights/yolov5su.pt')
model=YOLO(weight)

vid = cv2.VideoCapture(0)
thickness = 2
fontscale = 0.5

while True:
    ret, im = vid.read()
    results = model(source=im,
                    conf=0.4,
                    iou=0.7,
                    save=False,
                    device=0,
                    classes=[0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 12]
                    )

    #box = results[0].boxes.xyxy.tolist()
    classes = results[0].boxes.cls.tolist()
    #conf = results[0].boxes.conf.tolist()
    names = results[0].names

    for cls in classes:
        name=names[int(cls)]
        color = colors(int(cls), True)
    dets = np.array(results[0].boxes.data.cpu().numpy())


    tracks = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls, ind)
#
    xyxys = tracks[:, 0:4].astype('int')
    ids = tracks[:, 4].astype('int')
    confs = np.round(tracks[:, 5], 2)
    clss = tracks[:, 6].astype('int')
    inds = tracks[:, 7].astype('int')


    if tracks.shape[0] != 0:
        for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
            im = cv2.rectangle(
                im,
                (xyxy[0], xyxy[1]),
                (xyxy[2], xyxy[3]),
                color,
                thickness
            )
            cv2.putText(
                im,
                f'c: {name}, {id}, conf: {conf} ',
                (xyxy[0], xyxy[1]-10),
                cv2.FONT_HERSHEY_SIMPLEX,
                fontscale,
                color,
                thickness
            )


    cv2.imshow('frame', im)



vid.release()
cv2.destroyAllWindows()

**Comment by wolfgang1021** [comment]
Hi Mr. Mikel Brostrom,
the following is my complete code. I did not miss "if tracks.shape[0] != 0:", but it cannot run when no target is detected:

`import cv2
import numpy as np
from pathlib import Path
import torch
from boxmot import BoTSORT

from ultralytics import YOLO
from ultralytics.utils.plotting import colors

tracker = BoTSORT(
    model_weights=Path('weights/osnet_ibn_x1_0.pt'),
    device=0,
    fp16=False
)
weight=('weights/yolov8s.pt')
model=YOLO(weight)

vid = cv2.VideoCapture(0)
thickness = 2
fontscale = 0.5

while True:
    ret, im = vid.read()
    results = model(source=im,
                    conf=0.4,
                    iou=0.7,
                    save=False,
                    device=0,
                    classes=[0, 1, 2, 3, 5, 6, 7, 9, 10, 11, 12]
                    )

    #box = results[0].boxes.xyxy.tolist()
    classes = results[0].boxes.cls.tolist()
    #conf = results[0].boxes.conf.tolist()
    names = results[0].names

    for cls in classes:
        name=names[int(cls)]
        color = colors(int(cls), True)
    dets = np.array(results[0].boxes.data.cpu().numpy())


    tracks = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls, ind)
#
    xyxys = tracks[:, 0:4].astype('int')
    ids = tracks[:, 4].astype('int')
    confs = np.round(tracks[:, 5], 2)
    clss = tracks[:, 6].astype('int')
    inds = tracks[:, 7].astype('int')


    if tracks.shape[0] != 0:
        for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):
            im = cv2.rectangle(
                im,
                (xyxy[0], xyxy[1]),
                (xyxy[2], xyxy[3]),
                color,
                thickness
            )
            cv2.putText(
                im,
                f'c: {name}, {id}, conf: {conf} ',
                (xyxy[0], xyxy[1]-10),
                cv2.FONT_HERSHEY_SIMPLEX,
                fontscale,
                color,
                thickness
            )


    cv2.imshow('frame', im)

vid.release()
cv2.destroyAllWindows()`

Error:
`0: 480x640 (no detections), 99.5ms
Speed: 4.0ms preprocess, 99.5ms inference, 1.0ms postprocess per image at shape (1, 3, 480, 640)
Traceback (most recent call last):
  File "D:\work\Trackor0.1\YT_01.py", line 45, in <module>
    xyxys = tracks[:, 0:4].astype('int')
IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed
`
