### ISSUE TITLE
How to use the local MOT17 data set for training, run the model and evaluate it

### ISSUE THREAD

**Issue by luke110** [mikel-brostrom/yolo_tracking#1153]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I downloaded the MOT17 data set locally, but I don’t know how to call the local MOT17 data set for training. I want to run out the checkpoints file myself and evaluate it.

**Comment by mikel-brostrom** [comment]
The easiest way is just to call `val.py`. It will download everything you need, unzip and place it in the correct folder. After that it will start running the evaluation :smile:

**Comment by luke110** [comment]
> 最简单的方法就是打电话`val.py`。它将下载您需要的所有内容，解压缩并将其放置在正确的文件夹中。之后它将开始运行评估😄

He just calls the existing checkpoints for evaluation, not the checkpoints I trained myself. I want to know how to train to get my own checkpoints.

**Comment by luke110** [comment]
> 最简单的方法就是打电话`val.py`。它将下载您需要的所有内容，解压缩并将其放置在正确的文件夹中。之后它将开始运行评估😄Can you provide me with training files?
