### ISSUE TITLE
How to use the tracker without reid any odf the available ones?

### ISSUE THREAD

**Issue by adnankarim** [mikel-brostrom/yolo_tracking#1157]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

How to use the tracker without reid any odf the available ones?

How to use available trackers without model.

**Comment by mikel-brostrom** [comment]
At the moment only OCSORT and ByteTrack does not use ReID models
