### ISSUE TITLE
Why Mean [3] is used for all positional dimensions?

### ISSUE THREAD

**Issue by fenguan** [mikel-brostrom/yolo_tracking#1160]
https://github.com/mikel-brostrom/yolo_tracking/blob/e672838829f9e7bfe1c5b0ffa870d0225124fed5/boxmot/motion/kalman_filters/adapters/bytetrack_kf_adapter.py#L50
Why Mean [3] is used for all positional dimensions?

**Comment by fenguan** [comment]
https://github.com/mikel-brostrom/yolo_tracking/blob/e672838829f9e7bfe1c5b0ffa870d0225124fed5/boxmot/motion/kalman_filters/adapters/bytetrack_kf_adapter.py#L83

**Comment by fenguan** [comment]
https://github.com/ifzhang/ByteTrack/issues/289

**Comment by mikel-brostrom** [comment]
Thanks for linking the answer here @fenguan  :smile:
