### ISSUE TITLE
Add yolov7 pretrained model

### ISSUE THREAD

**Issue by anhalu** [mikel-brostrom/yolo_tracking#1161]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Can you add the pipeline to use yolov7 model ? Thank a lot.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by anhalu** [comment]
@mikel-brostrom

**Comment by mikel-brostrom** [comment]
I would love to, but Yolov7 has no pip package so there is no easy way of doing this. I am not using submodules anymore because they are hell to work with :smile:

**Comment by mikel-brostrom** [comment]
I would also like to make Yolov6 available as well, but again, no pip package...

**Comment by mikel-brostrom** [comment]
This is a great idea! Please create new issue and set it as enhancement :smile:
