### ISSUE TITLE
yolov5_deepsort

### ISSUE THREAD

**Issue by firsttimeman** [mikel-brostrom/yolo_tracking#1163]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

i have looked before it was deepsort + yolov5 and now do you not offer yolov5+deepsort?? sorry for bad english

**Comment by mikel-brostrom** [comment]
You just need to go back to that specific release: https://github.com/mikel-brostrom/yolo_tracking/tree/bd27fadf1c34b08d5f04c6e3894e4af5ea360d7f
