### ISSUE TITLE
How Can I use yolov8 custom trained

### ISSUE THREAD

**Issue by TuanBao0711** [mikel-brostrom/yolo_tracking#1168]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I want to use my custom train yolov8 model to tracking some object . How can I use this in scripts?

**Comment by TuanBao0711** [comment]
I have a custom trained model yolov8 to detect a UAV, name "UAV_v8.pt". How can I use this to tracking UAV in video? Thank you so much ^^

**Comment by TuanBao0711** [comment]
I use: python examples/track.py --tracking-method deepocsort --yolo-model UAV_v8 --show --source video/IR.mp4 
=>2023-11-01 16:09:35.931 | ERROR    | examples.detectors:get_yolo_inferer:34 - Failed to infer inference mode from yolo model name
2023-11-01 16:09:35.931 | ERROR    | examples.detectors:get_yolo_inferer:35 - Your model name has to contain either yolox, yolo_nas or yolov8

**Comment by mikel-brostrom** [comment]
Rename the model, from: "UAV_v8.pt" to "yolov8_UAV.pt". Then you can run:

```bash
python examples/track.py --tracking-method deepocsort --yolo-model yolov8_UAV.pt --show --source video/IR.mp4
```

**Comment by TuanBao0711** [comment]
Thanks you so much, it work
