### ISSUE TITLE
Custom object detection model example

### ISSUE THREAD

**Issue by TuanBao0711** [mikel-brostrom/yolo_tracking#1169]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am trying custom object detection model example with on base of you file but not work

tracker = DeepOCSORT(
    model_weights=Path('osnet_x0_25_msmt17.pt'), # which ReID model to use
    device='cuda:0',
    fp16=True,
)

vid = cv2.VideoCapture(0)
color = (0, 0, 255)  # BGR
thickness = 2
fontscale = 0.5

Model = YOLO('yolov8n.pt')

while True:
    ret, im = vid.read()

    results = Model(im)
    
    for result in results:
        for r in result.boxes.data.tolist():
   
            dets = np.array(results)
            

            tracks = tracker.update(dets, im) # --> (x, y, x, y, id, conf, cls, ind)

            xyxys = tracks[:, 0:4].astype('int') # float64 to int
            ids = tracks[:, 4].astype('int') # float64 to int
            confs = tracks[:, 5]
            clss = tracks[:, 6].astype('int') # float64 to int
            inds = tracks[:, 7].astype('int') # float64 to int
            
  => Traceback (most recent call last):
  File "C:\Users\TuanBao\yolo_tracking\main.py", line 35, in <module>
    dets = np.array(results)
ValueError: setting an array element with a sequence. The requested array would exceed the maximum number of dimension of 32.
How Can I fix that, thanks

**Comment by TuanBao0711** [comment]
I tried many ways such as delete "dets = np.array(results)" or modify some codes, but not work :((

**Comment by chenke225** [comment]
```                
                results = Model(im)
                for result in results:
                    boxes = result.boxes.xyxy
                    confs = result.boxes.conf
                    cls = result.boxes.cls
                    # convert PyTorch to NumPy
                    boxes_np = boxes.cpu().numpy()
                    confs_np = confs.cpu().numpy()
                    cls_np = cls.cpu().numpy()
                    detection_results = np.column_stack((boxes_np, confs_np, cls_np))
                tracks = tracker.update(detection_results, im0) # --> (x, y, x, y, id, conf, cls, ind)
```

**Comment by chenke225** [comment]
Correct:  im0 -> im
tracks = tracker.update(detection_results, im) # --> (x, y, x, y, id, conf, cls, ind)

**Comment by chenke225** [comment]
results = Model(im)
                for result in results:
                    boxes = result.boxes.xyxy
                    confs = result.boxes.conf
                    cls = result.boxes.cls
                    # convert PyTorch to NumPy
                    boxes_np = boxes.cpu().numpy()
                    confs_np = confs.cpu().numpy()
                    cls_np = cls.cpu().numpy()
                    detection_results = np.column_stack((boxes_np, confs_np, cls_np))
                tracks = tracker.update(detection_results, im) # --> (x, y, x, y, id, conf, cls, ind)

**Comment by mikel-brostrom** [comment]
If you are using a Yolov8 custom model you can use the `track.py` under examples

**Comment by TuanBao0711** [comment]
> ```
>             results = Model(im)
>             for result in results:
>                 boxes = result.boxes.xyxy
>                 confs = result.boxes.conf
>                 cls = result.boxes.cls
>                 # convert PyTorch to NumPy
>                 boxes_np = boxes.cpu().numpy()
>                 confs_np = confs.cpu().numpy()
>                 cls_np = cls.cpu().numpy()
>                 detection_results = np.column_stack((boxes_np, confs_np, cls_np))
>             tracks = tracker.update(detection_results, im) # --> (x, y, x, y, id, conf, cls, ind)
> ```

thanks you, it work ^^

**Comment by TuanBao0711** [comment]
> If you are using a Yolov8 custom model you can use `track.py` under the `examples` folder

Sure, I could run the track.py file, however I would like to see your code and customize the code to use algorithms like bytrack, strongsort, or ocsort in my project. Is that allowed? :((
