### ISSUE TITLE
where can i find clip_market1501.pt？

### ISSUE THREAD

**Issue by wumiaowang66** [mikel-brostrom/yolo_tracking#1171]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

hello，in pytorch reid model zoo，i cant find clip_market1501.pt.

**Comment by mikel-brostrom** [comment]
Clip is not part of PytorchReID. The original clip models come from: https://github.com/Syliz517/CLIP-ReID
