### ISSUE TITLE
Can the tracking systems that require a ReID model be operated without using ReID?

### ISSUE THREAD

**Issue by LXXIANG12** [mikel-brostrom/yolo_tracking#1172]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Can the tracking systems that require a ReID model be operated without using ReID?for  example:Hybrid-SORT

**Comment by mikel-brostrom** [comment]
`ByteTrack` and `OCSORT` do not have ReID model. For the rest of the tracking methods the appearance description usage is not togglable.
