### ISSUE TITLE
Multi-Camera-Multi-Object-Tracking Setting

### ISSUE THREAD

**Issue by Nas-Azzam** [mikel-brostrom/yolo_tracking#1173]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Hello  Mr.Mike,
First Thanks for this great project, we would appreciate it and if possible kindly mention title (MCMOT) functionality would be great for the future development of this project. I searched for it, general trends are to use thread pooling and other post-processing techniques like these.

My suggestion would be to integrate the reidentification model in the inter-camera setting for reidentification of the same instance in different views.

Thanks.

### Use case

Multi-Camera-Re-identification

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
For this to work properly all the cameras in the setup have to be calibrated. With the relative camera poses one can establish a common coordinate system for all cameras. This will never be plug and play as there are several steps required before you can start tracking with a multi-camera setup at all.
