### ISSUE TITLE
Why CPU Usage Issue so HIGH?

### ISSUE THREAD

**Issue by Xxxnh** [mikel-brostrom/yolo_tracking#1174]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

When using trackers other than ocsort, which require loading a ReID pretrained model, the CPU usage is excessively high during inference. The CPU usage reaches up to 3000. What could be the reason for this?

**Comment by Justin900429** [comment]
Hi @Xxxnh,

Other trackers might utilize ReID model and if no cuda is found, cpu will be used for running the model.
Maybe checking which tracker you use and whether it have ReID-model can find the problem.
