### ISSUE TITLE
Can yolo_tracking support open-images-v7 model?

### ISSUE THREAD

**Issue by golfr32** [mikel-brostrom/yolo_tracking#1178]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Does the yolo_tracking support open-images-v7 model?

**Comment by mikel-brostrom** [comment]
We are dependent on the detection methods found under `examples/detectors`. If any of those provide a open-image-v7 trained model, we can ensure you I would work here.
