### ISSUE TITLE
Model Re-ID

### ISSUE THREAD

**Issue by TuanBao0711** [mikel-brostrom/yolo_tracking#1179]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Can I ask a little about models like osnet_x1_0_msmt17.pt ,.... ? What is it specifically, how is it structured and why some models must use it when initializing and some models do not in the custom object detection model.
tracker = boxmot.StrongSORT(
                model_weights=Path('osnet_x0_25_msmt17.pt'), # which ReID model to use
                device='cuda:0',
                fp16=True,
            )
but with ByterTrack
tracker = boxmot.BYTETracker()
Thanks you

**Comment by mikel-brostrom** [comment]
Some tracking methods are based on motion only. Like `ByteTrack`. Others on motion + appearance. Like `StrongSORT`.

**Comment by TuanBao0711** [comment]
Can you explain a little more detail, thanks? :(((
