### ISSUE TITLE
How can I get the extracted features from BoTSORT to create a global ID map

### ISSUE THREAD

**Issue by monuyadav016** [mikel-brostrom/yolo_tracking#1184]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am using BoTSORT to track objects within my recorded footage of camera. Now I would like people to retain their ID if possible when moving different camera's view. I know the graph layout of the cameras. I know their placement and angle is not perfect. I just want to see if it works for even 1 in a 100.

I tried searching through issues and the web for anything related. I learnt something that had to do with feature extraction and matching to create a global ID for all cameras. I know the BoTSORT class tracker does a lot of this under the hood however it does not work for multi cameras. How can I get the extracted feature from the BoTSORT class instance so that I can create my own solution on top of it.

**Comment by mikel-brostrom** [comment]
Global IDs across multiple cameras is not supported atm

**Comment by monuyadav016** [comment]
> Global IDs across multiple cameras is not supported atm

How can I get the extracted appearance feature from the BoTSORT class instance so that I can create my own solution on top of it?

**Comment by mikel-brostrom** [comment]
Sorry for my late response  @monuyadav016 

```py
for t in botsort.tracked_stracks:
    t.smooth_feat
```
