### ISSUE TITLE
how to use my own training data set

### ISSUE THREAD

**Issue by GangYuan666** [mikel-brostrom/yolo_tracking#1186]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

did you slove this problem on this link https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking/issues   ？i have the same problem as you,help me ,please

**Comment by GangYuan666** [comment]
this is  problem "ModuleNotFoundError: No module named 'ultralytics.nn.modules.conv'; 'ultralytics.nn.modules' is not a package"

**Comment by mikel-brostrom** [comment]
> ### Search before asking
> 
>     * [x]  I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.
> 
> 
> ### Question
> 
> did you slove this problem on this link https://github.com/MuhammadMoinFaisal/YOLOv8-DeepSORT-Object-Tracking/issues ？i have the same problem as you,help me ,please

This question has nothing to do with this repo
