### ISSUE TITLE
Deprecated instructions in REID multi framework model export wiki

### ISSUE THREAD

**Issue by furkan-novit** [mikel-brostrom/yolo_tracking#1193]
Wiki: https://github.com/mikel-brostrom/yolo_tracking/wiki/ReID-multi-framework-model-export

Instruction: `python3 boxmot/deep/reid_export.py`

Correction: `python3 boxmot/appearance/reid_export.py`

**Comment by mikel-brostrom** [comment]
Thanks! Corrected now :smile:
