### ISSUE TITLE
Trained YOLOv8 detector weights on custom dataset

### ISSUE THREAD

**Issue by 22GC22** [mikel-brostrom/yolo_tracking#1195]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

 I have custom weights in best.pt for the yolov8 detector. How can I use it it doesn't let me use it directly like --yolo-model best.pt

**Comment by rbccv** [comment]
Due to the naming convention, I believe you have to change the name of your best.pt file to have yolov8 in it.
Ex.: rename it to yolov8_weights.pt 

![Screenshot_5](https://github.com/mikel-brostrom/yolo_tracking/assets/43848556/73d33d97-0726-414c-8787-d2abea2d81ea)

**Comment by mikel-brostrom** [comment]
> Due to the naming convention, I believe you have to change the name of your best.pt file to have yolov8 in it. Ex.: rename it to yolov8_weights.pt
> 
> ![Screenshot_5](https://user-images.githubusercontent.com/43848556/284881156-73d33d97-0726-414c-8787-d2abea2d81ea.png)

This is right. Thank you for helping me out here @rbccv :smile:
