### ISSUE TITLE
Tracking loosing object with detection

### ISSUE THREAD

**Issue by MonteiroAlvesMatheus** [mikel-brostrom/yolo_tracking#1196]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello Mike! First of all, thank you very much for providing your code; it has been extremely helpful during my research.

I'm facing the following situation while testing all available trackers: they are experiencing an issue. The problem scenario is as follows: I send information about object detection frame by frame. When the confidence is above 50%, the tracker initiates tracking by assigning an ID to the object. After a certain period, with the object moving ahead in frames, for example, 20 frames later, the tracker stops tracking the object, even though it continues to receive detection information with a confidence level above 90% for the same object.

What could be causing this problem? I've tried a few approaches to improve it, such as increasing the frame_buffer and modifying parameters in trackers that have second association in cases of occlusion, attempting to make the tracker understand that the object is not 100% occluded.

Attached is an image of the issue.

Previous frame
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/106630689/a1564efe-e6d5-427d-948c-a7c68dd194c7)

Subsequent frame
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/106630689/62bbe50e-1f1b-4116-bfa1-e8e16929eba0)

**Comment by mikel-brostrom** [comment]
Try to relax the arguments associated with the association process. For `BoTSORT` this would be: `proximity_thresh`, `match_thresh`, `appearance_thresh`. My guess is that the motion uncertainty is very high. The objects move large distances (in pixels) from frame to frame which causes issues when tracking...

**Comment by MonteiroAlvesMatheus** [comment]
Thank you very much for the feedback, Mike! I'm using the Bytetrack tracker because when I use BoTSORT, both CPU and GPU usage are very high. Bytetrack, on the other hand, keeps CPU usage low and GPU high. I made changes to the match_thresh arguments, and it showed some improvement. However, the issue persists in some cases. Using OCSORT, for example, the result with the changes to the arguments was better, but the problem still exists in some cases. This makes sense, as the object moves by several pixels, as you mentioned.

Another question is, I've noticed that the tracking bounding box is slightly offset from the detection bounding box. However, what the tracker receives are the coordinates xmin, ymin, xmax, ymax, meaning the points of the top-left and bottom-right corners of the bounding box. There is a conversion of values in the code for Bytetrack and BoTSORT that modifies these values, causing such displacement, but OCSORT doesn't exhibit this displacement. Is there a way for me to work around this?

**Comment by mikel-brostrom** [comment]
> There is a conversion of values in the code for Bytetrack and BoTSORT that modifies these values, causing such displacement, but OCSORT doesn't exhibit this displacement

The output of the tracker comes from its corresponding Kalman filter which predicts a bounding box. Hence, it is not equal to the input bbox
