### ISSUE TITLE
need for model weights help

### ISSUE THREAD

**Issue by wumiaowang66** [mikel-brostrom/yolo_tracking#1200]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello，Thank you for your outstanding work. May I ask if you can send me YOLOX_ n.pt  weight file.  If possible, thank you very much。

**Comment by mikel-brostrom** [comment]
You will need a VPN as a Chinese user

https://github.com/mikel-brostrom/yolo_tracking/blob/f964fe48338a524a8a2b7a06fad5354474e041ba/examples/detectors/yolox.py#L15-L21
