### ISSUE TITLE
A bug for predict() function in class StrongSortKalmanFilterAdapter

### ISSUE THREAD

**Issue by lyxyuren** [mikel-brostrom/yolo_tracking#1204]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

I noticed a BUG, which is in the file:  yolo_tracking\boxmot\motion\kalman_filters\adapters\ocsort_kf_adapter.py. The function predict(self, mean, covariance) in class StrongSortKalmanFilterAdapter is wrong. The correct form should be like:
`def predict(self, mean, covariance):
        """Run Kalman filter prediction step.

        Parameters
        ----------
        mean : ndarray
            The 8 dimensional mean vector of the object state at the previous
            time step.
        covariance : ndarray
            The 8x8 dimensional covariance matrix of the object state at the
            previous time step.

        Returns
        -------
        (ndarray, ndarray)
            Returns the mean vector and covariance matrix of the predicted
            state. Unobserved velocities are initialized to 0 mean.

        """
        std_pos = [
            self._std_weight_position * mean[3],
            self._std_weight_position * mean[3],
            1e-2,
            self._std_weight_position * mean[3],
        ]
        std_vel = [
            self._std_weight_velocity * mean[3],
            self._std_weight_velocity * mean[3],
            1e-5,
            self._std_weight_velocity * mean[3],
        ]
        motion_cov = np.diag(np.square(np.r_[std_pos, std_vel]))

        super().predict(Q=motion_cov)

        return self.x, self.P`
The calculation of std_pos and std_vel (it failed to use mean[3] for each component!) are not correct in the oringinal version.

### Environment

Python 3.10, cuda11.4 windows

### Minimal Reproducible Example

def predict(self, mean, covariance):
        """Run Kalman filter prediction step.

        Parameters
        ----------
        mean : ndarray
            The 8 dimensional mean vector of the object state at the previous
            time step.
        covariance : ndarray
            The 8x8 dimensional covariance matrix of the object state at the
            previous time step.

        Returns
        -------
        (ndarray, ndarray)
            Returns the mean vector and covariance matrix of the predicted
            state. Unobserved velocities are initialized to 0 mean.

        """
        std_pos = [
            self._std_weight_position * mean[3],
            self._std_weight_position * mean[3],
            1e-2,
            self._std_weight_position * mean[3],
        ]
        std_vel = [
            self._std_weight_velocity * mean[3],
            self._std_weight_velocity * mean[3],
            1e-5,
            self._std_weight_velocity * mean[3],
        ]
        motion_cov = np.diag(np.square(np.r_[std_pos, std_vel]))

        super().predict(Q=motion_cov)

        return self.x, self.P

**Comment by mikel-brostrom** [comment]
I need to check all the KF implementations...

**Comment by mikel-brostrom** [comment]
Will be done bore the end of the year :rocket:

**Comment by mikel-brostrom** [comment]
This should now be fixed. I switched back the original Kalman Filters
