### ISSUE TITLE
DEBUG level logs gets disabled after importing boxmot

### ISSUE THREAD

**Issue by Pannu22** [mikel-brostrom/yolo_tracking#1211]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Other

### Bug

I'm experimenting with Boxmot & found this issue where after importing Boxmot, I'm not getting DEBUG-level logs!
Thanks in advance & I would love to contribute.

### Environment

loguru==0.7.2 ; python_full_version == "3.10.13"
boxmot==10.0.46 ; python_full_version == "3.10.13"

### Minimal Reproducible Example

```python
from loguru import logger
logger.debug("Test log")

from boxmot import DeepOCSORT
logger.debug("Imported boxmot")
```

**Comment by mikel-brostrom** [comment]
You can set the level here:

https://github.com/mikel-brostrom/yolo_tracking/blob/7f414e0d2692b4ed4383d9ab16eb85bfc17fd59c/boxmot/utils/__init__.py#L19

:smile:
