### ISSUE TITLE
'StrongSORT' object has no attribute 'reset'

### ISSUE THREAD

**Issue by ddracoo** [mikel-brostrom/yolo_tracking#1212]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi!

I'm wondering what the error is and how I can fix it: 

`Traceback (most recent call last):
  File "/cluster/home/user/boxmot/yolo_tracking/examples/track.py", line 199, in <module>
    run(opt)
  File "/cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/user/boxmot/yolo_tracking/examples/track.py", line 103, in run
    for frame_idx, r in enumerate(results):
  File "/cluster/apps/nss/gcc-8.2.0/python/3.11.2/x86_64/lib64/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
    response = gen.send(None)
               ^^^^^^^^^^^^^^
  File "/cluster/home/user/.local/lib64/python3.11/site-packages/ultralytics/engine/predictor.py", line 269, in stream_inference
    self.run_callbacks('on_predict_postprocess_end')
  File "/cluster/home/user/.local/lib64/python3.11/site-packages/ultralytics/engine/predictor.py", line 362, in run_callbacks
    callback(self)
  File "/cluster/home/user/.local/lib64/python3.11/site-packages/ultralytics/trackers/track.py", line 48, in on_predict_postprocess_end
    predictor.trackers[i].reset()
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'StrongSORT' object has no attribute 'reset'`

I am trying to run a tracking with this command:
`examples/track.py --yolo-model examples/detectors/yolov8.py --tracking-method strongsort --source $SOURCE_DIR --reid-model lmbn_n_cuhk03_d.pt --imgsz 860 --device 0 --save --name test --save-txt --save-mot`

**Comment by chenke225** [comment]
This is due to the incompatibility between the latest version of Ultralytics tracker and the BoxMot tracker.

Solution:
(1) Modify: def on_predict_postprocess_end(predictor, persist=False): 

```
def on_predict_postprocess_end(predictor, persist=False):
    """Postprocess detected boxes and update with object tracking."""
    bs = predictor.dataset.bs
    path, im0s = predictor.batch[:2]

    for i in range(bs):
#        if not persist and predictor.vid_path[i] != str(predictor.save_dir / Path(path[i]).name):  # new video
#            predictor.trackers[i].reset()                        
        det = predictor.results[i].boxes.data.cpu().numpy()  
        if len(det) == 0:
            continue
        tracks = predictor.trackers[i].update(det, im0s[i])  
        if len(tracks) == 0:
            continue
        idx = tracks[:, -1].astype(int)
        predictor.results[i] = predictor.results[i][idx]
        predictor.results[i].update(boxes=torch.as_tensor(tracks[:, :-1]))
```
(2) Use the Ultralytics version provided by mikel-brostrom at the following link:
https://github.com/mikel-brostrom/ultralytics

**Comment by chenke225** [comment]
This is due to the incompatibility between the latest version of Ultralytics tracker and the BOXMOT tracker.

Solution:  （1）or （2）
(1) Modify ultralytics/trackers/track.py: def on_predict_postprocess_end(predictor, persist=False):
```
def on_predict_postprocess_end(predictor, persist=False):
    """Postprocess detected boxes and update with object tracking."""
    bs = predictor.dataset.bs
    path, im0s = predictor.batch[:2]

    for i in range(bs):
#        if not persist and predictor.vid_path[i] != str(predictor.save_dir / Path(path[i]).name):  # new video
#            predictor.trackers[i].reset()                        
        det = predictor.results[i].boxes.data.cpu().numpy()   # add .data attribute
        if len(det) == 0:
            continue
        tracks = predictor.trackers[i].update(det, im0s[i])  
        if len(tracks) == 0:
            continue
        idx = tracks[:, -1].astype(int)
        predictor.results[i] = predictor.results[i][idx]
        predictor.results[i].update(boxes=torch.as_tensor(tracks[:, :-1]))
```
or
(2) Use the Ultralytics version provided by mikel-brostrom at the following link:
https://github.com/mikel-brostrom/ultralytics
