### ISSUE TITLE
Questions about the ReID model in BoTSORT

### ISSUE THREAD

**Issue by Kevin111369** [mikel-brostrom/yolo_tracking#1213]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

There are two trackers in BoTSORT, BoT-SORT and BoT-SORT-ReID. How to use the tracker without ReID module?

**Comment by Kevin111369** [comment]
> In this repo we only offer the ReID version. You could compare the original repo to this one and make the necessary changes to deactivate ReiD

Thank you for your timely reply. By comparing the official BoTSORT code with your code, I successfully implemented BoTSORT without the ReID model.

**Comment by wolfgang1021** [comment]
Hi Kevin,
could you share how to block the ReID module? I'm trying to set `_**model_weights=None**_` in the parameter, then：
```
       if model_weights is not None:
            self.model = ReIDDetectMultiBackend(
            weights=model_weights, device=device, fp16=fp16
        )
```
```
        if model_weights is not None:
            features_high = self.model.get_features(dets_first[:, 0:4], img)
```
```
      if len(dets) > 0:
            """Detections"""
            if model_weights is not None:
                detections = [STrack(det, f) for (det, f) in zip(dets_first, features_high)]
            else:
                detections = [STrack(det) for (det) in zip(dets_first)]
        else:
            detections = []
```
```
 # Associate with high score detection boxes
        ious_dists = iou_distance(strack_pool, detections)
        ious_dists_mask = ious_dists > self.proximity_thresh
        if model_weights is not None:
            emb_dists = embedding_distance(strack_pool, detections) / 2.0
            emb_dists[emb_dists > self.appearance_thresh] = 1.0
            emb_dists[ious_dists_mask] = 1.0
            dists = np.minimum(ious_dists, emb_dists)
        else:
            dists = ious_dists
```
But it doesn't work, there will be an error：  name 'weight_model' is not defined

**Comment by Kevin111369** [comment]
> Hi Kevin, could you share how to block the ReID module? I'm trying to set `_**model_weights=None**_` in the parameter, then：
> 
> ```
>        if model_weights is not None:
>             self.model = ReIDDetectMultiBackend(
>             weights=model_weights, device=device, fp16=fp16
>         )
> ```
> 
> ```
>         if model_weights is not None:
>             features_high = self.model.get_features(dets_first[:, 0:4], img)
> ```
> 
> ```
>       if len(dets) > 0:
>             """Detections"""
>             if model_weights is not None:
>                 detections = [STrack(det, f) for (det, f) in zip(dets_first, features_high)]
>             else:
>                 detections = [STrack(det) for (det) in zip(dets_first)]
>         else:
>             detections = []
> ```
> 
> ```
>  # Associate with high score detection boxes
>         ious_dists = iou_distance(strack_pool, detections)
>         ious_dists_mask = ious_dists > self.proximity_thresh
>         if model_weights is not None:
>             emb_dists = embedding_distance(strack_pool, detections) / 2.0
>             emb_dists[emb_dists > self.appearance_thresh] = 1.0
>             emb_dists[ious_dists_mask] = 1.0
>             dists = np.minimum(ious_dists, emb_dists)
>         else:
>             dists = ious_dists
> ```
> 
> But it doesn't work, there will be an error： name 'weight_model' is not defined

I modified bot_sort.py and added the with_reid option. When with_reid=Ture, the model needs to be loaded and features extracted. When with_reid=False, these operations are not performed. It is recommended that you refer to [the official program](https://github.com/NirAharon/BoT-SORT). Their code has the with_reid option.

**Comment by wolfgang1021** [comment]
Thanks for the quick reply and the ideas you provided! If possible, could you share what the code looks like after your modifications? I'm a newbie, so I still haven't modified it successfully.

**Comment by mikel-brostrom** [comment]
Are you willing to submit a PR @Kevin111369? I would be more than happy to have a look at it?

**Comment by wolfgang1021** [comment]
Thank you for sharing!
