### ISSUE TITLE
Is There BoxMOT package in C++ version？

### ISSUE THREAD

**Issue by Xxxnh** [mikel-brostrom/yolo_tracking#1217]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Is there a c++ version of the boxmot package that can be called directly?

**Comment by mikel-brostrom** [comment]
This repo focuses on python tracker implementations only. There are however C++ options out there: https://github.com/viplix3/BoTSORT-cpp/tree/main :smile:
