### ISSUE TITLE
Can't create val_utils/scripts/run_mot_challenge.py

### ISSUE THREAD

**Issue by lzvvva** [mikel-brostrom/yolo_tracking#1222]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I run val.py to download the val_utils. The code are  "python examples/val.py --yolo-model yolov8n.pt --tracking-method deepocsort --reid-model osnet_x1_0_msmt17.pt".   
But the following error occurs:  can't open file '/home/ZK/yolo_tracking/examples/val_utils/scripts/run_mot_challenge.py': [Errno 2] No such file or directory.  
I found that the val_utils only contained data directory, and it seems that the srcipts can not be downloaded.

**Comment by mikel-brostrom** [comment]
Start from a clean slate. All the evaluation tools are downloaded when running `val.py`
