### ISSUE TITLE
ID Changes with box intersection and objects going out of frame

### ISSUE THREAD

**Issue by lukeborozan** [mikel-brostrom/yolo_tracking#1226]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I made a custom yolov8 model which tracks soccer players, and using the track.py I got a saved output which has the correct bounding boxes, but the problem is that the ID numbers keep switching whenever a bunch of players are in the same place to where the boxes intersect, or if the player goes out of the frame it changes their ID when they come back into it. Do you have any ideas on why this could be the case? Is it a matter of training a larger dataset? I appreciate the help.

**Comment by mikel-brostrom** [comment]
This is not a solved research are. If you are using a single camera and objects are entering and exiting the filed of view you will have reidentification issues.

**Comment by gigasurgeon** [comment]
I have solved this for basketball players. Earlier, the ids kept switching if the players went out of the frame and came back. I trained a clip model from here - https://github.com/DeepSportradar/player-reidentification-challenge
The clip model is later used to generate image embeddings and find similar players. 

Then for all the frames, I went ahead and cropped out every player, and then generated clip image embeddings. For basketball, there are total 10 players in the court, so I did kmeans clustering for 10 clusters on those embeddings. Surprisingly, it did very well. I was able to retain same id for the players across the entire match.

I used boxmot's bytetracker as a postsprocessing step. There would be times when players will fight for the basketball and were close to each other and appeared nearly the same. So, their ids would switch for those few milliseconds. I generated tracklets information from bytetracker and for every tracklet, I computed the most frequent id used (from clustering), and assign it to that player. It made reid even more robust. 

Tip: You can also create 2 clusters, to divide players in two teams .

**Comment by amit-real** [comment]
@aidenderinger5 You need to make use of both, the tracklets from the tracker and clustering. The tracklets are accurate for very short duration, and then the id is changed to another one.
You take a tracklet, get into its frames, crop the player and create embeddings from the tracklet. Now you go and identify to which cluster, are these player embeddings from a single tracklet are similar to, and then you give it that id.

Now when the id changes, you want to treat it as a different tracklet and repeat the process. In doing so, you will map each tracklet to the correct player ids.

So you are leveraging the short term accuracy of the tracker, and the long term accuracy of the clusters.
