### ISSUE TITLE
Inquiry on Replicating Experiments in Enhanced Tracking and ReID through Segmentation

### ISSUE THREAD

**Issue by carry-all-coder** [mikel-brostrom/yolo_tracking#1228]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello! I am currently engaged in research focused on enhancing tracking and reidentification (ReID) using segmentation techniques. In the course of my work, I came across two of your experiments that are highly relevant to my research interests:

1. **"Segmentation model vs. object detection model on MOT metrics"** available at [this GitHub link](https://github.com/mikel-brostrom/yolo_tracking/wiki/Segmentation-model-vs-object-detetion-model-on-MOT-metrics).
2. **"Masked detection crops vs. regular detection crops for ReID feature extraction"** accessible via [this GitHub link](https://github.com/mikel-brostrom/yolo_tracking/wiki/Masked-detection-crops-vs-regular-detection-crops-for-ReID-feature-extraction).

I found both experiments intriguing and potentially beneficial for my project. Could you please provide some guidance, steps or code on how to replicate these experiments? Any additional insights or details about the methodologies and tools used would be greatly appreciated.

Thank you for your time and assistance. I look forward to your valuable input!

**Comment by mikel-brostrom** [comment]
> Segmentation model vs. object detection model on MOT metrics

You will need to make custom modifications. Pass both bboxes and masks to the tracker and mask the crops generated with bboxes:

https://github.com/mikel-brostrom/yolo_tracking/blob/59588ac53e02a3ad0fee523566da4713cb080ea1/trackers/strong_sort/strong_sort.py#L147-L152

> Segmentation model vs. object detection model on MOT metrics

Segmentation models generate both segmentations and bboxes. Only pass the bboxes :smile:

**Comment by carry-all-coder** [comment]
Dear Mike,

I am deeply grateful for your quick and detailed response to my earlier question. It provided valuable insights!

Another question, could you briefly explain the specific implementation of "Masked detection crops vs. regular detection crops for ReID feature extraction," particularly focusing on how it differs in code and approach from the "Segmentation model vs. object detection model on MOT metrics"? I'm also curious about why segmentation enhances tracking in ReID(Masked detection crops vs. regular detection crops for ReID feature extraction) but not as much in the MOT metrics experiment(Segmentation model vs. object detection model on MOT metrics).

Thank you once again for your time and expertise!

**Comment by mikel-brostrom** [comment]
> could you briefly explain the specific implementation of "Masked detection crops vs. regular detection crops for ReID feature extraction,"

Everything you need to know regarding this is in this branch:

https://github.com/mikel-brostrom/yolo_tracking/blob/59588ac53e02a3ad0fee523566da4713cb080ea1/trackers/strong_sort/strong_sort.py#L147-L152

> how it differs in code and approach from the "Segmentation model vs. object detection model on MOT metrics"?

Segmentation models also generate bboxes. These bboxes can be passed instead of the object detection bboxes.

**Comment by carry-all-coder** [comment]
Got it! So the "Segmentation model vs. object detection model on MOT metrics" experiment refers to model performance between yolov5m and yolov5m-seg(use box output). And the "Masked detection crops vs. regular detection crops for ReID feature extraction" experiment refers to performance comparison between yolov5m-seg and yolov5m-seg with masked refined features, which is related to the code you mentioned.
Thank you for your enlightening response!

**Comment by mikel-brostrom** [comment]
Exactly. Good luck with your experiments :smile:
