### ISSUE TITLE
It seems that there are several issues after updating the ultralytics version. Could you please fix the version in the requirements file so that we can easily run the yolo_tracking?

### ISSUE THREAD

**Issue by yaoshanliang** [mikel-brostrom/yolo_tracking#1230]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evolution

### Bug

Such as:

`'StrongSORT' object has no attribute 'reset'`

### Environment

python 3.8

### Minimal Reproducible Example

```
python examples/evolve.py --yolo-model best.pt  --benchmark dataset_root --split test --tracking-method deepocsort --objective HOTA --n-trials 100
```

**Comment by mikel-brostrom** [comment]
I updated the custom Ultralytics version used by this repo to 8.0.224

**Comment by mikel-brostrom** [comment]
You cannot simply install the official latest Ultralytics repo. The custom one used enables inference using other object detectors
