### ISSUE TITLE
Support for SMILETrack?

### ISSUE THREAD

**Issue by sourabhyadav** [mikel-brostrom/yolo_tracking#1234]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Is the support for SMILETrack available? Or is it under development? 

If not, is there a way tutorial/guidelines to quickly implement new SOTA tracking methods in this amazing repo? 

P.S. - Thanks for creating the repo. The guidelines worked smoothly!

**Comment by mikel-brostrom** [comment]
> Is the support for SMILETrack available? Or is it under development?

Not available and not under development. Btw, https://github.com/corfyi/UCMCTrack seems to yield better performance 

> If not, is there a way tutorial/guidelines to quickly implement new SOTA tracking methods in this amazing repo?

Not really, just split all the components into their respective folders :smile:
