### ISSUE TITLE
Tracker predicts the same ID more than once in a single timestep 

### ISSUE THREAD

**Issue by yaoshanliang** [mikel-brostrom/yolo_tracking#1236]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Evaluation

### Bug

When using hybridsort as the tracking-method on my custom dataset, it always output the error message: Tracker predicts the same ID more than once in a single timestep. The other tracking-methods ('bytetrack', 'botsort', 'strongsort', 'ocsort', 'deepocsort') all work well.

### Environment

python3.8

### Minimal Reproducible Example

```
python examples/val.py --yolo-model best.pt --benchmark tracking --split test --device 0 --tracking-method hybridsort
```

**Comment by WJ-Huang** [comment]
Hey, did you solve the problem? @yaoshanliang
