### ISSUE TITLE
mot17_sbs_S50.pt

### ISSUE THREAD

**Issue by wolfgang1021** [mikel-brostrom/yolo_tracking#1239]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi mikel, 
I have a question about the ReID model.  Why I can't use mot17_sbs_S50.pt. 
It is the official ReID model of BoT-SORT.
Thanks and looking forward to your reply.

**Comment by mikel-brostrom** [comment]
This architecture is not supported for appearance description extraction. You can easily add it here: https://github.com/mikel-brostrom/yolo_tracking/tree/master/boxmot/appearance/backbones

**Comment by wolfgang1021** [comment]
Does it mean that boxmot does not support appearance description extraction? Sorry I'm new to CV, you mean I need to add mot17_sbs.py to the backbone , right? But I didn't find this code in the original BoT-SORT.
https://github.com/NirAharon/BoT-SORT/tree/main/fast_reid/fastreid/modeling/backbones

**Comment by mikel-brostrom** [comment]
> you mean I need to add mot17_sbs.py to the backbone , right?

Yes. You will need to figure out which backbone `mot17_sbs_S50.pt` is associated to

**Comment by wolfgang1021** [comment]
Thank you for your reply. Can you tell me if the mot50_sbs_S50.pt model is different from the others? Does using it improve the tracking IDF1?
Also, I found that by extracting the color of the BBox in the detector and using it in the tracker you can make the output of the tracker a different color BBox, just a small difference, but visually better. Hope this is useful for your boxmot.
#from ultralytics.utils.plotting import colors

**Comment by mikel-brostrom** [comment]
> Can you tell me if the mot50_sbs_S50.pt model is different from the others?

I am not familiar with the reid repo so cannot help you out here
