### ISSUE TITLE
Model complexity

### ISSUE THREAD

**Issue by wsw321** [mikel-brostrom/yolo_tracking#1240]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

May I ask how to calculate the complexity of the tracking algorithm? In addition to calculating the parameters of the detection model and feature extraction model, do we need to calculate anything else?

**Comment by mikel-brostrom** [comment]
This has no easy answers. But let's try to brake this down. The tracking algorithm consists of basically four parts: appearance description extraction, camera motion compensation, kalman filter updates and multi-step association. 

- The appearance description extraction part is tricky as the complexity of the models do not scale linearly with the input pixels. The complexity of a CNN is more nuanced and depends on several factors: stride, pooling, convolutional layers, their kernels... There is not easy way of calculating this without looking very deep into the specific architecture.

- The Big O notation for camera motion compensation can vary widely depending on the specific algorithm. Methods based on optical flow are slower than feature-based methods

- The Kalman Filter complexity i primarily dependent on the state and observation vector.

- The association part is solved by the Hungarian Algorithm. Each association subproblem (high confidence, low confidence for example) is solved using the Hungarian algorithm.
