### ISSUE TITLE
How to add support for other ReID models

### ISSUE THREAD

**Issue by koolgax99** [mikel-brostrom/yolo_tracking#1242]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi @mikel-brostrom and team, Firstly thanks you for this amazing repository.

I have been using this repo for my person re-identification problem, but the current pretrained models perform poorly on my data. I wanted to know if there is support available for the pretrained models of [Spatial Temporal Person Re-Identification ](https://github.com/Wanggcong/Spatial-Temporal-Re-identification)  and [Triplet Loss based Reidentification (TriNET)](https://github.com/VisualComputingInstitute/triplet-reid) models?

Incase the support is not available can you please guide on if I can tweak in some code and add these pertrained ReId models in?

I apologize if this issue becomes a duplicate for any of the previous issue.

**Comment by mikel-brostrom** [comment]
You need to add the backbones [here](https://github.com/mikel-brostrom/yolo_tracking/tree/master/boxmot/appearance/backbones). Then just add it to the [model factory](https://github.com/mikel-brostrom/yolo_tracking/blob/master/boxmot/appearance/backbones/__init__.py)

**Comment by ppsychoo** [comment]
Have slove this problem，I have the same question. I want to use the SirNet as the re-id model, but I do not know how to add the backbones and the model factory, can you give me a more detailed instruction note?

**Comment by mikel-brostrom** [comment]
Everything you need to know is here:

> You need to add the backbones [here](https://github.com/mikel-brostrom/yolo_tracking/tree/master/boxmot/appearance/backbones). Then just add it to the [model factory](https://github.com/mikel-brostrom/yolo_tracking/blob/master/boxmot/appearance/backbones/__init__.py). By adding the string associated to the backbone in the weights file name the weights are loaded into the right architecture.

You need to understand the code, I cannot do this for you.
