### ISSUE TITLE
Handle Small/Tiny and Fast/High Speed moving object detection/tracking with stable inference

### ISSUE THREAD

**Issue by tgbaoo** [mikel-brostrom/yolo_tracking#1246]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello @mikel-brostrom, I am involve a project that predict ball in hole classification, I am having a discussion on the ultralytics issue question below:
https://github.com/ultralytics/ultralytics/issues/7109?notification_referrer_id=NT_kwDOBSc1urM4ODQzMDc2ODU4Ojg2NDU1NzM4
this issue also contain my result clip demo, training result and relevant information

Then I found your repo with plugged difference SORT tracking algorithms, I wondered from your experience on tracking small/high speed object like golf ball,do you have any ideas or strategy on keep tracking them well? I am tend to re-trained the ReID model. 

If you have any better idea with my case, please help me, I am noob with computer vision so really need your consult.

Thanks you so much

**Comment by mikel-brostrom** [comment]
ReID won't solve your tracking issues. High speed objects have high motion uncertainty, specially if the FPS for your camera are very low. For those cases IoU is not be a viable association metric option as there most certainly won't be any overlap at all between the bboxes.

**Comment by colonelpanic8** [comment]
@tgbaoo I have built a bunch of code around a centroid based system and got it to work quite well. its really quite a different paradigm than iou and there are a few gotchas. lmk if you want some help.

**Comment by mikel-brostrom** [comment]
I would be more than happy to review your centroid-based association method @. Just creat a PR 😊

**Comment by mikel-brostrom** [comment]
I will drop my 5 cents here:

```py
def centroid_distance_batch_normalized(bboxes1, bboxes2, w, h):
    """
    Computes the normalized centroid distance between two sets of bounding boxes.
    Bounding boxes are in the format [x1, y1, x2, y2].
    `normalize_scale` is a tuple (width, height) to normalize the distance.
    """

    # Calculate centroids
    centroids1 = np.stack(((bboxes1[..., 0] + bboxes1[..., 2]) / 2, 
                           (bboxes1[..., 1] + bboxes1[..., 3]) / 2), axis=-1)
    centroids2 = np.stack(((bboxes2[..., 0] + bboxes2[..., 2]) / 2, 
                           (bboxes2[..., 1] + bboxes2[..., 3]) / 2), axis=-1)

    # Expand dimensions for broadcasting
    centroids1 = np.expand_dims(centroids1, 1)
    centroids2 = np.expand_dims(centroids2, 0)

    # Calculate Euclidean distances
    distances = np.sqrt(np.sum((centroids1 - centroids2) ** 2, axis=-1))

    # Normalize distances
    norm_factor = np.sqrt(w**2 + h**2)
    normalized_distances = distances / norm_factor

    return normalized_distances
```

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/pull/1247:

```py
def centroid_batch(bboxes1, bboxes2, w, h):
    """
    Computes the normalized centroid distance between two sets of bounding boxes.
    Bounding boxes are in the format [x1, y1, x2, y2].
    `normalize_scale` is a tuple (width, height) to normalize the distance.
    """

    # Calculate centroids
    centroids1 = np.stack(((bboxes1[..., 0] + bboxes1[..., 2]) / 2,
                           (bboxes1[..., 1] + bboxes1[..., 3]) / 2), axis=-1)
    centroids2 = np.stack(((bboxes2[..., 0] + bboxes2[..., 2]) / 2,
                           (bboxes2[..., 1] + bboxes2[..., 3]) / 2), axis=-1)

    # Expand dimensions for broadcasting
    centroids1 = np.expand_dims(centroids1, 1)
    centroids2 = np.expand_dims(centroids2, 0)

    # Calculate Euclidean distances
    distances = np.sqrt(np.sum((centroids1 - centroids2) ** 2, axis=-1))

    # Normalize distances
    norm_factor = np.sqrt(w**2 + h**2)
    normalized_distances = distances / norm_factor

    return normalized_distances
```

**Comment by mikel-brostrom** [comment]
In order to be able to use the centroid cost above interchangeably with iou_cost the cost matrix should inverted:

    ```return 1 - normalized_distances```

**Comment by mikel-brostrom** [comment]
A ReID model won't help you because all the golf balls basically look the same @tgbaoo. But maybe you are detecting more objects?

**Comment by mikel-brostrom** [comment]
@tgbaoo 

You can now try:

```py
from boxmot import OCSORT

tracker = OCSORT(
    asso_func="centroid",
    iou_threshold=0.3  # use this to set the centroid threshold that match your use-case best
)
```

**Comment by mikel-brostrom** [comment]
Please share your results here @tgbaoo so that we can see how this performs for your use-case 😊

**Comment by mikel-brostrom** [comment]
At the moment this only works here: https://github.com/mikel-brostrom/yolo_tracking/pull/1249

**Comment by tgbaoo** [comment]
@mikel-brostrom, @colonelpanic8, Thanks for you guys passion and quick apply new logic for centroid based cost, I am currently just detect only the golf ball only for this stage, for future stage is also detect the golfer for design system for my app demonstrate the which player are taking the shot and the result belong to which user

I am applying the new logic so the clip result will be updated soon. 

Thanks you so much for your consult and support once again.

**Comment by tgbaoo** [comment]
@mikel-brostrom Before I already have a quick test, the result magically robust, I writing some code to imwrite the video, I will post some result soon, stay tune!

Thanks again from @colonelpanic8 and @mikel-brostrom support <3

**Comment by tgbaoo** [comment]
@colonelpanic8, @mikel-brostrom This is my some result test on OCSORT:

https://github.com/mikel-brostrom/yolo_tracking/assets/86455738/a8102b2c-7729-406c-8323-c5fbd5c6347e

https://github.com/mikel-brostrom/yolo_tracking/assets/86455738/b3feb541-99fc-4c76-83c0-8015ba3d987b

https://github.com/mikel-brostrom/yolo_tracking/assets/86455738/1d90ac50-b66b-471b-80ee-5eca53af3e22

I am gonna testing DeepOCSORT, and update to the same comment, but I noticed that this is good with fast moving (like golf putting) but not seem's good with smaller trend + fast moving (like golf swing clip), do you guys have any solution/idea for handle insanely fast moving and smaller trend object like the golf swing?

**Comment by mikel-brostrom** [comment]
Exactly what I was expecting 🔥. The question related to dynamic speed object (fast to slow/ slow to fast) tracking is a matter of adaptive KFs. In order to get this working you will need to carefully study the system and its dynamics.

**Comment by tgbaoo** [comment]
@mikel-brostrom Really appreciate your knowledge and expertise again.

For next stage of the project is try to draw the golf swing path line, with the sample video like I attached above, from your experience, do you have any recommendation, consulting, solution or just few keywords for me to do research on my own to solve the drawing exactly or nearly golf path line of the golf swing.

I have do some research, they give me some keywords related about motion tracking rather than actually visual object tracking.

One of them is this repo, they do some C++ code (which is a little bit hardcore for me) but if you have time, your attention on this repo and give me some opinion or recommendation is very useful to me.

Thanks for your work ⛳🙌🙌🙌🔥🔥🔥

**Comment by mikel-brostrom** [comment]
> For next stage of the project is try to draw the golf swing path line, with the sample video like I attached above, from your experience, do you have any recommendation

Have you tried SAHI for the swing video with the metric I just implemented?

**Comment by tgbaoo** [comment]
@mikel-brostrom, I already applied SAHI and I realized that the delay of the inference is not compatible with my realtime stream camera application, I considered design my own algorithm like:

A few first frame I use yolo like normal

When I detect the ball success, then I create a window for 'detect area', then I detect for only the 'detect area' then when the ball is hit, if the ball is moving from the center of the detect area, we also move the 'detect area' Follow to the ball, then when the ball too small and lose the detection, I hard code the 'drop down' effect like the PGA Tour sample video below:
https://github.com/mikel-brostrom/yolo_tracking/assets/86455738/9a600ef2-08f9-4b97-a09f-10cb175ea137

From the technical opinion, how would you think about my logic? Is that possible to apply? I will run some code using chatgpt support for the algorithm.

**Comment by mikel-brostrom** [comment]
If it works well using SAHI. This:

> When I detect the ball success, then I create a window for 'detect area', then I detect for only the 'detect area' then when the ball is hit, if the ball is moving from the center of the detect area, we also move the 'detect area' Follow to the ball,

I guess should work too.

> I hard code the 'drop down' effect

This I believe will be very difficult to achieve with a realistic outcome. But sure, try it out :smile:

**Comment by 050603** [comment]
> @tgbaoo
> 
> 您现在可以尝试：
> 
> ```python
> from boxmot import OCSORT
> 
> tracker = OCSORT(
>     asso_func="centroid",
>     iou_threshold=0.3  # use this to set the centroid threshold that match your use-case best
> )
> ```
> 
> `iou_threshold`现在😄必须更改为仅阈值。0.7 iou_threshold表示只有图像对角线 30% 以内的对象（以像素为单位）才会被接受为可能的匹配项。

@mikel-brostrom HI, may I ask which file should this code be added to?

**Comment by 050603** [comment]
> @tgbaoo
> 
> You can now try:
> 
> ```python
> from boxmot import OCSORT
> 
> tracker = OCSORT(
>     asso_func="centroid",
>     iou_threshold=0.3  # use this to set the centroid threshold that match your use-case best
> )
> ```
> 
> `iou_threshold` has to be changed to only threshold now 😄. 0.7 iou_threshold means that only objects within 30% of the images's diagonal in pixels will be accepted as possible matches.

@mikel-brostrom HI, may I ask which file should this code be added to?

**Comment by 050603** [comment]
@mikel-brostrom Thanks a lot

**Comment by tgbaoo** [comment]
@mikel-brostrom Hello Mikel, now I am moving to deploy my project to production, can I open another question label to discuss about how we process the tracker and detector keep process real time (with high frame rate and low latency - delay) as much as possible from streaming frames from Ip camera?

**Comment by mikel-brostrom** [comment]
Sure @tgbaoo !
