### ISSUE TITLE
error in downloading the re_id models 

### ISSUE THREAD

**Issue by SuenoSn** [mikel-brostrom/yolo_tracking#1248]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

i guess i have error in downloading the re_id models: 
ne 349, in __init__
    self.model = ReIDDetectMultiBackend(weights=model_weights, device=device, fp16=fp16)
line 64, in __init__
    gdown.download(model_url, str(w), quiet=False)

 line 259, in download     filename_from_url = m.groups()[0] AttributeError: 'NoneType' object has no attribute 'groups'

**Comment by mikel-brostrom** [comment]
https://github.com/wkentaro/gdown/issues/291

**Comment by mikel-brostrom** [comment]
The latest version of the pkg solves this :smile:

**Comment by SuenoSn** [comment]
thank you, it was solved by donwgrading the gdown package

> The latest version of the pkg solves this 😄
