### ISSUE TITLE
ImportError: Bad git executable.

### ISSUE THREAD

**Issue by wolfgang1021** [mikel-brostrom/yolo_tracking#1250]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi mikel,
I have installed the packages requested in requirements.txt. 
Name: GitPython
Version: 3.1.41
But I get the following error when I try to run val.py:

Traceback (most recent call last):
  File "D:\Anaconda\envs\Yolo-Tracking\lib\site-packages\git\__init__.py", line 140, in <module>
    refresh()
  File "D:\Anaconda\envs\Yolo-Tracking\lib\site-packages\git\__init__.py", line 127, in refresh
    if not Git.refresh(path=path):
  File "D:\Anaconda\envs\Yolo-Tracking\lib\site-packages\git\cmd.py", line 456, in refresh
    raise ImportError(err)
ImportError: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\work\yolo_tracking-master\examples\val.py", line 28, in <module>
    import git
  File "D:\Anaconda\envs\Yolo-Tracking\lib\site-packages\git\__init__.py", line 142, in <module>
    raise ImportError("Failed to initialize: {0}".format(_exc)) from _exc
ImportError: Failed to initialize: Bad git executable.
The git executable must be specified in one of the following ways:
    - be included in your $PATH
    - be set via $GIT_PYTHON_GIT_EXECUTABLE
    - explicitly set via git.refresh()

All git commands will error until this is rectified.

This initial warning can be silenced or aggravated in the future by setting the
$GIT_PYTHON_REFRESH environment variable. Use one of the following values:
    - quiet|q|silence|s|none|n|0: for no warning or exception
    - warn|w|warning|1: for a printed warning
    - error|e|raise|r|2: for a raised exception

Example:
    export GIT_PYTHON_REFRESH=quiet

**Comment by mikel-brostrom** [comment]
I have never used anaconda. I am afraid I cannot help your here if you are not installing the package in the way it is recommended

**Comment by wolfgang1021** [comment]
Thanks for your reply, I'll try running val.py in ubuntuOS.

**Comment by wolfgang1021** [comment]
Hi mikel,
I tried the evaluation using yolov8m's model with BoT-SORT tracker and 'osnet_ibn_x1_0_msmt17.pt' ReID model. But got high metrics with conf-threshold at 0.1. Different results from the experiment you did with the 5m model, do you know the reason for that?
<img width="421" alt="conf-ther" src="https://github.com/mikel-brostrom/yolo_tracking/assets/122220514/699f2e4c-fcbf-4ad1-9d4c-ac1582dd1b5c">

**Comment by mikel-brostrom** [comment]
`Yolov5` does not perform the same as `Yolov8`
