### ISSUE TITLE
How can I use this repo on Android? Any suggestions are appreciated.

### ISSUE THREAD

**Issue by yijunwu** [mikel-brostrom/yolo_tracking#1251]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Some track algorithms have been migrated to Android, e.g. [this one](https://github.com/yaoyi30/ByteTrack_ncnn_Android) for ByteTrack. Is it possible to run yolo_tracking(BoxMOT) on Anroid as well? Any suggestions on resources/approaches are appreciated.

**Comment by mikel-brostrom** [comment]
> Is it possible to run yolo_tracking(BoxMOT) on Anroid as well?

Sadly this is a python only repo for now

> Any suggestions on resources/approaches are appreciated.

There are many resources out there. But the repo you found seems to be a good start :smile:

**Comment by yijunwu** [comment]
Thank you 😄
