### ISSUE TITLE
Using SORT tracker with the YOLO models

### ISSUE THREAD

**Issue by Sumeshbaba** [mikel-brostrom/yolo_tracking#1253]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello. Great work with integrating the YOLO and recent tracking models! 

I checked the repository and saw that there is no option to track with SORT algorithm. 

Is there anyway you can include SORT tracking option to the repository as well?

Thanks a lot.

**Comment by mikel-brostrom** [comment]
I have no plans of implementing SORT. There are plenty of SORT resources out there :smile:
