### ISSUE TITLE
How to use this repo for multiple camera  

### ISSUE THREAD

**Issue by adinathkale01** [mikel-brostrom/yolo_tracking#1258]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, I want to use this repository for multiple cameras for tracking multiple objects, In this it is showing only for a single source  
python track_v5.py --source 0 --yolo-weights weights/yolov5n.pt --img 640

**Comment by mikel-brostrom** [comment]
You have two options:

```py
# Multiple streams with batched inference (i.e. batch-size 8 for 8 streams)
source = 'path/to/list.streams'  # *.streams text file with one streaming address per row
```

or:

```py
# Define a path to a CSV file with images, URLs, videos and directories
source = 'path/to/file.csv'
```
