### ISSUE TITLE
how can i evaluate on first half of MOT17 ?

### ISSUE THREAD

**Issue by wumiaowang66** [mikel-brostrom/yolo_tracking#1262]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thank you for your outstanding work. I would like to know how I can modify the code to evaluate it on either the first half or the second half of MOT17?

**Comment by mikel-brostrom** [comment]
You would need to split MOT17 in half. In order to achieve this you could use: https://github.com/mikel-brostrom/yolo_tracking/blob/split-ds-by-factor/split.py. Then just point to the split dataset when evaluating.
