### ISSUE TITLE
How to use this repository for Multi-camera and multi object tracking 

### ISSUE THREAD

**Issue by adinathkale01** [mikel-brostrom/yolo_tracking#1264]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I just had a query regarding usage of multicamera object tracking for my academic project
I'm using the below command to run for the 2 camera feed
**python3 track.py --source 2 4 --reid-model osnet_x0_25_msmt17.pt --show**

but I'm getting below error
track.py: error: unrecognized arguments: 4

**could you please suggest me a way to include both camera feeds and assign the same ID for the object when it passes through these camera frames?**

thank you in advance!!

**Comment by mikel-brostrom** [comment]
You have two options:

```py
# Multiple streams with batched inference (i.e. batch-size 8 for 8 streams)
source = 'path/to/list.streams'  # *.streams text file with one streaming address per row
```

or:

```py
# Define a path to a CSV file with images, URLs, videos and directories
source = 'path/to/file.csv'
```

> same ID for the object when it passes through these camera frames?

This we don't support

**Comment by adinathkale01** [comment]
Thank you for the reply,
If you don't mind, could you please suggest any alternative repo for the same ID for the object when it passes through multi-camera frames?
OR How can I achieve this task by customizing this existing track.py file 
it would be very helpful :)
thank you!!!!

**Comment by thejasonfisher** [comment]
> Thank you for the reply, If you don't mind, could you please suggest any alternative repo for the same ID for the object when it passes through multi-camera frames? OR How can I achieve this task by customizing this existing track.py file it would be very helpful :) thank you!!!!

You need a homography to a "global" coordinate space, and then do tracking in that space, and then you can use the reverse of the homography for each camera from the global space.  Basically NMS on boxes in the global space and a custom tracking of ID sets.

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/594#issuecomment-1310624465
