### ISSUE TITLE
Adding support for SparseTrack?

### ISSUE THREAD

**Issue by FrancescoDeMatteo** [mikel-brostrom/yolo_tracking#1268]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

First and foremost let me thank you for the very useful and well-organized repository. It is not a trivial matter in the field of tracking algos. It is much appreciated.

I wanted to ask if adding support for Sparse Track, (being a bit reductive here) an upgraded version of Bytetrack, is in your plans.

https://paperswithcode.com/sota/multi-object-tracking-on-mot20-1?metric=HOTA

I find interesting that some motion-only algorithms such as StarseTrack and UCMC Track are showing very competitive and SOTA performance even compared to appearance-relying ones. At least on MOTs databases.
While I realized that automating a pipeline for UCMC would be pretty labor-intensive, just wanted to know if you had plans about Sparsetrack.

Let me renew my thanks.
Francesco

**Comment by mikel-brostrom** [comment]
> First and foremost let me thank you for the very useful and well-organized repository. It is not a trivial matter in the field of tracking algos. It is much appreciated.

Glad I could help :smile: 

> I wanted to ask if adding support for Sparse Track, (being a bit reductive here) an upgraded version of Bytetrack, is in your plans.

I am not sure tbh. I checked out UCMC but saw it required camera parameters estimation. Although the code is openly available I am not certain how well it performs on other images. For that reason SparseTrack seems like abetter candidate for this repo.
