### ISSUE TITLE
After tracking the model using trt, will appear IndexError: index 3 is out of bounds for axis 0 with size 3

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/yolo_tracking#1269]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/75210061/89e9df8a-bddd-4582-9881-a1621fc2c93a)
I tracked a video of three people with no error using the pt model, but this error occurred after using the deepocort method, osnet_x0_25_dukemtmcreid.engine model

### Environment

torch   1.12.1+cu113

### Minimal Reproducible Example

 This error appears on line 492 in deepocort.py
# create and initialise new trackers for unmatched detections
        for i in unmatched_dets:
            trk = KalmanBoxTracker(
                dets[i],
                delta_t=self.delta_t,
                emb=dets_embs[i],
                alpha=dets_alpha[i],
                new_kf=not self.new_kf_off
            )
            self.trackers.append(trk)

**Comment by mikel-brostrom** [comment]
How did you export the model? Please provide the complete command

**Comment by songjiahao-wq** [comment]
I see. Thank you
python boxmot/appearance/reid_export.py --device 0 --dynamic --include engine --weights examples/weights/osnet_x0_25_dukemtmcreid.pt --batch-size （A bigger number）

**Comment by mikel-brostrom** [comment]
Did it work? :smile:
