### ISSUE TITLE
Where is the OCSortKalmanFilterAdapter? I can't find it

### ISSUE THREAD

**Issue by PrincessLei-03** [mikel-brostrom/yolo_tracking#1270]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, when I trid to use deep_ocsort.py it said that OCSortKalmanFilterAdapter is missing and I have no idea where it is, anyone has the solution? Thanks in advance.

**Comment by mikel-brostrom** [comment]
Reclone or pip uninstal and then install again. You have an older version of the package
