### ISSUE TITLE
Prediction on new frames without YOLO detection 

### ISSUE THREAD

**Issue by ManuBN786** [mikel-brostrom/yolo_tracking#1271]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

I have the bbox 'dets' for the first frame which is obtained by fitting a rect on a set of contour points around a CT lung nodule.

For the subsequent frames,  i'm using the 'xyxys' from 'tracks'  for tracker.update.

i.e. the predictions from the previous frame will use used to update the tracker for the current frame.

I don't have a yolo detection. So I'm simply setting the confidence to 0.9 and there's only one class.

But this does not provide a varying bbox as the output. 

The tracker outputs the same bbox for all the subsequent frame.

How to fix this issue ? 

### Environment

python 3.8, cuda 11

### Minimal Reproducible Example

global tracks

    tracker = DeepOCSORT(model_weights=Path('osnet_x0_25_msmt17.pt'),  # which ReID model to use
        device='cuda:0',
        fp16=False,
    )

    tracked_bboxes_deep = []

    # As long as the first segmentation mask is perfect
    edged = cv2.Canny(masks_first, 20, 255)
    contours, hierarchy = cv2.findContours(edged, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

    print(len(contours), " Contours Shape ")

    contours = np.vstack(contours)
    x_deep_0, y_deep_0, w_deep_0, h_deep_0 = cv2.boundingRect(contours)

    tracked_bboxes_deep.append((x_deep_0, y_deep_0, w_deep_0, h_deep_0))

    x2_deep_0 = x_deep_0 + w_deep_0
    y2_deep_0 = y_deep_0 + h_deep_0

    count_frame = 0

    # Get the video file and read it
    video = cv2.VideoCapture(video_path)

    total_frames = int(video.get(cv2.CAP_PROP_FRAME_COUNT))

    all_tracked_IDs = []

    while count_frame<total_frames:

        print(count_frame," Frame count")

        ret, im = video.read()

        # Initialize first frame with the bbox around contour
        if count_frame == 0:
            # substitute by your object detector, input to tracker has to be N X (x, y, x, y, conf, cls)
            dets_0 = np.array([[x_deep_0, y_deep_0, x2_deep_0, y2_deep_0, 0.9, 0]])
            tracks = tracker.update(dets_0, im)  # --> (x, y, x, y, id, conf, cls, ind)

        # Update the tracker with bbox from previous prediction
        elif count_frame > 0:

            x_deep, y_deep, w_deep, h_deep = tracked_bboxes_deep[-1]

            x2_deep = x_deep + w_deep
            y2_deep = y_deep + h_deep

            dets = np.array([[x_deep, y_deep, x2_deep, y2_deep, 0.9, 0]])

            print(dets," The detection results")
            tracks = tracker.update(dets, im)  # --> (x, y, x, y, id, conf, cls, ind)

        xyxys = tracks[:, 0:4].astype('int')  # float64 to int
        ids = tracks[:, 4].astype('int')  # float64 to int
        all_tracked_IDs.append(ids)
        confs = tracks[:, 5]
        clss = tracks[:, 6].astype('int')  # float64 to int
        inds = tracks[:, 7].astype('int')  # float64 to int

        im_copy = copy.deepcopy(im)

        # in case you have segmentations or poses alongside with your detections you can use
        # the ind variable in order to identify which track is associated to each seg or pose by:
        # segs = segs[inds]
        # poses = poses[inds]
        # you can then zip them together: zip(tracks, poses)

        # print bboxes with their associated id, cls and conf
        if tracks.shape[0] != 0:

            for xyxy, id, conf, cls in zip(xyxys, ids, confs, clss):

                bbox = (xyxy[0], xyxy[1], xyxy[2] - xyxy[0] , xyxy[3] - xyxy[1])

                tracked_bboxes_deep.append(bbox)

                cv2.rectangle(im_copy,(xyxy[0], xyxy[1]),(xyxy[2], xyxy[3]),(0, 0, 255), 2)
                cv2.putText(im_copy,f'id: {id}, conf: {conf}, c: {cls}',(xyxy[0], xyxy[1] - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 0, 255), 2)

        # if there's no tracking then use previous bbox
        elif tracks.shape[0] == 0 :

            if count_frame >= 1 and len(tracked_bboxes_deep) != 0:

                tracked_bboxes_deep.append(tracked_bboxes_deep[-1])

        # Detect ID switching from previous
        if count_frame >= 1 and (all_tracked_IDs[count_frame] != all_tracked_IDs[count_frame - 1]):
            print(" Bbox Tracker Has switched IDs ")

        print(tracked_bboxes_deep," All of the tracked bboxes ")

        #cv2.imwrite("/home/manu/Downloads/bronchoscopy/small_dataset_PIPsSAM/results/lung_009/deep_tracking/sam_deepSort/" + str(count_frame) + '.png', im_copy)

        cv2.imshow(" Tracked BBOXES ", im_copy)
        cv2.waitKey(0)

        count_frame+=1

    video.release()

**Comment by mikel-brostrom** [comment]
This is not how this repo works. You won't get predictions based on an input. The predictions for each frame are associated to Kalman Filter bbox predictions. If no associations are made you won't get an output.

**Comment by ManuBN786** [comment]
Can you please add a detailed example of how to do it ?

The example here https://github.com/mikel-brostrom/yolo_tracking#custom-object-detection-model-tracking-example is rather misleading.
