### ISSUE TITLE
adapt to more new technological solutions

### ISSUE THREAD

**Issue by 050603** [mikel-brostrom/yolo_tracking#1272]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Do you have plans to adapt to more new technological solutions, such as:[UCMCTrack](https://github.com/corfyi/UCMCTrack.)
Or other new tracking technologies

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
My intention was to implement: https://arxiv.org/abs/2306.05238. UCMCTrack seems to be more difficult to get into the repo as it needs camera parameters estimation. I just don't have time atm. But feel free to implement any of these and will be more than happy to review them :smile:
