### ISSUE TITLE
Any Vehicle ReID Models?

### ISSUE THREAD

**Issue by shreejalt** [mikel-brostrom/yolo_tracking#1274]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi,
Does this repo support an vehicle reid based models apart from Clip models? Because CLIP models doesn't work when we instantiate it in any appearance based trackers

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/1155#issuecomment-1783102293

**Comment by mikel-brostrom** [comment]
> Does this repo support an vehicle reid based models apart from Clip models?

Not at the moment
