### ISSUE TITLE
numpy version

### ISSUE THREAD

**Issue by NVRGUP** [mikel-brostrom/yolo_tracking#1275]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello! NumPy>=1.20.0 doesn't support np.int/np.float, but MOT_eval always uses 'np.int'.What should I do?

**Comment by mikel-brostrom** [comment]
That is why `val.py` contain these lines of code:

https://github.com/mikel-brostrom/yolo_tracking/blob/11a09da99d35212e86a5a2b1b4fc43eef340a3dc/examples/val.py#L67-L73

**Comment by NVRGUP** [comment]
thank you very much!

> That is why `val.py` contain these lines of code:
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/11a09da99d35212e86a5a2b1b4fc43eef340a3dc/examples/val.py#L67-L73
