### ISSUE TITLE
Yolov5 support as a detector

### ISSUE THREAD

**Issue by sourabhyadav** [mikel-brostrom/yolo_tracking#1296]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi @mikel-brostrom , 
I've been working with your repo for the past couple of months and it has been a delight. 
Just recently I had to try out yolov5 model instead of yolov8 and realized that it seems there are checks in place in the code to make sure that - 'Your model name has to contain either yolox, yolo_nas or yolov8'. Would it be possible for you to guide me on how to run a yolov5m model in the repo? 

I have a hunch that there would be some custom modifications to be done to 'examples->detectors->yolo_interface.py/__init__.py'? Is that right? I made some quick modifications but they didn't seem to work as planned, so do you have some directions as to how I could get Yolov5 working? 

The questions related to this that I found in the previous issues are all relatively old, thus asking this again here. Let me know if this question suits here or shall I remove it. Thanks for your work.

**Comment by sourabhyadav** [comment]
@mikel-brostrom That's very much understandable. 

I have a hunch that there would be some custom modifications to be done to 'examples->detectors->yolo_interface.py/init.py' and a new file would need to be added for 'yolov5.py'? Is that direction right to think in? 
I made some quick modifications but they didn't work as planned, so do you have some directions as to how I could get Yolov5 working? I only ask as it's very crucial for me to do this. 
And again, thanks for such a quick response! :)

**Comment by sourabhyadav** [comment]
@mikel-brostrom - Another question that I wanted to ask here, is it possible for me to get the yolov5 output (from the Ultralytics repo) separately and just run the trackers (OC-SORT and DeepOCSORT) in boxmot on that output? What would be the way to do that? 

And if the above technique works, I'd love to contribute it as a tutorial too (if it doesn't already exist) for others to - 
1. get their output from their own detectors and 
2. use boxmot's trackers on those outputs.

**Comment by mikel-brostrom** [comment]
> 'examples->detectors->yolo_interface.py/init.py' and a new file would need to be added for 'yolov5.py'? Is that direction right to think in?

Yup that is right. But first you need the submodule for importing the right stuff :smile:

**Comment by sourabhyadav** [comment]
> Yup that is right. But first you need the submodule for importing the right stuff such that you can load you yolov5 weights and run inference using it 😄

Got it. 

> @mikel-brostrom - Another question that I wanted to ask here, is it possible for me to get the yolov5 output (from the Ultralytics repo) separately and just run the trackers (OC-SORT and DeepOCSORT) in boxmot on that output? What would be the way to do that?
> 
> And if the above technique works, I'd love to contribute it as a tutorial too (if it doesn't already exist) for others to -
> 
> 1. get their output from their own detectors and
> 2. use boxmot's trackers on those outputs.

Any thoughts on this?

**Comment by mikel-brostrom** [comment]
> Any thoughts on this?

You could store the detections for each frame in a list `[dets_frame1, dets_frame2, ..., dets_frameN]`. Then, you could dump this data and such that you can reload it anywhere else. After that you could just run the examples provided by this repo :smile:

**Comment by Hemilibeatriz** [comment]
> @mikel-brostrom- Outra pergunta que eu queria fazer aqui, é possível para mim obter a saída do yolov5 (do repositório Ultralytics) separadamente e apenas executar os rastreadores (OC-SORT e DeepOCSORT) no boxmot nessa saída? Qual seria a maneira de fazer isso?
> 
> E se a técnica acima funcionar, eu adoraria contribuir como um tutorial também (se ainda não existir) para que outros possam -
> 
> 1. obtêm a saída dos seus próprios detectores e
> 2. use os rastreadores do boxmot nessas saídas.

Hi @sourabhyadav!

Did you get it? I really need this. Can you explain to me how you did it?
