### ISSUE TITLE
Add Counter to count the classes detected

### ISSUE THREAD

**Issue by arbaazglobant** [mikel-brostrom/yolo_tracking#1299]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Add a functionality that counts the number of object in each frame  by frame. also dont keep updating the counter based on the ids or detected object but keep the counter separate just based on the object detected in each frame.

### Use case

So we can count the objects throughout the entire video

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
To implement this for all trackers in an easy way. It requires a common inherited superclass for all the trackers which is not in place at the moment.
