### ISSUE TITLE
bytetracker silent or verbose=0?

### ISSUE THREAD

**Issue by bryanlegrand** [mikel-brostrom/yolo_tracking#1301]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

This may seem a little silly, but for all tracking methods there's no print statement in the terminal, except for bytetracker which prints what I'm assuming are the current tracks? Is there anyway to be able to switch that on/off via a variable or otherwise?

Apparently this also applies for BoTSORT tracker....

Thanks in advance and thanks for all the great work on boxmot :).

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/blob/80bc49b55b1e73e2a13cf064dda165096f5b53b3/examples/track.py#L189-L190

You could set `default=False`

**Comment by bryanlegrand** [comment]
I'm constructiong the tracker individually as a custom tracker, similar to minimalist, complete, and tiled examples provided in the readme.

e.g 
`
from boxmot import BYTETracker
        tracker = BYTETracker(
            track_thresh=0.35,
            track_buffer=max_age,
            match_thresh=0.9,
        )`

I've tried verbose directly in the constructor and when looking through the code I haven't found any variable that worked via this method.

Thanks for taking the time to respond.

**Comment by mikel-brostrom** [comment]
I looked for print statements in bytetrack and botsort and cannot find any...

**Comment by bryanlegrand** [comment]
> I looked for print statements in bytetrack and botsort and cannot find any...

I couldn't find any either, guess it's not just me... Thanks for taking a look.
