### ISSUE TITLE
Use DeepOCSort to predict next location of object

### ISSUE THREAD

**Issue by TuanBao0711** [mikel-brostrom/yolo_tracking#1302]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, I'm using the image matching LighGlue to detect my object and get a detect infomation as "detectResults" simple detectResults  [[1858  740 1608  620    0.6    4]]  (xyxy, confi , cls) but When I use this for Update def of DeepOCSort I have a error

Traceback (most recent call last):
  File "C:\Users\TuanBao\Desktop\My_Docs\CNTT\predict trajectory\Tracking\testLGDOS.py", line 137, in <module>
    LocationPred = tracker.predict_location(detectResults, frame)
  File "C:\Users\TuanBao\Desktop\My_Docs\CNTT\predict trajectory\Tracking\boxmot\trackers\deepocsort\deep_ocsort.py", line 536, in predict_location
    dets_embs = self.model.get_features(dets[:, 0:4], img)
  File "C:\Users\TuanBao\anaconda3\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\TuanBao\Desktop\My_Docs\CNTT\predict trajectory\Tracking\boxmot\appearance\reid_multibackend.py", line 300, in get_features
    crops = self.preprocess(xyxys, img)
  File "C:\Users\TuanBao\Desktop\My_Docs\CNTT\predict trajectory\Tracking\boxmot\appearance\reid_multibackend.py", line 195, in preprocess
    crop = cv2.resize(
cv2.error: OpenCV(4.8.1) D:\a\opencv-python\opencv-python\opencv\modules\imgproc\src\resize.cpp:4062: error: (-215:Assertion failed) !ssize.empty() in function 'cv::resize'

If I switch back to using yolo instead of LightGlue it works fine but my project needs to use LightGlue. I don't think my input structure is wrong because I use the same ByteTrack it doesn't give the error
​Help me :( Thanks

**Comment by mikel-brostrom** [comment]
Ok. So the error is here:

https://github.com/mikel-brostrom/yolo_tracking/blob/80bc49b55b1e73e2a13cf064dda165096f5b53b3/boxmot/appearance/reid_multibackend.py#L201-L205

For the bboxes, make sure that:

- the format follows: [x1, y1, x2, y2, confidence, class] 

For the crop:

- The crop is loaded correctly by displaying it using OpenCV's imshow function

**Comment by TuanBao0711** [comment]
> Ok. So the error is here:
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/80bc49b55b1e73e2a13cf064dda165096f5b53b3/boxmot/appearance/reid_multibackend.py#L201-L205
> 
> For the bboxes, make sure that:
> 
> * the format follows: [x1, y1, x2, y2, confidence, class]
> 
> For the crop:
> 
> * The crop is loaded correctly by displaying it using OpenCV's imshow function

Yes, i'm sure my input bboxes to format [x1, y1, x2, y2, confidence, class], because it's the same when I use it with ByteTrack and it doesn't give an error, about cv2 crop, I dont know how to fix, my cv2 can use imshow normally :((

**Comment by mikel-brostrom** [comment]
Run imshow on the crop. After this line of code: https://github.com/mikel-brostrom/yolo_tracking/blob/80bc49b55b1e73e2a13cf064dda165096f5b53b3/boxmot/appearance/reid_multibackend.py#L199

**Comment by TuanBao0711** [comment]
> Run imshow on the crop. After this line of code:
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/80bc49b55b1e73e2a13cf064dda165096f5b53b3/boxmot/appearance/reid_multibackend.py#L199

I dont understand, What do you want to display with imshow function? pls :((

**Comment by mikel-brostrom** [comment]
the crop

**Comment by TuanBao0711** [comment]
> the crop. By visualizing the crop you will understand what the model is creating the embedding out of.

Oh, I understand. Thank you so much, my mistake in main.py :(((

**Comment by TuanBao0711** [comment]
I have another question, When I use YOLO to predict next location , it work and return the next location bounding box in predict func , but with img matching this usually not return the next location predict :(((
