### ISSUE TITLE
Predict next Location boudingbox of object

### ISSUE THREAD

**Issue by TuanBao0711** [mikel-brostrom/yolo_tracking#1304]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

 I am trying to get project predict the trajectory of an object when obscured, I use ByteTrack and DeepOcSort to predict next location bounding box of Object.  When I use YOLO to get bounding box and predict next location , it work and return the next location bounding box in predict func , but with image matching is LightGlue, I also get a bounding box but when I use this for predict next location bounding box this usually not return the next location predict :((( the format input I set same YOLO. :(( Thank you

**Comment by mikel-brostrom** [comment]
The trackers are designed to predict the next bbox only if an association was performed. If you want to predict bboxes indefinitely you need to make custom modifications to the trackers
