### ISSUE TITLE
How to replace yolov8 with yolov9

### ISSUE THREAD

**Issue by 050603** [mikel-brostrom/yolo_tracking#1305]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Now that yolov9 has been launched, I would like to try using yolov9 in yolotracing. May I ask if this is feasible? Do you have a plan to adapt? Or could you tell me how to replace the detector in YOLOtracking.

**Comment by mikel-brostrom** [comment]
I asked on their repo if they plan to release a pip-package out of Yolov9. In that case, when released,I will add it asap.

**Comment by 050603** [comment]
> I asked on their repo if they plan to release a pip-package out of Yolov9. In that case, when released,I will add it asap.

I saw a third-party packaged pip package：https://github.com/kadirnar/yolov9-pip

**Comment by mikel-brostrom** [comment]
Ohh! Then this makes everything muuuch easier. I will start this work today

**Comment by 050603** [comment]
> Ohh! Then this makes everything muuuch easier. I will start this work today


A great project!Thank you for your efforts.

**Comment by mikel-brostrom** [comment]
I tried out Yolov9 but the package but is full of relative imports which collide with files in this repo for example `from utils import ...` collides with `utils` under `examples/`

**Comment by 050603** [comment]
> I tried out Yolov9 but the package but is full of relative imports which collide with files in this repo for example `from utils import ...` in yolov9 collides with `utils` under `examples/`. This could be avoided by absolute imports using the full path to the project's root folder.

Thank you very much for trying and suggesting. So if I want to replace yolov8 with yolov9 or yoloworld in this project, I just need to install the pip package and change some naming?

**Comment by mikel-brostrom** [comment]
The pkg has to be properly built. Otherwise it will create issues when being integrated with the rest of the repo. Like I explained in my previous comment. It should be fairly easy to add other detectors under `tracking/detectors` :smile:
