### ISSUE TITLE
Centroid-based association in OCSORT keeps switching IDs for the same detection

### ISSUE THREAD

**Issue by ThenoobMario** [mikel-brostrom/yolo_tracking#1308]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, I am experimenting with the centroid-based association for my use case where I won't be able to process a lot of frames at the same time. I went through #1246 where it showed good results. However, when there are two persons in the frame, the id keeps on switching between the two, alternatively showing 1 and 2 over the same person. 

What can be the issue?

**Comment by mikel-brostrom** [comment]
If the threshold for the association is too large. There is certainly a risk of objects being mixed up. Try a lower threshold.

**Comment by ThenoobMario** [comment]
Hi @mikel-brostrom, thanks for the reply. I am attaching my configurations.

```python

tracker = OCSORT(det_thresh = 0.4,
                 max_age = 120,
                 min_hits = 3,
                 asso_threshold = 0.2,
                 delta_t = 3,
                 asso_func = "centroid",
                 use_byte = False)
```
The ID switching is still an issue. I tried keeping the `asso_threshold` high as well as low.

**Comment by mikel-brostrom** [comment]
Centroid-based association may be problematic if both objects are within each others association distances. There is no magic solution for this...

**Comment by ThenoobMario** [comment]
I do understand it can be problematic for objects that are within each other's association distances. [Here is a case](https://esecconsultants-my.sharepoint.com/:v:/p/nachiket_s/EU9EE9iIvsxNkIVDt8UXe3QBqr23PQvSPO3yoC7bJCs8Gw?nav=eyJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJPbmVEcml2ZUZvckJ1c2luZXNzIiwicmVmZXJyYWxBcHBQbGF0Zm9ybSI6IldlYiIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJNeUZpbGVzTGlua0NvcHkifX0&e=3M5CIu). Will this count as objects being within their association distances?

**Comment by mikel-brostrom** [comment]
The performance of your object detector seems to be very poor. A lot of flickering is noticeable in the video. This is clearly not a problem mainly  of the tracker but of the object detector.
