### ISSUE TITLE
Tracking based on off-the-shelf detections and features

### ISSUE THREAD

**Issue by dyhBUPT** [mikel-brostrom/yolo_tracking#1310]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Thanks for your excellent repo!
Does this repo support tracking with off-the-shelf detections and reid features?
If it supports, then we can greatly accelerate the experiments focusing on trackers.
Moreover, we can more easily introduce other detectors and feature extractors.

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
First of all. Great work on StrongSORT @dyhBUPT!

>  Does this repo support tracking with off-the-shelf detections and reid features?

This is exacly the intention of this repo! To accelerate tracking experimentation. At the moment, this repo supports off-the-shelf models for Yolov8, YoloNAS and YoloX. I also added the Bytetrack YoloX people models for automatic download. It also supports multiple off-the-shelf ReID models. Adding both detectors and ReID models should be fairly easy :smile:

**Comment by dyhBUPT** [comment]
Hi, thanks for your reply~ Your repo benefits the MOT community greatly!
> But loading detections and features stored in files is not supported. This would need to be implemented. Is this what you mean @dyhBUPT ?

Yes, that's what I mean. Because in tracking inference, `detection` and `reid` often dominate the time cost compared with `tracking`. This will waste too much time in experiments.

Indeed, this is a common problem of existing MOT repos, e.g., [mmtracking](https://github.com/open-mmlab/mmtracking), [ByteTrack](https://github.com/ifzhang/ByteTrack). This makes me prefer the official repo of [DeepSORT](https://github.com/nwojke/deep_sort) in my own experiments.

**Comment by mikel-brostrom** [comment]
I checked the numpy size of the `MOT16_POI_train/MOT16-02.npy` file in the DeepSORT repo. I get the following shape: `(14092, 138)`. What does this mean?

**Comment by dyhBUPT** [comment]
I suggest the format of official [DeepSORT](https://github.com/nwojke/deep_sort), which is a matrix with shape `N x (10+C)`, which `N` is the number of detections of the total sequence. The first `10` dimensions will contain some object information, e.g., frame_id x, y, w, h, score. The remaining `C` dimensions contain the appearance features.

You can also split this whole file to `T` sub-files, and each contains the frame-level detections.

**Comment by dyhBUPT** [comment]
Maybe ou can refer to this issue https://github.com/dyhBUPT/StrongSORT/issues/28. 😄

**Comment by dyhBUPT** [comment]
I'm not good at code programming. :joy:
I see that BoxMOT is highly bundled with ultralytics. Therefore it seems hard to realize this feature in `track.py` gently.
Maybe I suggest to create a new version of `track.py`, like `track_with_file.py` to support tracking with given detection and feature files.
And create a script like `generate_dets_and_embs_npy.py` to generate these files.

**Comment by mikel-brostrom** [comment]
Working on it here: https://github.com/mikel-brostrom/yolo_tracking/tree/generate-dets-n-emb-txt. Will let you know when it is ready for testing @dyhBUPT

**Comment by dyhBUPT** [comment]
Thanks for your work! 👍👍👍

**Comment by dyhBUPT** [comment]
Hi, mikel, you realize this feature in such a short time! :smile: :smile: :smile:

A small question is, do we still need the `yolo` object in `track_w_dets_n_embs.py`? If I understand correctly, maybe `yolo` can be removed?
https://github.com/mikel-brostrom/yolo_tracking/blob/c2bbd4c31cea021bc91b34078e646fecc142531c/experimentation/track_w_dets_n_embs.py#L46-L48

Another small suggestion is more flexible customization of `generate_dets_and_embs.py`. For example:

- only generate detections without embeddings, for tracking with ByteTrack / OC-SORT.
- only generate embeddings based on given detection files.

Thanks!

**Comment by mikel-brostrom** [comment]
Thanks for the feedback!

> A small question is, do we still need the yolo object in track_w_dets_n_embs.py? If I understand correctly, maybe yolo can be removed?

You are right. Deleted. Not needed :smile:

**Comment by dyhBUPT** [comment]
I get it, thanks~😄

**Comment by mikel-brostrom** [comment]
> only generate embeddings based on given detection files.

Still need to think a bit about how this should be implemented in the best possible way. So that detections can be combined with arbitrary embeddings from different ReID models...

**Comment by mikel-brostrom** [comment]
Because we want to be sure that the embeddings are coupled together with their respective detections

**Comment by mikel-brostrom** [comment]
![Screenshot from 2024-03-01 18-07-21](https://github.com/mikel-brostrom/yolo_tracking/assets/18719680/f87ba446-3ad5-4ac2-a308-fe09d6019dd4)

**Comment by mikel-brostrom** [comment]
I have a new way of working for generating detections for different yolo models and their associated embeddings. The workflow feels nice if you ask me :smile:. This now needs thorough testing by the community, so all feedback is more than welcomed.

**Comment by mikel-brostrom** [comment]
Just added the possibility to evolve the tracker parameters with pregenerated detections and embeddings. Again, this is in a very early face and has not been properly tested.

**Comment by dyhBUPT** [comment]
> Do you think it is a good setup for agilizing experimentation

Yes, I think it is a good choice~
BTW, maybe using `.npy` instead of `.txt` is better for `embs` for saving space?

Another optional choice is storing both `dets` and `embs` in the same `.npy` files, like:
```
runs
├── dets_n_embs
    ├── yolo_nas_s
        ├── none
            MOT17-02-FRCNN.npy
            ...
        ├── osnet_x0_25_msmt17
           MOT17-02-FRCNN.npy
            ...
```
where `none` means "dets w/o embs" with shape `Nx7`, others with shape `Nx(7+C)`.

**Comment by mikel-brostrom** [comment]
> BTW, maybe using .npy instead of .txt is better for embs for saving space?

`np.savetxt` is used. So the file is actually a binary file in npy format. The choice of changing the suffix from `.npy` to `.txt` is because `TrackEval` expects `.txt` files...

**Comment by mikel-brostrom** [comment]
BTW, the pipeline is making use of the pregenerated detections and embeddings, speeding up the testing process x4. So this will be beneficial on many different levels :smile:, not only for research purposes :rocket:

**Comment by mikel-brostrom** [comment]
I will close this down now @dyhBUPT as the feature is fully implemented and integrated into the CI pipeline :rocket:

**Comment by dyhBUPT** [comment]
Thanks for all your works!!!
