### ISSUE TITLE
Incorporate depth information to further enhance crowded scene and occlusions.

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/yolo_tracking#1319]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

by incorporating depth accuracy when there exists heavily or prolonged occluded objects can be greatly increased.

inspiration maybe taken from here but im not sure if its relevant 

https://github.com/hustvl/SparseTrack/tree/v8

### Use case

eg. I wanted to detect how long students stay in a class room/exam with a very low placed camera where students at the back become occluded for long periods of time. 

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
You mean using psedo-depth by the appraoch presented in sparsetrack? Or doyou mean 3D object tracking by using 4 channel camera with depth information?
