### ISSUE TITLE
mechanism of multiclass tracking

### ISSUE THREAD

**Issue by Sujie1528** [mikel-brostrom/yolo_tracking#1338]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

The original ByteTrack code only tracks one "person" class. But my current task requires tracking objects from ~70 classes. The author of ByteTrack proposes to create a tracker for each class but this would be inefficient. I'm curious how your ByteTrack code deals with multiclass tracking. Any explanations greatly appreciated!

**Comment by mikel-brostrom** [comment]
My suggestion would be to adapt the multi_class decorator to work with ByteTrack:

https://github.com/mikel-brostrom/yolo_tracking/blob/8c39d59a10a2233a4dff69b64c0bac7c316e17dc/boxmot/utils/__init__.py#L24

You don't need several trackers. You need to feed the class detections individually in class batches

**Comment by Sujie1528** [comment]
> My suggestion would be to adapt the multi_class decorator to work with ByteTrack:
> 
> https://github.com/mikel-brostrom/yolo_tracking/blob/8c39d59a10a2233a4dff69b64c0bac7c316e17dc/boxmot/utils/__init__.py#L24
> 
> You don't need several trackers. You need to feed the class detections individually in class batches

I believe the implementation from this repo can deal with multiclass tracking, because I saw people asked questions in the past: [https://github.com/mikel-brostrom/yolo_tracking/issues/927#issue-1742293861](url). But since this question was asked a while ago, I just want to confirm if the current implementation is still able to deal with multiclass situation. 

Could you please elaborate on this: 'You need to feed the class detections individually in class batches'? I could see how to implement this but I don't understand why I need to do this. Could you please share some thoughts on why this would make multiclass tracking possible? Even some high-level ideas would be awesome. Thank you so much!

**Comment by mikel-brostrom** [comment]
This just got implemented and tested for all trackers!

```
tracker = create_tracker(
    tracker_type=tracker_type,
    tracker_config=tracker_conf,
    reid_weights=WEIGHTS / 'mobilenetv2_x1_4_dukemtmcreid.pt',
    device='cpu',
    half=False,
    per_class=True      # <------------------------ notice this
)
```

**Comment by Sujie1528** [comment]
> This just got implemented and tested for all trackers!
> 
> ```python
> tracker = create_tracker(
>     tracker_type=tracker_type,
>     tracker_config=tracker_conf,
>     reid_weights=WEIGHTS / 'mobilenetv2_x1_4_dukemtmcreid.pt',
>     device='cpu',
>     half=False,
>     per_class=True      # <------------------------ notice this
> )
> ```

Thank you for the code snippet. It helps a lot! But I notice something when I use ByteTrack: In the ByteTrack branch of the create_tracker() function:[https://github.com/mikel-brostrom/yolo_tracking/blob/c575c679adb5ce3ba7a1df3ce6ea157b118fd529/boxmot/tracker_zoo.py#L56](url), the BYTETracker object is not initialized with the argument per_class; so the object will always be initialized with the default parameter per_class=False. Am I understanding this correctly? Maybe another line like `per_class=per_class` should be inserted into the initialization?

**Comment by mikel-brostrom** [comment]
Done!

**Comment by Sujie1528** [comment]
> Oh, I see. Thanks for pointing this out! I will add this argument to the tracker creation in the model zoo 😄

Thank you! A dumb follow-up question: how to run the latest code? I cloned the master branch to my computer and run `python track.py`, but it complains:
```
Traceback (most recent call last):
  File "track.py", line 9, in <module>
    from boxmot import TRACKERS
ModuleNotFoundError: No module named 'boxmot'
```
I have uninstalled pip-installed boxmot because I notice the source code is of older version.

**Comment by mikel-brostrom** [comment]
Please follow: https://github.com/mikel-brostrom/yolo_tracking?tab=readme-ov-file#installation

**Comment by Sujie1528** [comment]
Hi, I run the code with `per_class=True` and with `per_class=False` using ByteTrack. But the visualization of resulting tracks differ by a lot. With `per_class=False`, the tracks look OK (although there are jumping IDs); but when I set `per_class=True`, some objects are not tracked at all. I cannot wrap my head around this. Could you please share some thoughts what leads to the untracked objects when `per_class=True`? I've attached the videos for comparison. 

https://github.com/mikel-brostrom/yolo_tracking/assets/63102146/049c935a-37fb-4fc5-b117-4451a6d10747



https://github.com/mikel-brostrom/yolo_tracking/assets/63102146/3588bbab-e47e-4213-b66f-07d9220be3c6

The config files for both cases are the same:
```
track_thresh: 0.5  # tracking confidence threshold, should be the same as model conf
track_buffer: 30   # the frames for keep lost tracks
match_thresh: 0.8  # matching threshold for tracking
frame_rate: 10     # FPS
conf_thres: 0.5122620708221085
```

Thank you in advance!

**Comment by mikel-brostrom** [comment]
I see the issue. My naive approach inputs one set of class detections at a time

**Comment by mikel-brostrom** [comment]
For now I believe that something like the following could work:

```py
import numpy as np
from boxmot.trackers.bytetrack.byte_tracker import BYTETracker


trackers = []
classses = [0, 1, 2, 3, 4, 5, 6, 7]
dets = np.array([[144, 212, 578, 480, 0.82, 0],
                 [425, 281, 576, 472, 0.56, 1],
                 [425, 281, 576, 472, 0.56, 2],
                 [425, 281, 576, 472, 0.56, 3],
                 [425, 281, 576, 472, 0.56, 7]])

for t in classes:
    trackers.append(BYTETracker())


detections_by_class = {
    class_id: np.array([det for det in dets if int(det[5]) == int(class_id)])
    for class_id in set(int(det[5]) for det in dets)
}

for class_id in detections_by_class.keys():
    current_class_detections = detections_by_class.get(class_id, np.empty((0, 6)))
    trackers[class_id].update(current_class_detections)

```

**Comment by mikel-brostrom** [comment]
I need to rethink the per class approach...

**Comment by Sujie1528** [comment]
> For now I believe that something like the following could work:
> 
> ```python
> import numpy as np
> from boxmot.trackers.bytetrack.byte_tracker import BYTETracker
> 
> 
> trackers = []
> classses = [0, 1, 2, 3, 4, 5, 6, 7]
> dets = np.array([[144, 212, 578, 480, 0.82, 0],
>                  [425, 281, 576, 472, 0.56, 1],
>                  [425, 281, 576, 472, 0.56, 2],
>                  [425, 281, 576, 472, 0.56, 3],
>                  [425, 281, 576, 472, 0.56, 7]])
> 
> for t in classes:
>     trackers.append(BYTETracker())
> 
> 
> detections_by_class = {
>     class_id: np.array([det for det in dets if int(det[5]) == int(class_id)])
>     for class_id in set(int(det[5]) for det in dets)
> }
> 
> for class_id in detections_by_class.keys():
>     current_class_detections = detections_by_class.get(class_id, np.empty((0, 6)))
>     trackers[class_id].update(current_class_detections)
> ```

Thank you for this! I think this code creates a tracker for each class. In my case, I have 70 classes and I'm not sure if this is efficient enough to run on an edge device. I plan to look at the ultralytics yolov8 tracking code and see how they implemented this.

**Comment by mikel-brostrom** [comment]
I searched through ultralytics' documentation but see nothing regarding tracking per class. But let me know if you find something :smile:

**Comment by mikel-brostrom** [comment]
I think a good way of doing this would be to   have a 2D list with active tracks per class. This would lead to a more efficient solution where the updates of one class wouldn't affect the others. I will start working on this next week :smile:

**Comment by Sujie1528** [comment]
> I think a good way of doing this would be to have a 2D list with active tracks per class. This would allow for a single tracker to handle all the different classes, where the updates of one class wouldn't affect the others. I will start working on this next week 😄

Yeah I looked at other repos (like this one: [https://github.com/CaptainEven/MCMOT-ByteTrack](url)). I think it is using exacly the same method you describes: [https://github.com/CaptainEven/MCMOT-ByteTrack/blob/b80b648450412251b502b6429d0d15558f87dcc9/yolox/tracker/byte_tracker_bu.py#L915](url). I guess this wouldn't be a big issue. 

The next problem I want to handle is the changing IDs. For instance, in per_class_false.mp4, beginning the 27th second, the dish  on bottom left with id 9 was quickly pulled to the right and subsequently its ID changed to 18. Would you please share some thoughts on how to mitigate this problem? Thank you so much!

**Comment by mikel-brostrom** [comment]
Yup. This:

https://github.com/CaptainEven/MCMOT-ByteTrack/blob/b80b648450412251b502b6429d0d15558f87dcc9/trackers/ocsort_tracker/ocsort.py#L552-L575

was exactly what I meant

**Comment by mikel-brostrom** [comment]
Should be working now @Sujie1528 :smile:

**Comment by mikel-brostrom** [comment]
Let me know if it works for you so that I can close this down

**Comment by Sujie1528** [comment]
> Let me know if it works for you so that I can close this down

Thank you for your implementation! Now it's able to track all the objects, but there are some issues. 

First, there's not a per-class visualization effect: ideally each class's first appearing object should have ID 1, but currently the IDs are still mixed up among classes. I realize this might only be my personal needs and I can implement something to achieve the desired effect.

Second, the problem of changing IDs seems to be more frequent than when I set `per_class=False`. I've attached videos for comparison. This phenomenon is very counter-intuitive for me.


https://github.com/mikel-brostrom/yolo_tracking/assets/63102146/0c718d8d-add4-4aff-a9b4-4606099017e4


https://github.com/mikel-brostrom/yolo_tracking/assets/63102146/a6d3ed8f-8a59-42b8-a338-a63811eba1ba

**Comment by mikel-brostrom** [comment]
> ideally each class's first appearing object should have ID 1, but currently the IDs are still mixed up among classes. I realize this might only be my personal needs and I can implement something to achieve the desired effect.

I see. This should be implemented for enabling multi-class evaluation. So will look into this. Thanks for the example videos!

**Comment by Sujie1528** [comment]
> > Let me know if it works for you so that I can close this down
> 
> Thank you for your implementation! Now it's able to track all the objects, but there are some issues.
> 
> First, there's not a per-class visualization effect: ideally each class's first appearing object should have ID 1, but currently the IDs are still mixed up among classes. I realize this might only be my personal needs and I can implement something to achieve the desired effect.
> 
> Second, the problem of changing IDs seems to be more frequent than when I set `per_class=False`. I've attached videos for comparison. This phenomenon is very counter-intuitive for me.
> 
>  per_class_true_1.mp4 
>  per_class_false_1.mp4

@mikel-brostrom Hi, after two week's of struggle, I managed to find the bug when `per_class=True`. The source of problem is a combination of this line: https://github.com/mikel-brostrom/yolo_tracking/blob/f6c3e9e74174265562ba4cf27b08cffb3f0cfcc8/boxmot/utils/__init__.py#L57, and this: https://github.com/mikel-brostrom/yolo_tracking/blob/f6c3e9e74174265562ba4cf27b08cffb3f0cfcc8/boxmot/trackers/bytetrack/byte_tracker.py#L151. So for a single frame, every class would increment frame_count by 1, leading to inflated frame counts. Thus any lost track would seem to have disappeared for many frames and thus got removed, leading to ID switches all over the place. I come up with this naive fix to just subtract the redundent frame counts in the PerClassDecorator class:
![bug_fix](https://github.com/mikel-brostrom/yolo_tracking/assets/63102146/f76f3b58-be63-46dc-a4b2-c4bbbb4b360a)
Please share if you have more elegant ways to solve this problem. Thank you!

**Comment by Soorajkumar36** [comment]
Hi there, i was using the 'deepocsort' and seems the same problem exists for me as well where for the same object multiple ids are generated throughout the video, can you suggest what i can do to eliminate this , i have used the argument '--per-class' too.

**Comment by Sujie1528** [comment]
> Hi there, i was using the 'deepocsort' and seems the same problem exists for me as well where for the same object multiple ids are generated throughout the video, can you suggest what i can do to eliminate this , i have used the argument '--per-class' too.

I described a potential fix in this comment: https://github.com/mikel-brostrom/yolo_tracking/issues/1338#issuecomment-2027359096. You can try adding the line (bounded in the red rectangle) to the source code and see if it solves the problem.

**Comment by mikel-brostrom** [comment]
Good catch on that bug @Sujie1528! Thanks for letting me know. This has now been fixed 🚀

**Comment by Soorajkumar36** [comment]
@Sujie1528  I used it but getting the error
 `tracks,remove_ids, add_remove_string = self.update(instance, class_dets, im)`
`ValueError: not enough values to unpack (expected 3, got 0)` 
after changing the line from `tracks= self.update(instance, class_dets, im)` to `tracks,remove_ids, add_remove_string = self.update(instance, class_dets, im)` 

> in the file  yolo_tracking\boxmot\utils\__init__.py

**Comment by mikel-brostrom** [comment]
Just use my latest release 😄

**Comment by Soorajkumar36** [comment]
@mikel-brostrom i used the latest release version 10.0.65 but it is still generating different ids for the same object for some cases as earlier, 
i ran the following in the CLI `python tracking/track.py  --yolo-model det_yolov8_14_02_24.pt --reid-model osnet_x0_25_msmt17.pt --tracking-method deepocsort --source left_view.mp4 --show --save --project results3 --name left_result --per-class --agnostic-nms --exist-ok --conf 0.25 --iou 0.45`   
can you suggest were am i doing wrong? or what can be done to improve

**Comment by mikel-brostrom** [comment]
These algorithms are not perfect. There will be ID switches for some cases.
