### ISSUE TITLE
Hello, about CLIP-REID’s vehicle model

### ISSUE THREAD

**Issue by 972821054** [mikel-brostrom/yolo_tracking#1344]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

First of all, thank you very much for your work, but when I used clip-reid, I found that when I used the vehicle model, there were dimensional errors? Could you please provide a solution to this problem?
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/83146207/4047d72f-bd82-4be1-b791-ff6c442ed4f5)

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/1155#issuecomment-1783102293
