### ISSUE TITLE
How to train BoTSORT

### ISSUE THREAD

**Issue by 050603** [mikel-brostrom/yolo_tracking#1346]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello Mikel. I would like to ask, if I want to train a BoTSORT tracking model, should I refer to the method in the BoTSORT code base? I have this question because I noticed that the training methods mentioned in the official training instructions written by BoTSORT are very different from the training methods you mentioned in other questions.

**Comment by 050603** [comment]
Are the only parts that can be trained are the detection model of yolov8 and the reid used for tracking? Is there any other training content?

**Comment by mikel-brostrom** [comment]
Sorry for my late reply. Must have missed your question. 

> Are the only parts that can be trained are the detection model of yolov8 and the reid used for tracking? Is there any other training content?

Nope, only those two
