### ISSUE TITLE
Error when trying to use StrongSort tracker

### ISSUE THREAD

**Issue by wolfassi123** [mikel-brostrom/yolo_tracking#1347]
### Question

I noticed there are some differences with using the StrongSort tracker. First of all it inherits from `"object"` and not from the class `BaseTracker`. Second of all, it seems as if most of the functions found in the other trackers are not present in StrongSort. I also did not seem to find where the `self.active_tracks` are instantiated. Did I miss something when it comes to test StrongSort?

The error I got at infrence was the following:
```AttributeError: 'StrongSORT' object has no attribute 'plot_results' ```.
Anyone knows a quick fix for this?

This is the traceback:
```
Traceback (most recent call last):
  File "/content/yolo_tracking/tracking/track.py", line 172, in <module>
    run(opt)
  File "/usr/local/lib/python3.10/dist-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/content/yolo_tracking/tracking/track.py", line 103, in run
    img = yolo.predictor.trackers[0].plot_results(r.orig_img, args.show_trajectories)
```

Is there something different that I need to do with StrongSort or is there something missing?

**Comment by mikel-brostrom** [comment]
The tracker structure of StrongSORT is a bit different than the rest. So the results plotting is still not working for it

**Comment by wolfassi123** [comment]
> The tracker structure of StrongSORT is a bit different than the rest. So the results plotting is still not working for it

How can I check the results of the tracker then if it has a different algorithm? Is it documented anywhere?

**Comment by mikel-brostrom** [comment]
You can evaluate it using the MOT challenge compatible results in the case you have a dataset
