### ISSUE TITLE
ModuleNotFoundError: No module named 'tracking'

### ISSUE THREAD

**Issue by brainer3220** [mikel-brostrom/yolo_tracking#1352]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

I'v got the error.
```sh
Traceback (most recent call last):
  File "/content/yolo_tracking/tracking/track.py", line 15, in <module>
    from tracking.detectors import get_yolo_inferer
ModuleNotFoundError: No module named 'tracking'
```

### Environment

Google Colab

### Minimal Reproducible Example

```python
python tracking/track.py --yolo-model yolov8n       # bboxes only
python tracking/track.py --yolo-model yolo_nas_s    # bboxes only
python tracking/track.py --yolo-model yolox_n       # bboxes only
                                        yolov8n-seg   # bboxes + segmentation masks
                                        yolov8n-pose  # bboxes + pose estimation

```

**Comment by mikel-brostrom** [comment]
You probably just needed to `git pull` :smile:

**Comment by jansanw** [comment]
just try:


python3 tracking/track.py --yolo-model yolov8n       # bboxes only
python3 tracking/track.py --yolo-model yolo_nas_s    # bboxes only
python3 tracking/track.py --yolo-model yolox_n       # bboxes only
                                        yolov8n-seg   # bboxes + segmentation masks
                                        yolov8n-pose  # bboxes + pose estimation

**Comment by bgq666** [comment]
I also meet the error:  No module named 'tracking when i run python tracking/track.py --yolo-model yolov8s.pt
