### ISSUE TITLE
Basic Questions

### ISSUE THREAD

**Issue by akirs82** [mikel-brostrom/yolo_tracking#1359]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi there,
Great work in using the weak cues as they are often overlooked. I have few questions which I could not get clarity in the issues raised.
1. How to run only BoxMOT flow and what is its FPS ?
2. Can BOXMot work for fast actions like Fight actions say with 5-10 frames per second?
3. Can it run only with Detections and without Images ?
4. How about skipping detections in between ?
5. Comments about batched Inferences and across camera inferences with/without batching.

regards,
akirs

**Comment by mikel-brostrom** [comment]
> How to run only BoxMOT flow and what is its FPS ?

> Can BOXMot work for fast actions like Fight actions say with 5-10 frames per second?

> Can it run only with Detections and without Images ?

How to run this repo you will find in the readme. The FPS depends heavily on your underlaying hardware. If we isolate the trackers and only measure the update calculations on a low end CPU you will reach 500 FPS on BYTETRACK and OCSORT, up to 5 seconds 

> How about skipping detections in between ?

Use `--stride`

> Comments about batched Inferences and across camera inferences with/without batching.

Multi-caemra batching for ReID models is not supported atm
