### ISSUE TITLE
May I ask if this project supports multi target tracking under multiple cameras? How should it be used if supported?

### ISSUE THREAD

**Issue by kuaihuolinlim** [mikel-brostrom/yolo_tracking#1364]
### Search before asking

- [x] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

May I ask if this project supports multi target tracking under multiple cameras? How should it be used if supported?

**Comment by mikel-brostrom** [comment]
This feature is not openly available
