### ISSUE TITLE
IndexError in unfreeze Method When Tracking with DeepOCSort

### ISSUE THREAD

**Issue by YoungjaeDev** [mikel-brostrom/yolo_tracking#1369]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/99321359/3413fd0e-13bc-4e57-9b6c-e3a7cba9046b)

While running a tracking process on video files using the YOLO object detection and DeepOCSort tracking algorithm from the yolo_tracking repository, I encountered an IndexError in the deepocsort_kf.py script

### Environment

torch 2.1.2+cu118

### Minimal Reproducible Example

```bash
python tracking/track.py --yolo-model yolov8x --source /videos/ --imgsz 1280 --device 0 --save --classes 0 
```

**Comment by mikel-brostrom** [comment]
Which package version?

**Comment by YoungjaeDev** [comment]
> Which package version?

boxmot               10.0.62              /home/aicads/workspace/yolo_tracking

**Comment by mikel-brostrom** [comment]
What a nasty bug... Let's see it if it is fixed now 😄

**Comment by YoungjaeDev** [comment]
@mikel-brostrom 

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/99321359/539ff2b1-4811-4316-8227-6e789bddac14)

I updated the commit and reinstalled it, but the error does not appear in the video where the problem occurred, but now a similar error occurs in another video.

**Comment by mikel-brostrom** [comment]
Should be fixed. Let me know 😄

**Comment by YoungjaeDev** [comment]
@mikel-brostrom 

boxmot                   10.0.72              /home/aicads/workspace/yolo_tracking

When I used `deepocsort` and increased the max_age value in the configuration, such as 60 and 90, I got the same error once again
