### ISSUE TITLE
Logic of track removal in ByteTrack

### ISSUE THREAD

**Issue by Sujie1528** [mikel-brostrom/yolo_tracking#1373]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

What is the logic behind these lines: [https://github.com/mikel-brostrom/yolo_tracking/blob/4de7ea7bfdd124d7e0f6985f6d936e772de8324f/boxmot/trackers/bytetrack/byte_tracker.py#L244-L247](url)? The comment at Line 235 says "tracks with only one beginning frame" but I don't understand what is happening under the hood. Any explanations for this piece of code greatly appreciated!

**Comment by userkw** [comment]
@Sujie1528 can i ask you when i use this cmd line :
python tracking/track.py --tracking-method deepocsort
 I changed the parameter value, like min_hit, from 1 to 3 in the file deepocsort.yaml, but it doesn't seem to consider it. It's like I didn't change anything. Any help?
