### ISSUE TITLE
Where can we modify txt file in the code

### ISSUE THREAD

**Issue by Sarouch** [mikel-brostrom/yolo_tracking#1374]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello,
I would like to generate a csv file with tracking information, for that I searched the txt file code but it is not in the track.py code.
Could you please tell me, from where the save-txt args is obtained? 
Thanks in advance.

PS: --save-mot does not exist anymore, you can delete it from Readme.

**Comment by anaxsouza** [comment]
Im also interested on it, did you find any solution?

**Comment by Sarouch** [comment]
> Im also interested on it, did you find any solution?

@anaxsouza not yet, wondering if @mikel-brostrom can help please.

**Comment by mikel-brostrom** [comment]
Check `evaluation` under https://github.com/mikel-brostrom/yolo_tracking/blob/master/README.md#yolov8--yolo-nas--yolox-examples. Tracking, visualizing and plotting in real-time while generating the MOT results is too time consuming hence I deleted that option. I now deleted this part from the README as well 😄

**Comment by Sarouch** [comment]
> Check `evaluation` under https://github.com/mikel-brostrom/yolo_tracking/blob/master/README.md#yolov8--yolo-nas--yolox-examples. Tracking, visualizing and plotting in real-time while generating the MOT results is too time consuming, hence I deleted that option. I now deleted this part from the README as well 😄

@mikel-brostrom Thank you, but I tried this code but I don't know which source are you talking about? I have this error ? what should we make in --source ? a path of what please? 

Traceback (most recent call last):
  File "tracking/generate_dets_n_embs.py", line 180, in <module>
    mot_folder_paths = [item for item in Path(opt.source).iterdir()]
  File "tracking/generate_dets_n_embs.py", line 180, in <listcomp>
    mot_folder_paths = [item for item in Path(opt.source).iterdir()]
  File "C:\Users\anaconda3\envs\boxmot\lib\pathlib.py", line 1122, in iterdir
    for name in self._accessor.listdir(self):
FileNotFoundError: [WinError 3] Le chemin d’accès spécifié est introuvable: '0'
