### ISSUE TITLE
Dynamic threshold adjustment

### ISSUE THREAD

**Issue by 050603** [mikel-brostrom/yolo_tracking#1395]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

What if I want to perform different tracking parameters for certain specific areas of the video compared to other areas?
For example, when tracking an object, when entering a certain coordinate area, tracking interruption often occurs. Therefore, parameter a is implemented in this area, and default parameter B is executed when the object moves out of that area.
Can this function be implemented?

**Comment by mikel-brostrom** [comment]
Not in my roadmap 😄
