### ISSUE TITLE
Why can't I reproduce the evaluation results mentioned in the README?

### ISSUE THREAD

**Issue by Victoire7** [mikel-brostrom/yolo_tracking#1396]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thank you for your outstanding work. Why is my evaluation result of using the yoloxm model with default settings on MOT17 lower by 20 points compared to the results shown in the readme?
![2024-04-02 11-14-11 的屏幕截图](https://github.com/mikel-brostrom/yolo_tracking/assets/137769152/d5fc5838-2d2f-4dc9-baba-7fdd02f39d5c)

**Comment by Victoire7** [comment]
> As noted in the README the evaluations are performed on the first 10 frames of each sequence.
I used the first 10 frames of the following sequences from MOT17 for evaluation, but the results are still significantly different from the ones mentioned in the README.
![2024-04-02 16-32-21 的屏幕截图](https://github.com/mikel-brostrom/yolo_tracking/assets/137769152/847e2f42-96ef-4f6f-8eef-15083aeb38c4)

**Comment by mikel-brostrom** [comment]
Did you use YoloXm as detector @Victoire7
