### ISSUE TITLE
AttributeError: 'StrongSORT' object has no attribute 'plot_results'

### ISSUE THREAD

**Issue by Hemilibeatriz** [mikel-brostrom/yolo_tracking#1398]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

When i run python tracking/track.py --tracking-method strongsort --source ../person.mp4
I get this error: img = yolo.predictor.trackers[0].plot_results(r.orig_img, args.show_trajectories)
AttributeError: 'StrongSORT' object has no attribute 'plot_results'

What´s wrong here?

### Environment

boxmot @ file:///C:/Users/hemil/Desktop/yolo_tracking
plotly==5.20.0
pluggy==1.4.0
poetry==1.8.2
poetry-core==1.9.0
poetry-plugin-export==1.7.1
torch==2.2.1+cpu
torchvision==0.17.1+cpu
tqdm==4.66.2
python==3.9.0

### Minimal Reproducible Example

python tracking/track.py --tracking-method strongsort --source ../person.mp4

**Comment by dulindulindulin** [comment]
I also have the same problem

**Comment by mikel-brostrom** [comment]
Not available for StrongSORT as stated here: https://github.com/mikel-brostrom/yolo_tracking#news

**Comment by chensonglu** [comment]
same problem
