### ISSUE TITLE
--save--id-crops, doesn´t works with hybridsort?

### ISSUE THREAD

**Issue by Hemilibeatriz** [mikel-brostrom/yolo_tracking#1400]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

When i run the code bellow, I don´t get any errors, but don´t have the crops. Just txt and video files.
```
>python tracking/track.py --yolo-model yolov8n --tracking-method hybridsort --source ../person.mp4 --show --save --cl
asses 0 --save-txt --save-id-crops

```
### Environment

Don´t apply

### Minimal Reproducible Example

Don´t apply

**Comment by mikel-brostrom** [comment]
It got removed together with the MOT results saving as the evaluation got a more versatile way of working 😄. But I can bring it back if needed 👍

**Comment by Hemilibeatriz** [comment]
Got it! If you can... I really appreciate it 😄
