### ISSUE TITLE
Is there a way to turn of camera movement correction (cmc)?

### ISSUE THREAD

**Issue by AlexanderNevarko** [mikel-brostrom/yolo_tracking#1404]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am using your wonderful tracking tool for tracking people from static surveillance cameras. I use `BoTSort` algorithm, which has `SOF` method for camera movement correction built in. As far as I understood reading the source code, it detects strong ORB keypoints and matches them from frame to frame to correct detections based on camera movement. It takes processing time and for static cameras it is useless. 
Furthermore, static cameras usually have OSD on frames (date and time, written on some corner of the frame). The characters from this OSD may also affect CMC, which can result in worse tracking performance. As for now I haven't seen the ability to turn off the CMC, but in my case it will be very useful!
Thanks for your awesome work!

**Comment by mikel-brostrom** [comment]
There is no toggle flag for this at the moment. But if you are working with BoTSORT you could simply delete these lineS OF code:

https://github.com/mikel-brostrom/yolo_tracking/blob/d079d3d03ddee639705edb2bbead373df0a82fe4/boxmot/trackers/botsort/bot_sort.py#L303-L305

**Comment by AlexanderNevarko** [comment]
Thanks!
Let me check the usage of cmc in other trackers and may be submit a PR. Is it going to be useful?

**Comment by mikel-brostrom** [comment]
A toggler for CMC would be nice IMO 😄
