### ISSUE TITLE
when to support rt-detrt as a detector , as it is better than yolo

### ISSUE THREAD

**Issue by darrenlei123** [mikel-brostrom/yolo_tracking#1406]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

when to support rt-detrt as a detector , as it is better than yolo

### Use case

when to support rt-detrt as a detector , as it is better than yolo

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Sorry, but there is no RT-DETR pip package and I am not using submodules in this repo 😄

**Comment by mikel-brostrom** [comment]
Yup, there you have Ultralytics' version of it. So that one may be enough for you @darrenlei123  😄

**Comment by darrenlei123** [comment]
thank @AlexanderNevarko and @mikel-brostrom  very much, I will have a try in later, best wishes to you .
