### ISSUE TITLE
How to apply tracking methods into 3d pointcloud detection?

### ISSUE THREAD

**Issue by mx2013713828** [mikel-brostrom/yolo_tracking#1407]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Thanks for your great work!
I just want to apply object track in 3d pointcloud detection,and I have searched github but found no valueable repo.
I think you can give me some advices to learn how to using tracking methods into 3d lidar detection.

**Comment by mikel-brostrom** [comment]
This would require a substantial amount of work. So first of all your detections would be 3D bboxes. You would need to extend the KF to 3D space. And some association methods as IoU from 2D to 3D

**Comment by mx2013713828** [comment]
> This would require a substantial amount of work. So first of all your detections would be 3D bboxes. You would need to extend the KF to 3D space. And some association methods as IoU from 2D to 3D

Thanks for your reply!!!
yes,I have 3d bboxes result. Your suggestion is very helpful, I will try from scratch. I think i should start from KF~ .
