### ISSUE TITLE
Dockerfile reference incorrect git branch

### ISSUE THREAD

**Issue by micat001** [mikel-brostrom/yolo_tracking#1413]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Other

### Bug

The dockerfile runs this line: `RUN git clone https://github.com/mikel-brostrom/yolo_tracking.git -b main /usr/src/boxmot` but there is no `main` branch, just `master`. 

### Environment

N/A.

### Minimal Reproducible Example

`docker build -t mikel-brostrom/yolov5_strongsort_osnet .`
```bash
 => ERROR [4/7] RUN git clone https://github.com/mikel-brostrom/yolo_tracking.git -b ma  0.8s
------
 > [4/7] RUN git clone https://github.com/mikel-brostrom/yolo_tracking.git -b main /usr/src/boxmot:
0.399 Cloning into '/usr/src/boxmot'...
0.699 fatal: Remote branch main not found in upstream origin
------
Dockerfile:14
```

**Comment by micat001** [comment]
Simple fix by main -> master (or fixing the repo to change master -> main).

**Comment by mikel-brostrom** [comment]
Thanks for pointing this out! Updated now 😄
