### ISSUE TITLE
How to evaluate the VisDrone dataset using YOLOv5 and ByteTrack

### ISSUE THREAD

**Issue by Czeni1** [mikel-brostrom/yolo_tracking#1420]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Author, I'm very sorry to bother you. I'm using yolo tracking8.0 and the tracker uses ByteTrack without REID. After running the track.py file, I wanted to see how the tracking performance works. However, I ran val.py again and a new val_utils file appeared. I want to know what this function is and how can I evaluate the performance of the VisDrone dataset? Looking forward to your answer, thank you very much!
<img width="231" alt="3b738c79ccc759337e42ee2056e8125" src="https://github.com/mikel-brostrom/yolo_tracking/assets/152961525/c2957489-2219-4887-a28a-d3d41a0cdee4">

**Comment by mikel-brostrom** [comment]
Check evaluation under: https://github.com/mikel-brostrom/yolo_tracking?tab=readme-ov-file#yolov8--yolo-nas--yolox-examples

**Comment by Czeni1** [comment]
> 检查评估下：https://github.com/mikel-brostrom/yolo_tracking?tab=readme-ov-file#yolov8--yolo-nas--yolox-examples

Thank you for your reply, but I would like to ask why ByteTrack can only run one video instead of the entire test set in the dataset?
Looking forward to your reply！
<img width="617" alt="c95882036dcf5d4d37e76a79d54d65a" src="https://github.com/mikel-brostrom/yolo_tracking/assets/152961525/f7d81ca0-de0b-43cd-bdec-c91afa781ea9">
