### ISSUE TITLE
How to use YOLOX as the detector for evaluation?

### ISSUE THREAD

**Issue by yaoshanliang** [mikel-brostrom/yolo_tracking#1422]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

`generate_dets_n_embs.py` seems to use yolov8 as the detector as the YOLO() method is from ultralytics repository.
When I pass a YOLOX model for the `--yolo-mode` parameter, no results are shown in dets and embs folders. The **results** in line 80 is generated from the yolov8n.pt in line 31.

**Comment by yaoshanliang** [comment]
@mikel-brostrom Help me. Have you tried using official YOLOX as the detector? Thanks a lot.

**Comment by mikel-brostrom** [comment]
You can take inspiration from `track.py`. `track.py` can run yolox. I would be more than happy to review a PR for this. I just don't have time at the moment for major changes.

**Comment by yaoshanliang** [comment]
@mikel-brostrom I just tried track.py. However, no results are detected. I am sure that the trained weight file is successful using official validation script, and can get the detection results.

**Comment by mikel-brostrom** [comment]
The default ByteTrack Crowdhuman weights run without problem...
