### ISSUE TITLE
Illegal instruction (core dumped) for BoTSORT

### ISSUE THREAD

**Issue by MABatin** [mikel-brostrom/yolo_tracking#1432]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Hi, I'm trying to integrate the BoTSORT tracker for tracking in my program. Running the given example (Minimal Reproducible Example) I get the error `Illegal instruction (core dumped)`
If I swap out the tracker for OCSORT, I don't get the error. What might be the issue?

### Environment

- YOLO tracking v10.0.72, torch 2.2.2+cpu (intel core i5 8th gen laptop cpu)
I have also tried torch 1.13.1+cpu

### Minimal Reproducible Example

```
tracker = BoTSORT(
            model_weights=None,
            device=torch.device(self.device),
            fp16=False,
            with_reid=False
        )
while not self.camera.stopped:
    frame = self.camera.read()
    r = next(face_model(frame, stream=True, **kwargs))
    dets = r.boxes.data.cpu().numpy()
    tracked_dets = tracker.update(
                                dets, frame
                            )  # --> M X (x, y, x, y, id, conf, cls, ind)
```

**Comment by MABatin** [comment]
> Provide the full error please

![image](https://github.com/mikel-brostrom/yolo_tracking/assets/56408528/0b5d5763-dfae-419f-be06-ccfd59abce17)
I get this error only, no full traceback. I've tried to following block of code to print traceback of error but it still doesn't print full traceback:
```
try:
    tracked_dets = tracker.update(
                                    dets, frame
                                )  # --> M X (x, y, x, y, id, conf, cls, ind)
except Exception:
    print(traceback.format_exc())
```

**Comment by mikel-brostrom** [comment]
Sorry. I cannot help you with this little information. Try:

import traceback

```py
try:
    # Simulating your tracking update function call
    # Assuming 'tracker.update' is a function that might throw an exception
    # Replace 'dets' and 'frame' with actual data that you pass to the function
    tracked_dets = tracker.update(dets, frame)  # --> M X (x, y, x, y, id, conf, cls, ind)
except Exception as e:
    # This prints the error message and the complete traceback
    print("An error occurred:", e)
    print(traceback.format_exc())
```
