### ISSUE TITLE
How to train custom Reid dataset from scratch on yolo_tracking? 

### ISSUE THREAD

**Issue by deel789** [mikel-brostrom/yolo_tracking#1445]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I want to achieve multi-obejct tracking on a custom new dataset. Therefore, I need to start training the object detector and reid for getting appropriate weights. The code provides ready-made weight links, and I can train the target detector, but I don't know how to train the reid. It seems that the training on Reid in the code of yolo_tracking is not complete.

**Comment by yaoshanliang** [comment]
@deel789 same question

**Comment by jmavasa** [comment]
I am also interested in the answer or some pointer  to the right resources. custom trained my yolox model , when using those weights and osnet_x0_25_msmt17.pt  nothing is  detected or tracked.
