### ISSUE TITLE
Inquiry regarding liscence

### ISSUE THREAD

**Issue by Howardlei123** [mikel-brostrom/yolo_tracking#1446]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi ! I am a University Student. I found your code is really useful. I have git cloned your project and modified the track.py file for my own project use. Is this allowed? Do I have to make my repository public? Thank you!

**Comment by mikel-brostrom** [comment]
Very small modification usually do not fall under this license 😄 

https://github.com/mikel-brostrom/yolo_tracking/blob/4f4cefd2dbee6d813bb7b4a83b3931c7b7e55d87/LICENSE#L32-L35
