### ISSUE TITLE
Retrain ReID

### ISSUE THREAD

**Issue by 1437940802** [mikel-brostrom/yolo_tracking#1462]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I found that in the project there is only a pedestrian ReID model, if I want to track other types of objects, I need to retrain a ReID model, how can I train it?

**Comment by mikel-brostrom** [comment]
Here you will find some good resources:

https://github.com/FanChiMao/Competition-2024-PyTorch-Tracking?tab=readme-ov-file#%EF%B8%8F-train-on-scratch
