### ISSUE TITLE
Minimum number of hits quesiton

### ISSUE THREAD

**Issue by IbrahimAlmasri01** [mikel-brostrom/yolo_tracking#1463]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, 
I have a question regarding the concept of min number of hits. 
How does it work? 

What I have understood is this:
the object will be detected lets say 5 times and each time its going to be tracked , if the tracking reached 4 times (assuming number is 4) is it going to start sowing me the detections ? 

Thanks

**Comment by mikel-brostrom** [comment]
Yes. It will be considered as a confirmed track then and the tracker will start outputting it 😄
