### ISSUE TITLE
Why ReID improves HybridSORT performance

### ISSUE THREAD

**Issue by fenguan** [mikel-brostrom/yolo_tracking#1470]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hello, may I ask if the improvement effect of ReID is due to the use of more advanced ReID or what is the reason. I want to join my method. thanks

**Comment by fenguan** [comment]
My confusion lies in the fact that recent methods such as bytetrack and ocsort do not seem to have ReID. Is it because the effect has deteriorated due to the addition of ReID

**Comment by mikel-brostrom** [comment]
The use of ReID or not, has to do with execution time.

- With ReID --> Slower execution time
- Without ReID --> Faster execution time

**Comment by fenguan** [comment]
Therefore, is the processing method to add the cost matrices of IOU and REID, and multiply REID by a coefficient?

**Comment by mikel-brostrom** [comment]
You need to check each tracker for the details :smile:
