### ISSUE TITLE
tracking of HybridSORT when moving to the next part of the video

### ISSUE THREAD

**Issue by vadfq** [mikel-brostrom/yolo_tracking#1472]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I have used HybridSORT with InsightFace for tracking faces. I applied them to an edited YouTube video. HybridSORT maintains track IDs better than other trackers, but when moving to the next part of the video, it still keeps track IDs even though the locations of the faces change. Additionally, the IDs point to different faces than before.

May I know how to assign new track IDs when moving to the next part of the video, or how to maintain track IDs without changing the tracked object?

![캡처1](https://github.com/mikel-brostrom/yolo_tracking/assets/138349650/a8bf0e9f-1690-4fee-9f60-29e416b5c30b)
![캡처2](https://github.com/mikel-brostrom/yolo_tracking/assets/138349650/87ec0cad-9cd4-43a1-81d8-f42aba592e3b)

**Comment by mikel-brostrom** [comment]
You would need to identify key frames in your videos. One simple but yet effective way of doing this is by calculating the difference between consecutive frames and detect when this difference exceeds a certain threshold.
