### ISSUE TITLE
IndexError Occurs When max_age is Set Above 60

### ISSUE THREAD

**Issue by YoungjaeDev** [mikel-brostrom/yolo_tracking#1480]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking, Evolution

### Bug

hello,

I had a similar [issue](https://github.com/mikel-brostrom/yolo_tracking/issues/1369) a while back

I have no problem when I set the max_age parameter to 30, but when I go beyond 60, either by performing the evolve function or by modifying the tracker yaml directly, I get the following error:

```bash
  File "/home/aicads/workspace/yolo_tracking/tracking/generate_mot_results.py", line 168, in run_generate_mot_results
    generate_mot_results(opt)
  File "/home/aicads/workspace/yolo_tracking/tracking/generate_mot_results.py", line 78, in generate_mot_results
    tracks = tracker.update(dets, im, embs)
  File "/home/aicads/workspace/yolo_tracking/boxmot/utils/__init__.py", line 81, in wrapper
    tracks = self.update(instance, dets, im)
  File "/home/aicads/workspace/yolo_tracking/boxmot/trackers/deepocsort/deep_ocsort.py", line 485, in update
    self.active_tracks[trk_ind].update(dets[det_ind, :])
  File "/home/aicads/workspace/yolo_tracking/boxmot/trackers/deepocsort/deep_ocsort.py", line 235, in update
    self.kf.update(self.bbox_to_z_func(bbox), R=R)
  File "/home/aicads/workspace/yolo_tracking/boxmot/motion/kalman_filters/deepocsort_kf.py", line 528, in update
    self.unfreeze()
  File "/home/aicads/workspace/yolo_tracking/boxmot/motion/kalman_filters/deepocsort_kf.py", line 442, in unfreeze
    index1 = indices[-2]
IndexError: index -2 is out of bounds for axis 0 with size 
```

My suspicion is that the problem is caused by the insufficient length of the indices array required by the Kalman filter's update process. Specifically, setting the max_age value above 60 seems to cause the error because the indices array is not long enough.

I also believe that the problem is likely caused by the fact that variables like history are limited to a length of 50, and this limit seems to be affecting the ability to retain enough historical state information as max_age increases.

I would appreciate it if you could look into this issue.

Thank you.

### Environment

boxmot  10.0.72

### Minimal Reproducible Example

```bash
Trial 16 failed with parameters: {'conf': 0.4266284948010711, 'det_thresh': 0, 'max_age': 60, 'min_hits': 4, 'iou_thresh': 0.24388418277590976, 'delta_t': 5, 'asso_func': 'giou', 'inertia': 0.18741675196890667, 'w_association_emb': 0.5060212238689145, 'alpha_fixed_emb': 0.9259561635650133, 'aw_param': 0.5662470182020077, 'embedding_off': True, 'cmc_off': False, 'aw_off': True, 'new_kf_off': False} because of the following error: IndexError('index -2 is out of bounds for axis 0 with size 1').
```

**Comment by mikel-brostrom** [comment]
I just implemented dynamic deques based on max_age here:

https://github.com/mikel-brostrom/yolo_tracking/pull/1481

Should be fixed. Let me know 😄
