### ISSUE TITLE
How to get every frame of the video

### ISSUE THREAD

**Issue by jayer95** [mikel-brostrom/yolo_tracking#193]
Hi, I appreciate your project.

Can you please tell me how to get every frame of the video and output it?

I also want to ask you how to crop and output the ROI of the bbox output with different IDs!

for example:

inference/output/car1.jpg
inference/output/car2.jpg

I need some hints and keywords, thank you.

**Comment by mikel-brostrom** [comment]
Use the output bounding boxes to crop the image and place the cropped images in individual folders based on their respective class and id
