### ISSUE TITLE
Cost_matrix is every large

### ISSUE THREAD

**Issue by wcyjerry** [mikel-brostrom/yolo_tracking#453]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I have trained yolo5 on my customer datasets, and I use a pretrain model of resnet50 to do feature extractor,
but the tracking of some obj always lost while the detection is good enough.
My datasets is like 1 frame per second, so maybe the variance between two frames is a little big but some obj's tracking is good, 
I check the cost_matrix, and find the gate_distance calculated by kf is every large between the same obj of two frames, 
I think that's how tracking lost happens.
![微信图片_20220712003010](https://user-images.githubusercontent.com/48686306/178312895-c176b9ff-53f9-455d-ae0a-787301f52157.png)
actually the biggest one [0,3] is the correct match.
Do u have any suggestions for this?

**Comment by mikel-brostrom** [comment]
It the FPS = 1. Then the motion uncertainty is for sure high. Try lowering:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/c0f3a1f453134c1bf5e769cabdc55222d50b6ac6/strong_sort/configs/strong_sort.yaml#L5

and

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/c0f3a1f453134c1bf5e769cabdc55222d50b6ac6/strong_sort/configs/strong_sort.yaml#L6

Let me know if this works for you

**Comment by q671383789** [comment]
@mikel-brostrom  
It's not improve much actually, but we have fix it more or less. We use other matching stratiges such as 
1. if there is only one obj for one class we assume its just the same the one in a sequence
2. we using diou and the distance of bbox'center point and other features to assist the match 
But thx a lot.
