### ISSUE TITLE
Re-id model format for strongSORT and botSORT

### ISSUE THREAD

**Issue by Sumant-Gosi** [mikel-brostrom/yolo_tracking#743]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello,

I am trying to reporduce the tracking for my custom video. 
I am able to reproduce results with ocsort and bytetrack. But, for strongSORT and botSORT, I need the re-id models. But the re-id models in the zoo are in .pth format. But however, .pth models seems not to be supported. So, do I need to convert it into .pt or .engine and then try ?

Am I getting it correct ?

Could you please explain what is it about ?

**Comment by Sumant-Gosi** [comment]
I just renamed it from .pth to .pt

**Comment by mikel-brostrom** [comment]
You can just rename the extension from `.pth` to `.pt`. That is all you need
