### ISSUE TITLE
StrongSORT not generating any output

### ISSUE THREAD

**Issue by skamano** [mikel-brostrom/yolo_tracking#746]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

StrongSORT is not generating any output.

### Bug

I am trying to use strongSORT but I am not getting any output for my video:
```
python track.py --source ~/Downloads/test.mp4   --save-vid  --show-vid --device cpu --iou-thres 0.9 --conf-thres 0.2  --yolo-weights yolov8n-seg.pt  --tracking-method strongsort --tracking-config trackers/strongsort/configs/strongsort.yaml
```
Here is some output from the model:
```
video 1/1 (1/281) ~/Downloads/test.mp4: 736x1280 74 persons, 1 horse, 6855.4ms
video 1/1 (2/281) ~/Downloads/test.mp4: 736x1280 79 persons, 3 motorcycles, 1 horse, 7429.4ms
```
The yolo detection is clearly working. It's this specific tracker update step here https://github.com/mikel-brostrom/yolov8_tracking/blob/master/track.py#L222 that is generating an empty list as output which prevents any bounding boxes or masks from being drawn at all.

I have tried the above command using ByteTrack and OCSort and both of these methods work. However I wanted to use StrongSORT because it seemed the most promising of the three trackers. Is StrongSORT GPU-only?

### Environment

MacOS, CPU

### Minimal Reproducible Example

follow README of this repo

**Comment by mikel-brostrom** [comment]
It is very hard to help any of you out with this problem without a video example of what you are trying to track. Usually, when tracking is failing it is due to a very low frame-rate which causes the KF to undershoot. This causes the association process to fail as it is largely based on IoU.

**Comment by mikel-brostrom** [comment]
This has most certainly to do with the KF configuration. We are looking into bringing automated KF tuning

**Comment by henriksod** [comment]
Hi, can you print the number of tracks while running strongsort?

On line 73 in trackers/strongsort/strong_sort.py, add:
`print(len(self.tracker.tracks))`
