### ISSUE TITLE
Facing occlusion  issue for some objects

### ISSUE THREAD

**Issue by aarushi-sahu** [mikel-brostrom/yolo_tracking#789]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Hello @mikel-brostrom,

The shared work proved useful in resolving my issue with multiple Object id allocation while using the SORT tracking algorithm. However, I have noticed that some objects are being occluded and in a few cases, multiple object IDs are being assigned to the same object. To address this, I have experimented with the Byte tracking algorithm using the yolov8x weight to track pedestrians in a dashcam video. 

I would appreciate any suggestions on how to improve the accuracy of my tracking or if any similar approaches could help me resolve this issue. My work specifically involves efficiently tracking cars and pedestrians in dashcam videos.

**Comment by aarushi-sahu** [comment]
> Try `deepocsort`. It is more robust for cases with heavy occlusion

Hello @mikel-brostrom,
 
Thank you for the reply. I tried deepocsort method for tracking. It resolved the occlusion issue to a great extent but for some objects, the object id is not matching and generating new ids for a single object.  In simple words, the object id for an object is changing(specifically in an occluded case) instead of keeping the same after some frames. 

Please let me know if there is any way to fix this.

**Comment by mikel-brostrom** [comment]
I may be solved by making multiple predictions ahead with the KFs in the case the occlusions occurs for longer periods of time
