### ISSUE TITLE
Bad tracking results on slow/fast moving birds (high motion uncertainty)

### ISSUE THREAD

**Issue by flo-crn** [mikel-brostrom/yolo_tracking#839]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

For the purpose of my internship, I want to use detection+deepsort to detect and track birds on massive nests which are a cryptic background.
To do so, I trained yolov5 and yolov8 on my custom data. I will have to make justified choices about parameters/ version...
Then I wanted to use the deepsort algorithm to track them.
I have some question about this use :
- yolov5l seems to be a little more efficient than yolov8l when using deepsort. What could explain this ?
- since the birds have "random" moves while building their nest, I think it is harder for deepsort to re-identify them along the video, so I have too much IDs at the end. I tried to play with the different deepsort params (max_age, iou_thres, min_hits), but I still a little confused about the right things to change.
Do you have any ideas or advices that I can test ?

**Comment by mikel-brostrom** [comment]
> yolov5l seems to be a little more efficient than yolov8l when using deepsort. What could explain this ?

This is a question for the Yolov8 official repo

> since the birds have "random" moves while building their nest, I think it is harder for deepsort to re-identify them along the video, so I have too much IDs at the end. I tried to play with the different deepsort params (max_age, iou_thres, min_hits), but I still a little confused about the right things to change. Do you have any ideas or advices that I can test ? 

First of all I would recommend using DeepOCSORT. It has a KF which is more robust to non-linear motion.

**Comment by mikel-brostrom** [comment]
So you are using deepocsort? What is the FPS on your videos/camera feeds?

**Comment by mikel-brostrom** [comment]
Could you drop a video example here so that we can help you better?

**Comment by flo-crn** [comment]
I am sorry but the 10Mo size limit doesn't allow me to drop any video I have (even 5sec). So here is a frame extracted from the tracking output, so you can see the context. Please note that the birds are hopping and going back and forth. In this extract, the second bird is not detected (on the right of the red one), even if it is not blurred on another frame

![Capture d’écran 2023-05-04 102241](https://user-images.githubusercontent.com/84318052/236150253-1e8bf009-4dff-4673-9d66-7e037383d865.png)

**Comment by mikel-brostrom** [comment]
So the birds are not visible in the field of view of the camera when they enter the nest? That's a hard case. The tracks have a maximum life time (https://github.com/mikel-brostrom/yolov8_tracking/blob/df3c76042eec69230c109ca8265728b51d24a111/trackers/deepocsort/configs/deepocsort.yaml#L10), after that, when accepted as a new track they will get a completely different ID.

**Comment by flo-crn** [comment]
> So the birds are not visible in the field of view of the camera when they enter the nest? That's a hard case. The tracks have a maximum life time (
> 
> https://github.com/mikel-brostrom/yolov8_tracking/blob/df3c76042eec69230c109ca8265728b51d24a111/trackers/deepocsort/configs/deepocsort.yaml#L10
> 
> ), after that, when accepted as a new track they will get a completely different ID. Even if it would manage to re-assign it correctly the previous motion information could confuse the tracker if a sudden motion change is there.

Indeed, if the bird isn't detected directly when it arrives is not a big proble, we are aware that it is complex. But when the bird is visible sometimes the ID changes if the movement is to fast (for exemple a bigger hop). I tried to play with the max age, the min hits and the iou threshold but I was wondering how the tracking algorithm is dealing with theses "random" mooves (in comparision with cars video). Maybe I should raise the max age ?

**Comment by mikel-brostrom** [comment]
The KF may be to slow to react to the sudden motion change. A tuning for you specific use-case may be needed

**Comment by flo-crn** [comment]
> The KF may be to slow to react to the sudden motion change. A tuning for you specific use-case may be needed

Thank you for your answers, do you have any ideas of what remplacement of KF I can investigate ?

**Comment by lynxhawk** [comment]
My project is to track fish with an underwater camera, and I have a similar problem 😭

**Comment by mikel-brostrom** [comment]
First you need to investigate what is going on. Plot the predicted bboxes in order to understand how the KF is behaving. Then you can proceed with the tuning from there

**Comment by lynxhawk** [comment]
> First you need to investigate what is going on. Plot the predicted bboxes in order to understand how the KF is behaving. Then you can proceed with the tuning from there

I'm sorry but I don't know exactly how to fine-tune and where to change it.

**Comment by mikel-brostrom** [comment]
Here you have a few things you can try: https://github.com/mikel-brostrom/yolov8_tracking/discussions/886#discussioncomment-5959280

**Comment by mikel-brostrom** [comment]
If non of this works you will need to start looking into adaptive KFs. This is because in this scenario (and in many other real-world scenarios) the dynamics of the system may change over time or be uncertain (for example from fast motion to slow, or viceversa). An adaptive Kalman filter addresses this limitation by adapting its model parameters based on the available measurements, allowing it to track changing system dynamics more effectively. I wish you the best of lucks with this endeavour. :smile:.

**Comment by lynxhawk** [comment]
To be honest, I am not very clear about the specific steps and codes of Kalman filtering. I am still learning. Thank you for your suggestions. I will reply you if there is any progress in the future ~

**Comment by mikel-brostrom** [comment]
I am planing to implement this at some point. But cannot give you a date, I have a lot of other prios for this repo.

**Comment by flo-crn** [comment]
Thank you for your time, I will see what I can do with this !
