### ISSUE TITLE
architecture diagram

### ISSUE THREAD

**Issue by gokselozgur5** [mikel-brostrom/yolo_tracking#876]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I am looking for the software architecture diagram of the project but could not found. Is there any providable software architecture diagram?

**Comment by mikel-brostrom** [comment]
Not available at the moment but could provide it. I will need some weeks for this I have other priorities for this repo

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/wiki/Very-basic-yolo-tracking-architecture-diagram

**Comment by mikel-brostrom** [comment]
Feel free to leave some feedback :smile:
