### ISSUE TITLE
How to Remove Class Name Visualization from Tracking Result Video

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/yolo_tracking#878]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

I am having trouble removing the class name visualization part from the tracking result video. The output video result contains the class name from the YOLOv8 detection. I would like to only show the tracking ID in the video. Do you have any suggestions?

**Comment by mikel-brostrom** [comment]
Some features are still not there after the last big refactor. I am working on getting them back ASAP. Than you for reporting this one.

**Comment by mikel-brostrom** [comment]
Sorry, but this is not even working in the Ultralytics repo. So won't do for now
