### ISSUE TITLE
UnboundLocalError: local variable 'seq_paths' referenced before assignment

### ISSUE THREAD

**Issue by promisechen666** [mikel-brostrom/yolo_tracking#879]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Bug

an error happened when I run ：python val.py --yolo-model WEIGHTS/yolov8n.pt --benchmark MOTCUSTOM --reid-model WEIGHTS/mobilenetv2_x1_4_dukemtmcreid.pt  --tracking-method deepocsort

val: yolo_model=WEIGHTS/yolov8n.pt, reid_model=WEIGHTS/mobilenetv2_x1_4_dukemtmcreid.pt, tracking_method=deepocsort, name=exp, project=runs/val, exists_ok=False, benchmark=MOTCUSTOM, split=train, eval_existing=, conf=0.45, imgsz=[1280], device=[''], processes_per_device=2
Eval repo already downloaded
Traceback (most recent call last):
  File "val.py", line 353, in <module>
    e.run(opt)
  File "val.py", line 302, in run
    seq_paths, save_dir, MOT_results_folder, gt_folder = e.eval_setup(opt, val_tools_path)
  File "val.py", line 140, in eval_setup
    return seq_paths, save_dir, MOT_results_folder, gt_folder
UnboundLocalError: local variable 'seq_paths' referenced before assignment

**Comment by mikel-brostrom** [comment]
Thanks for reporting this. Will have a look at it tomorrow 😊

**Comment by mikel-brostrom** [comment]
Should be fixed! Please let me know if it works for you :smile:
