### ISSUE TITLE
Can these algorithms only track moving objects and skip static objects?

### ISSUE THREAD

**Issue by segmentorTang** [mikel-brostrom/yolo_tracking#884]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

Can these algorithms only track moving objects and skip delicate objects?

**Comment by segmentorTang** [comment]
I realized this function simply, and now I want to add to the code that can distinguish objects taken out of the screen and the objects put into the screen，similar to smart container. Could you please give me some code suggestion? Thank you so much

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/594#issuecomment-1310624465
