### ISSUE TITLE
Issue with using val.py to evaluate a custom dataset

### ISSUE THREAD

**Issue by mesllo-bc** [mikel-brostrom/yolo_tracking#889]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

So I followed the instructions on formatting an MOT-compliant dataset using this [doc](https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) and tried to run val.py with a default setup. I kept getting the following output:

```
MotChallenge2DBox Config:
PRINT_CONFIG         : True                          
GT_FOLDER            : val_utils/data/foo/test
TRACKERS_FOLDER      : /home/foo/repos/yolov8_tracking/val_utils/data/trackers/mot_challenge/
OUTPUT_FOLDER        : None                          
TRACKERS_TO_EVAL     : ['foo']                
CLASSES_TO_EVAL      : ['pedestrian']                
BENCHMARK            : foo                    
SPLIT_TO_EVAL        : train                         
INPUT_AS_ZIP         : False                         
DO_PREPROC           : True                          
TRACKER_SUB_FOLDER   : exp4/data                     
OUTPUT_SUB_FOLDER    :                               
TRACKER_DISPLAY_NAMES : None                          
SEQMAP_FOLDER        : None                          
SEQMAP_FILE          : None                          
SEQ_INFO             : {'foo-42': None, 'foo-41': None}
GT_LOC_FORMAT        : {gt_folder}/{seq}/gt/gt.txt   
SKIP_SPLIT_FOL       : True                          
Tracker file not found: /home/foo/repos/yolov8_tracking/val_utils/data/trackers/mot_challenge/foo/exp4/data/foo-42.txt

Traceback (most recent call last):
  File "val.py", line 356, in <module>
    e.run(opt)
  File "val.py", line 307, in run
    writer.add_scalar('HOTA', combined_results['HOTA'])
KeyError: 'HOTA'
```

After some research in the issues, I then discovered that we should put the dataset under `val_utils` where I had to manually create the `data` folder and store it under there. The problem is that I still get the same above error and at this point I'm not sure what I'm doing wrong. I understand that the tracker file is not listed under there which is why I get the tracker file not found error, however, I'm not sure what I have to change so that this is corrected. Could you kindly suggest what I need to do please? Thank you.

**Comment by mikel-brostrom** [comment]
You can now select the folder result to evaluate on, by using the `--project` and `--name` flag when `--eval-existing`

**Comment by mesllo-bc** [comment]
What if we want to evaluate from scratch though? My folder does not contain the labels folder, it has the `gt` and `img1` folders as instructed [here](https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) and I thought we could then generate the HOTA results by simply running the command as below

`python val.py --yolo-weights <my_custom_weights> --benchmark MOTCUSTOM --split test --tracking-method strongsort
`

**Comment by mikel-brostrom** [comment]
That is not a problem. It will generate results on that specific folder when not using `--eval-existing`

**Comment by sivaji123256** [comment]
> What if we want to evaluate from scratch though? My folder does not contain the labels folder, it has the `gt` and `img1` folders as instructed [here](https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) and I thought we could then generate the HOTA results by simply running the command as below
> 
> `python val.py --yolo-weights <my_custom_weights> --benchmark MOTCUSTOM --split test --tracking-method strongsort `

@mesllo-bc ,I am also facing the same issue.Trying to evlauate from scratch but hota keyerror is raising.Can you pls tell you did you able to fix it ?

**Comment by mesllo-bc** [comment]
> > What if we want to evaluate from scratch though? My folder does not contain the labels folder, it has the `gt` and `img1` folders as instructed [here](https://github.com/mikel-brostrom/yolov8_tracking/wiki/How-to-evaluate-on-custom-tracking-dataset) and I thought we could then generate the HOTA results by simply running the command as below
> > `python val.py --yolo-weights <my_custom_weights> --benchmark MOTCUSTOM --split test --tracking-method strongsort `
> 
> @mesllo-bc ,I am also facing the same issue.Trying to evlauate from scratch but hota keyerror is raising.Can you pls tell you did you able to fix it ?

Hi @sivaji123256 , please check out this [issue](https://github.com/mikel-brostrom/yolo_tracking/issues/883) as the discussion arrives to a solution to your problem. Thank you!
