### ISSUE TITLE
How to use Multi-Camera to track pedestrians?

### ISSUE THREAD

**Issue by starytosky** [mikel-brostrom/yolo_tracking#902]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

How to use Multi-Camera to track pedestrians?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/583#issuecomment-1301791768
