### ISSUE TITLE
Modify the label of the image

### ISSUE THREAD

**Issue by eric12374038** [mikel-brostrom/yolo_tracking#903]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

How to modify the label of the image in the new version of the code?

In the past, I've been able to modify this code to serve my purposes.

label = None if hide_labels else (f'{id}' if hide_conf else \
                                (f'{id} {conf:.2f}' if hide_class else f'{id} {names[c]} {conf:.2f}'))

**Comment by mikel-brostrom** [comment]
This is not working in the ultralytics repo which this repo is dependent on. Won't add this flag till this get implemented there

**Comment by rickkk856** [comment]
@mikel-brostrom could these arguments be fixed in the track.py file?

It seems Yolov8 already implemented those arguments, see [Yolov8 Inference Arguments](https://docs.ultralytics.com/modes/predict/#inference-arguments) `--hide_labels` and `--hide_conf`

V
