### ISSUE TITLE
Custom Detection Model Tracking

### ISSUE THREAD

**Issue by Mersen130** [mikel-brostrom/yolo_tracking#905]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolov8_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Hi,

I'm trying out your tracker with Custom Detection Model

But I get this error when initializing the tracker: TypeError: OCSort.__init__() missing 4 required positional arguments: 'model_weights', 'device', 'fp16', and 'det_thresh'

Could you please elaborate on what arguments values should be filled in there, I couldn't find any related examples online

### Environment

Not environmental related

### Minimal Reproducible Example

```
from boxmot import DeepOCSORT

tracker = DeepOCSORT()
```

**Comment by mikel-brostrom** [comment]
Check the README example. There you have the explanation for all the requires arguments

**Comment by mikel-brostrom** [comment]
```
from boxmot import DeepOCSORT
from pathlib import Path


tracker = DeepOCSORT(
  model_weights=Path('mobilenetv2_x1_4_dukemtmcreid.pt'),  # which ReID model to use, when applicable
  device='cuda:0',  # 'cpu', 'cuda:0', 'cuda:1', ... 'cuda:N'
  fp16=True,  # wether to run the ReID model with half precision or not
  det_thresh=0.2  # minimum valid detection confidence
)
```
