### ISSUE TITLE
YOLOv8m-pretrained on the CrowdHuman datasets

### ISSUE THREAD

**Issue by wangjianan-123** [mikel-brostrom/yolo_tracking#912]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar enhancement requests.

### Description

Thank you for your open-source project and patient issue answer before, and it has been very helpful for my graduation project! 
Meanwhile, I trained a YOLOv8m model ([github](https://github.com/wangjianan-123/Graduation_Project_MOT))and achieved  MOTA of 60.442, IDF1 of 68.08 and HOTA of 54.386 by using strongsort on the MOT17. This performance seems not as good as the YOLOv5m model, maybe because there are still many techniques in training that I do not know. 
I hope it can help people in need.

**Comment by mikel-brostrom** [comment]
Hi @wangjianan-123,

I saw this in you repo:

> note:The model only be trained human full-body bounding-box of Crowdhuman datasets.

Do you have the code available? For MOT16/17 visible body would yield much better results :smile:

**Comment by wangjianan-123** [comment]
> For MOT16/17 visible body would yield much better results
@mikel-brostrom 
I trained a YOLOv8m model using visible bounding boxes, but the performance doesn't seem to be very good.For MOT17,MOTA is only 52 and HOTA is only 48.

**Comment by mikel-brostrom** [comment]
Let me know if you are planning to push the results you obtained. This repo would certainly benefit from a good people detector :smile:
