### ISSUE TITLE
How to make the box id correspond to the keypoint?

### ISSUE THREAD

**Issue by StormS0** [mikel-brostrom/yolo_tracking#915]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar bug report.

### Question

add to track.py   

                       if predictor.results[i].keypoints is not None:
                countid = 0

                for kpts ,  d  in zip (reversed(predictor.results[i].keypoints),reversed(predictor.results[i].boxes)):
                    p1, p2 = (int(d.xyxy.squeeze()[0]), int(d.xyxy.squeeze()[1])), (int(d.xyxy.squeeze()[2]), int(d.xyxy.squeeze()[3]))

                    countid+=1

                    boxid = 0 if d.id is None else int(d.id.item())
                    color_k = [boxid * 10, boxid * 20, boxid * 40]
                    print("countid", countid, color_k)
                    cv2.rectangle(im0, p1, p2, color_k, 5, lineType=cv2.LINE_AA)
                    name = ('' if boxid is None else f'id:{boxid} ')
                    cv2.putText(im0, name,p1, cv2.FONT_HERSHEY_SIMPLEX, 1,
                                (0, 0, 255), 1)
                    d.xyxy.squeeze()
                    for i, k in enumerate(kpts):
                        shape = (640, 640)

                        x_coord, y_coord = k[0], k[1]
                        if x_coord % shape[1] != 0 and y_coord % shape[0] != 0:
                            if len(k) == 3:
                                conf = k[2]
                                if conf < 0.5:
                                    continue
                            cv2.circle(im0, (int(x_coord), int(y_coord)), 2, color_k, -1, lineType=cv2.LINE_AA)

            cv2.imshow("im0",im0)
show im0, the box and keypoint have different colors.Why is this?

I guess the order of the boxes is modified here

```
predictor.results[i].boxes = Boxes(
                     # xyxy, (track_id), conf, cls
                     boxes=torch.from_numpy(predictor.tracker_outputs[i]).to(dets.device),
                     orig_shape=im0.shape[:2],  # (height, width)
                 )
```

**Comment by mikel-brostrom** [comment]
Notice:

https://github.com/mikel-brostrom/yolo_tracking/blob/b2f11989205b2a55d853f61e3c07a99d172046e3/examples/track.py#L129-L132

If you have segmentation or pose models you need to sync the tracker's output with the segmentations and keypoints. So that they end up in the right order.

**Comment by StormS0** [comment]
thanks ,You did a great job.

**Comment by StormS0** [comment]
Sometimes the key points are still wrong, maybe because of the same yolo_confs?
The following are the points I judged through IUO, which may get good results? Maybe you can get inspiration from them

`    def calculate_iou(self,box_a, box_b):
        """
        
        """
        xA = max(box_a[0], box_b[0])
        yA = max(box_a[1], box_b[1])
        xB = min(box_a[2], box_b[2])
        yB = min(box_a[3], box_b[3])

        inter_area = max(0, xB - xA + 1) * max(0, yB - yA + 1)

        box_a_area = (box_a[2] - box_a[0] + 1) * (box_a[3] - box_a[1] + 1)
        box_b_area = (box_b[2] - box_b[0] + 1) * (box_b[3] - box_b[1] + 1)

        iou = inter_area / float(box_a_area + box_b_area - inter_area)
        return iou  
  def filter_results2(self, i, predictor):
        if predictor.tracker_outputs[i].size != 0:
            ious = []
            for box_a in predictor.tracker_outputs[i]:

                iou_values = [self.calculate_iou(box_a[:4].tolist(), box_b[:4].tolist()) for box_b in predictor.results[i].boxes.data]
                ious.append(iou_values)
            print(ious)
            sorted_indices = np.argsort(ious, axis=1)[:, ::-1]
            column_list = sorted_indices[:, 0].tolist()
            predictor.results[i].keypoints = predictor.results[i].keypoints[column_list]`

**Comment by StormS0** [comment]
Sometimes the key points are still wrong, maybe because of the same yolo_confs?
The following are the points I judged through IUO, which may get good results? Maybe you can get inspiration from them

`    def calculate_iou(self,box_a, box_b):
        """

        """
        xA = max(box_a[0], box_b[0])
        yA = max(box_a[1], box_b[1])
        xB = min(box_a[2], box_b[2])
        yB = min(box_a[3], box_b[3])

        inter_area = max(0, xB - xA + 1) * max(0, yB - yA + 1)

        box_a_area = (box_a[2] - box_a[0] + 1) * (box_a[3] - box_a[1] + 1)
        box_b_area = (box_b[2] - box_b[0] + 1) * (box_b[3] - box_b[1] + 1)

        iou = inter_area / float(box_a_area + box_b_area - inter_area)
        return iou`

`    def filter_results2(self, i, predictor):
        if predictor.tracker_outputs[i].size != 0:
            ious = []
            for box_a in predictor.tracker_outputs[i]:

                iou_values = [self.calculate_iou(box_a[:4].tolist(), box_b[:4].tolist()) for box_b in predictor.results[i].boxes.data]
                ious.append(iou_values)
            print(ious)
            sorted_indices = np.argsort(ious, axis=1)[:, ::-1]
            column_list = sorted_indices[:, 0].tolist()
            predictor.results[i].keypoints = predictor.results[i].keypoints[column_list]`

**Comment by mikel-brostrom** [comment]
Using the Ultralytics way of doing this now. Basically: `from ultralytics.tracker.track import on_predict_postprocess_end`. Is this correct now?
