### ISSUE TITLE
Can we support more reid model for vechicle reid? 

### ISSUE THREAD

**Issue by niiish32x** [mikel-brostrom/yolo_tracking#925]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolov8_tracking/issues) and found no similar enhancement requests.

### Description

I have seen many awesome reid model in this repository https://github.com/michuanhaohao/AICITY2021_Track2_DMT 
can we enchance the Yolov8 Tracking to use these awesome  reid model for better tracking?

**Comment by mikel-brostrom** [comment]
This repo contains lightweight people ReID models only so adding others would make sense. Feel free to leave a PR :smile:.
