### ISSUE TITLE
I wonder how far the ID of Object Tracking can be increased.

### ISSUE THREAD

**Issue by rein1685** [mikel-brostrom/yolo_tracking#934]
### Search before asking

- [ ] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

If I leave the program on for nearly a month or a year, the ID will increase, but is there a logic that initializes back to 1 when it exceeds a certain value?

If not, is there any logic to prepare for an infinitely increased ID?

**Comment by mikel-brostrom** [comment]
The limit of the ID is the lagest value that can be represented by 64-bits. See this: https://stackoverflow.com/questions/7604966/maximum-and-minimum-values-for-ints

**Comment by rein1685** [comment]
If so, doesn't overflow occur if the ID increases to the limit of the int-type variable?

**Comment by mikel-brostrom** [comment]
I wouldn't be worried about creating more than 2**63-1 (9223372036854775807) ids
