### ISSUE TITLE
Need to move train.py into main folder, cannot execute properly from /examples

### ISSUE THREAD

**Issue by vhuard** [mikel-brostrom/yolo_tracking#936]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

i tried to run the main example provided.
while executing !python /examples/train.py ...
there was an error regarding botsort folder access
if i move train.py from examples/ to main folder it works for bytetrack tracking method but not for strongsort
can you help?

### Environment

Yolo Tracking v10.0.13 🚀 Python-3.10.12 torch-2.0.1+cu118 CUDA:0 (Tesla T4, 15102MiB)

### Minimal Reproducible Example

!python track.py --yolo-model 'best_yv8n_imgz640_100ep.pt' --tracking-method strongsort --imgsz 640 --source Barc_Placa_Espanya_2.MP4 --save --conf 0.4

**Comment by vhuard** [comment]
aditionaly i have one question 
in previous versions, trajectories are shown on the video.
is that schedule to bring back that functionallity?

**Comment by mikel-brostrom** [comment]
Post the full error please

**Comment by mikel-brostrom** [comment]
All the trackers are tested in the CI pipeline together with all the detector. SO unless you made modification I cannot see how this is failing. Again, post the error so that I can better help you out :smile:

**Comment by vhuard** [comment]
i download the git with following folders organisation
yolo_tracking
--assets
--boxmot
--examples
----track.py
--tests

i setup requirements

i launch the following command
!python examples/track.py --yolo-model 'best_yolov8n_imgz640.pt' --tracking-method bytetrack --imgsz 640 --source IMG_2240.MP4 --save --conf 0.4

and got following issues reported:
Traceback (most recent call last):
  File "/content/yolo_tracking/examples/track.py", line 10, in <module>
    from boxmot.tracker_zoo import create_tracker
ModuleNotFoundError: No module named 'boxmot'

**Comment by vhuard** [comment]
i did pip install boxmot
same error
still need to move train.py, utils.py and multiflow,py to main folder

any idea?

**Comment by mikel-brostrom** [comment]
There is no need to move anything at all. Everything gets tested in the [CI pipeline](https://github.com/mikel-brostrom/yolo_tracking/actions/runs/5228855344/jobs/9441517775) ensuring that the basic functionality works as it should. I recommend that you start from a clean slate.

**Comment by vhuard** [comment]
i do start every time from clean state
still it got the same error reported before.
anything else you can recommend?
