### ISSUE TITLE
Why is my MOTA negative？

### ISSUE THREAD

**Issue by lynxhawk** [mikel-brostrom/yolo_tracking#938]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I run val.py on my own custom dataset, then I found MOTA is negative. 
Below is my gt.txt and evaluation results.
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/26079070/705831e1-cd73-409f-a59a-61c252ba8724)
[gt.txt](https://github.com/mikel-brostrom/yolo_tracking/files/11720901/gt.txt)

**Comment by lynxhawk** [comment]
![image](https://github.com/mikel-brostrom/yolo_tracking/assets/26079070/c42eab44-fc13-402f-8be6-6c9935d9fea1)
Would you like to help me see if my gt.txt is correct? I compared it with the format of the mot17 dataset. I didn't find the error. I also uploaded gt.txt above.

**Comment by mikel-brostrom** [comment]
Negative MOTA does not necessarily indicate a problem with the evaluation. MOTA is negative when `FN + FP > GT` (described in the HOTA paper https://arxiv.org/abs/2009.07736; "MOTA scores can be negative and are unbounded.").

**Comment by mikel-brostrom** [comment]
Never tried to input GT as predicted data as well. Will get back at you when I try this out :smile:

**Comment by Hong-Pan** [comment]
> ![image](https://private-user-images.githubusercontent.com/26079070/245727300-c42eab44-fc13-402f-8be6-6c9935d9fea1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk0NjU1NjYsIm5iZiI6MTcxOTQ2NTI2NiwicGF0aCI6Ii8yNjA3OTA3MC8yNDU3MjczMDAtYzQyZWFiNDQtZmMxMy00MDJmLThiZTYtNmM5OTM1ZDlmZWExLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI3VDA1MTQyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhODBmMzc2NzQwNmEyN2ViY2VlYTk4YzdhNDAwMzFkNDNkOWJkZjgzNzFkYjZlNzhlMzdlZmRlNzExMzA3NDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.psUkA7GX9KsnC9xlsNAE3PcUYguFRJWprBVz6jdcEGc) Would you like to help me see if my gt.txt is correct? I compared it with the format of the mot17 dataset. I didn't find the error. I also uploaded gt.txt above.

You may try to change your cls_id to 1-based (starting from 1), then retry.
