### ISSUE TITLE
retrain ReID Model & Convert to .pt format

### ISSUE THREAD

**Issue by ihpolash** [mikel-brostrom/yolo_tracking#939]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I've retrained the ReID osnet_x0_25_market1501 model with custom dataset. The model format is .pth. But, in the repo, it accepts .pt format.  can you help me to convert the model from .pth to .pt to use in this repo?

**Comment by mikel-brostrom** [comment]
Just change the file name. Use .pt instead of .pth

**Comment by ihpolash** [comment]
@Nuwan1654 here is the guideline https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

**Comment by ihpolash** [comment]
> Just change the file name. Use .pt instead of .pth

Thank You!
