### ISSUE TITLE
yolo_nas model is not able to filter out the classes

### ISSUE THREAD

**Issue by lllkk-afk** [mikel-brostrom/yolo_tracking#940]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

when I use the yolo model yolo_nas_m, the code is no longer capable of filtering the classes.

**Comment by mikel-brostrom** [comment]
No available by default: https://github.com/Deci-AI/super-gradients/issues/892. So, so not implementable as I am using their pip package.
