### ISSUE TITLE
I tried to run for the tracking and this error occur.

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/yolo_tracking#941]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Traceback (most recent call last):
  File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 230, in <module>
    main(opt)
  File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 225, in main
    run(vars(opt))
  File "/home/sumyatnoe/miniconda3/envs/yolo8-deepoc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 97, in run
    path, im0s, vid_cap, s = batch
ValueError: too many values to unpack (expected 4)

### Environment

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

### Minimal Reproducible Example

conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

**Comment by mikel-brostrom** [comment]
Sorry, but conda is not officially supported. I recommend you switch to pip for further help.

**Comment by ImSuMyatNoe** [comment]
HI Thanks for the reply @mikel-brostrom . I tried to train with with the custom - weight and it occurs (attached error). Although I train weight from the yolov8-official train.py.

Could you please recommend me how to train the custom weight file in order to match the layer?

2023-06-15 15:56:53.483 | SUCCESS  | boxmot.deep.reid_model_factory:load_pretrained_weights:229 - Successfully loaded pretrained weights from "/mnt/d/Pycharm Projects/hiok/examples/weights/mobilenetv2_x1_4_dukemtmcreid.pt"
2023-06-15 15:56:53.483 | WARNING  | boxmot.deep.reid_model_factory:load_pretrained_weights:233 - The following layers are discarded due to unmatched keys or layer size: ('classifier.weight', 'classifier.bias')
2023-06-15 15:56:53.646 | ERROR    | multi_yolo_backend:__call__:76 - The Yolo model you selected is not available

**Comment by mikel-brostrom** [comment]
model name should contain model type (yolov8, yolo_nas, yolox)

**Comment by hieuhthh** [comment]
> ### Search before asking
> * [x]  I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.
> 
> ### Yolv8 Tracking Component
> Tracking
> 
> ### Bug
> Traceback (most recent call last): File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 230, in main(opt) File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 225, in main run(vars(opt)) File "/home/sumyatnoe/miniconda3/envs/yolo8-deepoc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 97, in run path, im0s, vid_cap, s = batch ValueError: too many values to unpack (expected 4)
> 
> ### Environment
> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
> 
> ### Minimal Reproducible Example
> conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia

Can anyone solve this ?

**Comment by hieuhthh** [comment]
> > ### Search before asking
> > 
> > * [x]   I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.
> > 
> > ### Yolv8 Tracking Component
> > Tracking
> > ### Bug
> > Traceback (most recent call last): File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 230, in main(opt) File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 225, in main run(vars(opt)) File "/home/sumyatnoe/miniconda3/envs/yolo8-deepoc/lib/python3.9/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context return func(*args, **kwargs) File "/mnt/d/Pycharm Projects/yolo8-deepoc/yolo_tracking/examples/track.py", line 97, in run path, im0s, vid_cap, s = batch ValueError: too many values to unpack (expected 4)
> > ### Environment
> > conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
> > ### Minimal Reproducible Example
> > conda install pytorch torchvision torchaudio pytorch-cuda=11.7 -c pytorch -c nvidia
> 
> Can anyone solve this ?

Never mind, pip install ultralytics --upgrade fixes this.
