### ISSUE TITLE
The  reid_export.py is missing

### ISSUE THREAD

**Issue by Nuwan1654** [mikel-brostrom/yolo_tracking#943]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Is there any script to convert the `osnet_x0_25_market1501.pt` model to tensorRT. Or any guideline to create a REID model using custom dataset.

**Comment by mikel-brostrom** [comment]
boxmot/deep/reid_export.pt

**Comment by Nuwan1654** [comment]
Thanks @mikel-brostrom
