### ISSUE TITLE
Track wit byte sort

### ISSUE THREAD

**Issue by uzumakinaruto19** [mikel-brostrom/yolo_tracking#946]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi i was having an issue while tracking yolov8 with bytetrack, it will be great if u can look into it and give some help or suggestions because i'm stuck here

So for some context , I'm using an rtsp stream with send frames to the detection and tracker which returns an output  json and the webrtc and stream through an angular UI

`
def main(input_data, frame, line_counter_1, line_counter_2, line_counter_3, zone):

    global model, frame_index,in_zone_state, in_zone_time

    input_data = {
        'frame_index': frame_index,
        'time_stamp': 0,  # You can replace 0 with an appropriate timestamp
        'demo_run': False
    }

    result = model.track(frame, classes=0, imgsz=480, show=False, stream=False,
                         agnostic_nms=True, tracker="bytetrack.yaml")
    result = result[0]

    frame = result.orig_img
    detections = sv.Detections.from_yolov8(result)

    if result.boxes.id is not None:
        detections.tracker_id = result.boxes.id.cpu().numpy().astype(int)
    else:
        detections.tracker_id = np.array([])
        detections.conf = np.array([])
        detections.xyxy = np.array([])

    labels = [str(id) for id in detections.tracker_id]

    new_ids = detections.tracker_id.astype(int).tolist()
    new_box = detections.xyxy.astype(int).tolist()

    i = 0
    while i < len(new_box):
        new_box[i][2] = new_box[i][2] - new_box[i][0]
        new_box[i][3] = new_box[i][3] - new_box[i][1]
        i = i + 1

    output = {
        'frame_index': frame_index,
        'detections': new_box,
        'demo_run': input_data['demo_run'],
        'ids': new_ids,
        'in_zone_time': in_zone_time,
        'avg_wait_time': avg_wait_time,
        'line_counter_values': line_counter_values
    }
    frame_index += 1
    print(output)
    return output
`

so here if I use a for loop and use source and give a video tracker works well, but if I pass a frame, for each frame the IDs are getting created again and again hense its not unique anymore.(its starts from 1 again) I hope u understand my problem

ik this isn't eacly related to this repo, but I have rffered ur repo so,

how to tackle that, if anyone could provide any solution itwill be really helpful  @mikel-brostrom

**Comment by mikel-brostrom** [comment]
You are not even using this repo for tracking
