### ISSUE TITLE
Not found the train.py file

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/yolo_tracking#948]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

I can’t find the train.py file in the examples folder. So, I can’t able to train the custom weight file. When I train on the yolov8-official and use this weight for the tracking module, i could not able to use this weight. Could someone please help and advise me🙏

### Environment

Yolo Tracking Latest version,
RTX A6000
python 3.9
PyTorch latest verison on ubuntu

### Minimal Reproducible Example

Can not find train.py in the examples
When i trained on the yolov8 official and can’t able to use this in the tracking module

**Comment by mikel-brostrom** [comment]
This is a tracking only repo. You won't find a `train.py` file because there is none. Train should be performed with the respective Yolo repos (v8, x, nas)
