### ISSUE TITLE
The --hide-label and hide-conf in the track .py file, does not actually hide in the output result.

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/yolo_tracking#949]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

The --hide-label and hide-conf in the track .py file, does not actually hide in the output result.
Ih the command, i run with this following command :

python examples/track.py --source testing1.mp4 --yolo-model yolov8x-seg.pt --hide-conf --hide-label --save 

but in the output, the result is not hiding the confidence score and label.

### Environment

latest track version
ubuntu on pytorch

### Minimal Reproducible Example

The --hide-label and hide-conf in the track .py file, does not actually hide in the output result.
Ih the command, i run with this following command :

python examples/track.py --source testing1.mp4 --yolo-model yolov8x-seg.pt --hide-conf --hide-label --save 

but in the output, the result is not hiding the confidence score and label.v

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/issues/903
