### ISSUE TITLE
Results Overwriting

### ISSUE THREAD

**Issue by TalhaSarwar1136** [mikel-brostrom/yolo_tracking#950]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Hi
After tracking when results are saved in text and image format they are not saved sequence wise. Results from new sequence overwrite older sequence. It would be grateful if label and image results are saved folder wise for every sequence

### Use case

It would help in saving results and furthur analysis

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Results gets saved at: `runs/track/exp*/`. `runs/track/exp*/` is always incremented by one, by default.
