### ISSUE TITLE
How to output confidence 

### ISSUE THREAD

**Issue by Stephentyndel** [mikel-brostrom/yolo_tracking#951]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I feel like I'm missing something obvious in the def write_MOT_results(txt_path, results, frame_idx, i) function but: 

in the examples/utils.py the following two lines are there:

```
results.boxes.conf.unsqueeze(1).to('cpu'),
results.boxes.cls.unsqueeze(1).to('cpu'),
```

But I see no possibility to write the confidence scores to the .txt file when --save-txt is implemented. The output includes the class name, bounding box coordinates, and the ID of the track, but not confidence. Any guidance is greatly appreciated. Thanks for your work!

Tracking method is set to 'strongsort'

**Comment by mikel-brostrom** [comment]
`conf` 

https://github.com/mikel-brostrom/yolo_tracking/blob/a504e9eae4c0de5be4f17ff2c5990367cf62e85f/examples/utils.py#L15

is written to `txt` here:

https://github.com/mikel-brostrom/yolo_tracking/blob/a504e9eae4c0de5be4f17ff2c5990367cf62e85f/examples/utils.py#L21

**Comment by Stephentyndel** [comment]
It seems like this code in track.py:

```
            if predictor.args.verbose or predictor.args.save or predictor.args.save_txt or predictor.args.show:
                s += predictor.write_results(i, predictor.results, (p, im, im0))
                predictor.txt_path = Path(predictor.txt_path)
                
                # write MOT specific results
                if predictor.args.source.endswith(VID_FORMATS):
                    predictor.MOT_txt_path = predictor.txt_path.parent / p.stem
                else:
                    # append folder name containing current img
                    predictor.MOT_txt_path = predictor.txt_path.parent / p.parent.name
                    
   
```

overwrites
```

               if predictor.tracker_outputs[i].size != 0 and predictor.args.save_txt:
                    #print(predictor.results[i])  # <-- add this line
                    write_MOT_results(
                        predictor.MOT_txt_path,
                        predictor.results[i],
                        frame_idx,
                        i,
                    )

I can modify slightly for my own needs, but fyi. Maybe could be useful to add --save-conf as an argument? Thanks for your work!
```
