### ISSUE TITLE
GitHub repository instructions are old, could they be updated?

### ISSUE THREAD

**Issue by jvkloc** [mikel-brostrom/yolo_tracking#954]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I noticed that the repository instructions for running `track.py` are outdated. The arguments have changed as well as the order of arguments. This might cause confusion for future users, especially for novices like me. Repository instructions are 

`python track.py --source 0 --yolo-weights yolov5/weights/crowdhuman_yolov5m.pt --classes 0`

but `track.py` prints the following instructions

```usage: track.py [-h] [--yolo-model YOLO_MODEL] [--reid-model REID_MODEL] [--tracking-method TRACKING_METHOD [--source SOURCE] [--imgsz IMGSZ [IMGSZ ...]] [--conf CONF] [--iou IOU] [--device DEVICE] [--show] [--save] [--classes CLASSES [CLASSES ...]] [--project PROJECT] [--name NAME] [--exist-ok] [--half] [--vid-stride VID_STRIDE] [--hide-label] [--hide-conf] [--save-txt]```

so there is no argument `--yolo-weights` and `--source` comes afer `-yolo--model`, for example. Also, when trying 

`python3 track.py --yolo-model crowdhuman_yolov5m.pt --source test_video1.mp4 --classes 0` 

I get `The Yolo model you selected is not available` error. The same error appears also when trying with the repository example path `yolov5/weights/crowdhuman_yolov5m.pt`. How can I use the person-tracking weigths?

**Comment by mikel-brostrom** [comment]
Check out master. They are updated :smile:

**Comment by jvkloc** [comment]
Oh, I see. You can remove this topic. Or should I? This is quite useless to anyone awake and posessing a pair of eyes : )
