### ISSUE TITLE
Using the frame taken from the camera as the source

### ISSUE THREAD

**Issue by iremcorak** [mikel-brostrom/yolo_tracking#955]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am using camera with a custom library in my project. The source should be a string, but how can I use the processed version of the frame I took from the camera as the source?

**Comment by mikel-brostrom** [comment]
Check of the custom model example:

https://github.com/mikel-brostrom/yolo_tracking#custom-object-detection-model-example
