### ISSUE TITLE
Dataset used for weights

### ISSUE THREAD

**Issue by Mohit-robo** [mikel-brostrom/yolo_tracking#956]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hey, I had something to confirm, the weights used by trackers are trained on person-reid datasets right, so why are they preferred for other objects as well? My general question is why aren't we using a separate vehicle Reid model for vehicle tracking. If this sounds great to you I can help you with this, as I have quite some knowledge of Reid.

**Comment by mikel-brostrom** [comment]
Hi @Mohit-robo! Thx again for your last PR!

>  the weights used by trackers are trained on person-reid datasets right

Yes

> so why are they preferred for other objects as well?

I just don't have time to add other ReID models. MOT16/17 and 20, the main MOT datasets, are only comprised of people so I try to focus on ReID model that focus on people re-identification. Of course, models trained on different datasets than `market1501`, `duke` and `msmt17` would be nice to have as well.

**Comment by Mohit-robo** [comment]
Thanks for the reply, I have some resnet-50 based vegicle reid models which could be used for tracking vehicle, and if you could keep this as only implementation and no evaluation I think would do it for now. And we could figure out something about evaluation. I actually have worked for some time now with vehicle reid if its okay with you to bring in vehicle reid models with current models I could work on this task.

**Comment by mikel-brostrom** [comment]
> and if you could keep this as only implementation and no evaluation I think would do it for now

I would need some metrics just to make sure that they are worth integrating
