### ISSUE TITLE
How to handle ignored regions

### ISSUE THREAD

**Issue by TalhaSarwar1136** [mikel-brostrom/yolo_tracking#960]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi!

I am working on UAVDT dataset and it provides "seq_gt.txt" file in format
"Frame id, target_id, BB_Left, BB_Top, width , height, 1,1,-1"

and another file named "Seq_gt_ignore,txt" in format
"Frame id, target_id, BB_Left, BB-Top, width , height, 1,-1,-1"

How I can use gt_ignore during MOT evaluation, so to get more accurate results

One sequence file is attached for reference
[M1304_gt.txt](https://github.com/mikel-brostrom/yolo_tracking/files/11789246/M1304_gt.txt)
[M1304_gt_ignore.txt](https://github.com/mikel-brostrom/yolo_tracking/files/11789248/M1304_gt_ignore.txt)

**Comment by TalhaSarwar1136** [comment]
Thanks for the reply. 
I have checked the link you shared. In the first link it has to be identified as another ID which detection model is not trained to do so. Another problem is In complete code it reads ignored regions but I am unable to understand the format in which that has to be provided.

**Comment by mikel-brostrom** [comment]
Sorry I am not familiar with that dataset. I am afraid I won't be able to help you in a good way.

**Comment by TalhaSarwar1136** [comment]
You can give me example of any MOT Dataset. I would then try to adjust my annotation file accordingly

**Comment by TalhaSarwar1136** [comment]
And another question. You have shared an experiment of Kalman Filter update parameter. How can I vary that parameter. Thanks in advance
