### ISSUE TITLE
LAP installation problem 

### ISSUE THREAD

**Issue by muttahirul** [mikel-brostrom/yolo_tracking#961]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

I am using python version 3.10 as you have suggested >=3.8
But I am facing problem installing lap as lap only supports python 3.7 versions.
Could please tell me what should I do?

**Comment by mikel-brostrom** [comment]
`lap` installs correctly for python3.8, 3.9 and 3.10 as shown in the pipieline: https://github.com/mikel-brostrom/yolo_tracking/actions/runs/5228855344/jobs/9441517775

**Comment by muttahirul** [comment]
Hi @mikel-brostrom , Thank you for your reply. But I used windows 10 operating system and Pycharm IDE. While I tried to install lap, it still shows this error.

(venv) G:\YOLOV8_tracking\yolo_tracking>pip install lap
Collecting lap
  Using cached lap-0.4.0.tar.gz (1.5 MB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: lap
  Building wheel for lap (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Partial import of lap during the build process.
      C:\Users\User\AppData\Local\Temp\pip-install-2etukphs\lap_d6491dff3bac4b7780c930a18233817e\setup.py:223: DeprecationWarning:
     
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
       from numpy.distutils.core import setup
      Generating cython files
      running bdist_wheel
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      G:\YOLOV8_tracking\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lap
      copying lap\lapmod.py -> build\lib.win-amd64-cpython-38\lap
      copying lap\__init__.py -> build\lib.win-amd64-cpython-38\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\User\AppData\Local\Temp\pip-install-2etukphs\lap_d6491dff3bac4b7780c930a18233817e\build\temp.win-amd64-cpython-38\Release\ccompiler_opt_cache_ext.py        
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lap
  Running setup.py clean for lap
Failed to build lap
Installing collected packages: lap
  Running setup.py install for lap ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lap did not run successfully.
  │ exit code: 1
  ╰─> [39 lines of output]
      Partial import of lap during the build process.
      C:\Users\User\AppData\Local\Temp\pip-install-2etukphs\lap_d6491dff3bac4b7780c930a18233817e\setup.py:223: DeprecationWarning:
     
        `numpy.distutils` is deprecated since NumPy 1.23.0, as a result
        of the deprecation of `distutils` itself. It will be removed for
        Python >= 3.12. For older Python versions it will remain present.
        It is recommended to use `setuptools < 60.0` for those Python versions.
        For more details, see:
          https://numpy.org/devdocs/reference/distutils_status_migration.html
     
     
        from numpy.distutils.core import setup
      Generating cython files
      running install
      G:\YOLOV8_tracking\venv\lib\site-packages\setuptools\command\install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
        warnings.warn(
      running build
      running config_cc
      INFO: unifing config_cc, config, build_clib, build_ext, build commands --compiler options
      running config_fc
      INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
      running build_src
      INFO: build_src
      INFO: building extension "lap._lapjv" sources
      INFO: building data_files sources
      INFO: build_src: building npy-pkg config files
      running build_py
      creating build
      creating build\lib.win-amd64-cpython-38
      creating build\lib.win-amd64-cpython-38\lap
      copying lap\lapmod.py -> build\lib.win-amd64-cpython-38\lap
      copying lap\__init__.py -> build\lib.win-amd64-cpython-38\lap
      running build_ext
      INFO: No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
      INFO: customize MSVCCompiler
      INFO: customize MSVCCompiler using build_ext
      INFO: CCompilerOpt.cc_test_flags[1073] : testing flags (/O2)
      error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/
      INFO: CCompilerOpt.cache_flush[857] : write cache to path -> C:\Users\User\AppData\Local\Temp\pip-install-2etukphs\lap_d6491dff3bac4b7780c930a18233817e\build\temp.win-amd64-cpython-38\Release\ccompiler_opt_cache_ext.py        
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lap

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

Could please give me some solution in this regards?

**Comment by mikel-brostrom** [comment]
I don't test the repo for windows so cannot know if this works for windows
