### ISSUE TITLE
option --yolo_model = yolox_n --classes 0 returns all classes results

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#963]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolv8 Tracking Component

Tracking

### Bug

Hello.
Thank you for making nice repo.

When I use yolo_tracking with `--yolo_model=yolox_n --classes 0  --save-txt --save conf 0.01 iou 0.8` otions, it returns all classes results. Is this a bug?
returned example message is here    
`65 persons, 1 car, 3 trucks, 1 boat, 1 kite,`

### Environment

- Windows wsl2 (Ubuntu 20.04)

### Minimal Reproducible Example

```
python track.py --tracking-method strongsort --source {YOUR_PATH} --yolo-model yolox_n --img 2560 --classes 0 --save-txt --save --conf 0.01 --device 0 --iou 0.8
```

**Comment by mikel-brostrom** [comment]
Per class eval is in this branch: https://github.com/mikel-brostrom/yolo_tracking/tree/pymotmetrics. MOreover it does not calculate HOTA as this metric is not present in pymotmetric yet

**Comment by mikel-brostrom** [comment]
There is no class filtering for yolox. This is not implemented in the SG repo. Please as them here: https://github.com/Deci-AI/super-gradients

**Comment by TakuNishiumi** [comment]
@mikel-brostrom 
Thank you.
