### ISSUE TITLE
about yolov8 strongsort save-crop function

### ISSUE THREAD

**Issue by ImSuMyatNoe** [mikel-brostrom/yolo_tracking#964]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

In the YOLOv5-StrongSort, the save-crop function saves each ID of the bounding box to a separate folder. However, in the YOLOv8-StrongSort save-crop function, all bounding boxes are saved to the same class folder. How should i modify to same with yolov5-strongsort function.

**Comment by mikel-brostrom** [comment]
Yup, you are right. This functionality did not got ported after the big refactor I see. Just re-implemented it in master. Activate it by:

`python3 examples/track.py --save-id-crop`
