### ISSUE TITLE
Link(URL) of the main page

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#965]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, @mikel-brostrom 

A link you wrote in main page may be wrong.
YOLOv8 | YOLO-NAS | YOLOX examples => Select ReID model => [reid_export.py](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/master/reid_export.py)
Could you fix it?

Thanks

**Comment by mikel-brostrom** [comment]
Thanks for pointing this out. Updated!
