### ISSUE TITLE
About location of exp* folders

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#971]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

Hi @mikel-brostrom,

If you have times, Could you change the save directory of experiment folder as follows as written in README.md?
```
MOT compliant results
Can be saved to your experiment folder runs/track/<yolo_model>_<deep_sort_model>/ by
```
In the current setting, I think that the default folder of exp* locates `runs/track/exp*`.
Could you check it?
Thank you!

### Are you willing to submit a PR?

- [ ] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Don't know if I want to take this back. The reason is that the experiments don't end up in chronological order. When doing many experiments it can be frustrating to scroll through all the experiments to find the latest one. Maybe saving the yolo config as well would be a better solution?

**Comment by TakuNishiumi** [comment]
I agree with you. It might better saving the config instead of changing folder name. If you can do it, I am happy.
Thank you.

**Comment by mikel-brostrom** [comment]
Will put this in my backlog :smile:
