### ISSUE TITLE
latest version of --save-txt does not save [SOURCE NAME].txt file?

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#972]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and [discussions](https://github.com/mikel-brostrom/yolo_tracking/discussions) and found no similar questions.

### Yolo Tracking Component

Tracking

### Bug

Hi @mikel-brostrom,

Forgive me, consecutive posts of issues.
Normally, --save-txt option saves a [SOURCE NAME].txt file and [SOURCE NAME]_N.txt files.
Although, I noticed that generally version recently updated does not save [SOURCE NAME].txt. 
Is this a bug? or only happened in my environment?

Sincerely, 

### Environment

v10.0.15 cause this.   
v10.0.13 does not cause this.   

### Minimal Reproducible Example

python example/track.py --source --save-txt --save

**Comment by mikel-brostrom** [comment]
Use --save-mot :smile:

**Comment by TakuNishiumi** [comment]
Great!

**Comment by TakuNishiumi** [comment]
@mikel-brostrom ,

I tried tracking with `python track.py --save-mot --save-txt --save` today.
I got some labels but I cannot get ` [SOURCE NAME].txt` in labels directory.
How can I get  ` [SOURCE NAME].txt` like version of v10.0.13?
In addition to it, what is the difference between --save-txt and --save-mot ?

**Comment by TakuNishiumi** [comment]
This file exists at `yolo_tracking/runs/exp*/mot/[SOURCE NAME].txt`.
