### ISSUE TITLE
ReID models were completely ignored in my tracking?

### ISSUE THREAD

**Issue by TakuNishiumi** [mikel-brostrom/yolo_tracking#977]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, Mr. @mikel-brostrom,

I have a question about ReID model.
> Some tracking methods combine appearance description and motion in the process of tracking. For those which use appearance, you can choose a ReID model based on your needs from this [ReID model zoo](https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO). These model can be further optimized for you needs by the [reid_export.py](https://github.com/mikel-brostrom/yolo_tracking/blob/master/boxmot/deep/reid_export.py) script

I tried many tracking with many patterns of `--yolo_model` * `--reid-model`  * `--tracking-method` * `IoU` * `conf`.
I realized that --reid-model parameter completely did not change the tracking results. 
The ReID models downloaded from [here.](https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO)
Do you know what are the causes?
What can I do next to improve accuracy of tracking persons?

**Comment by mikel-brostrom** [comment]
Which tracking method are you using?

**Comment by mikel-brostrom** [comment]
OCSORT and ByteTrack are motion only trackers. ReID does not apply to this methods :smile:

**Comment by TakuNishiumi** [comment]
I tried all model and all combinations.

**Comment by TakuNishiumi** [comment]
I see, Thanks!
By the way, What can I do next to improve accuracy of tracking persons?
Do you have ideas?

**Comment by mikel-brostrom** [comment]
Just run `val.py` on `MOT17-mini`

```
reid-model: mobilenetv2_x1_4_dukemtmcreid.pt

COMBINED HOTA                         57.655
```


```
reid-model: osnet_x0_25_dukemtmcreid.pt


COMBINED HOTA                        57.982
```

**Comment by TakuNishiumi** [comment]
Great! I will try it now! 
Thank you.
