### ISSUE TITLE
Multi-class tracking OCSort

### ISSUE THREAD

**Issue by Pieterm93** [mikel-brostrom/yolo_tracking#982]
### Search before asking

- [X] I have searched the Yolov8 Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar enhancement requests.

### Description

I had some issues with multi-class tracking in OCSort. I didn't want the tracker to associate detections of different classes, so each track may only consist of 1 unique class. I tested this by changing the class of a person walking to a car from a certain frame point where the track continued. I Couldn't find a solution anywhere and no Trackers i found had this option.

I made the self.trackers a dict and am keeping separate trackers for each class in the detections, by iterating over them in the update code. Does this make any sense or am I still missing a step? It seems to be working just fine and now doesn't associate bboxes from different classes like it did earlier.

lass OCSort(object):
    def __init__(self, det_thresh=0.2, max_age=30, min_hits=3, 
        iou_threshold=0.3, delta_t=3, asso_func="iou", inertia=0.2, use_byte=False):
        """
        Sets key parameters for SORT
        """
        self.max_age = max_age
        self.min_hits = min_hits
        self.iou_threshold = iou_threshold
        self.trackers = {}
        self.frame_count = 0
        self.det_thresh = det_thresh
        self.delta_t = delta_t
        self.asso_func = ASSO_FUNCS[asso_func]
        self.inertia = inertia
        self.use_byte = use_byte
        KalmanBoxTracker.count = 0

    def update(self, dets, _):
        """
        Params:
          dets - a numpy array of detections in the format [[x1,y1,x2,y2,score],[x1,y1,x2,y2,score],...]
        Requires: this method must be called once for each frame even with empty detections (use np.empty((0, 5)) for frames without detections).
        Returns the a similar array, where the last column is the object ID.
        NOTE: The number of objects returned may differ from the number of detections provided.
        """

        assert isinstance(dets, np.ndarray), f"Unsupported 'dets' input format '{type(dets)}', valid format is np.ndarray"
        assert len(dets.shape) == 2, f"Unsupported 'dets' dimensions, valid number of dimensions is two"
        assert dets.shape[1] == 6, f"Unsupported 'dets' 2nd dimension lenght, valid lenghts is 6"

        self.frame_count += 1
        
        xyxys = dets[:, 0:4]
        confs = dets[:, 4]
        clss = dets[:, 5]
        
        classes = clss
        xyxys = xyxys
        confs = confs

        output_results = np.column_stack((xyxys, confs, classes))
        
        inds_low = confs > 0.1
        inds_high = confs < self.det_thresh
        inds_second = np.logical_and(inds_low, inds_high)  # self.det_thresh > score > 0.1, for second matching
        dets_second = output_results[inds_second]  # detections for second matching
        remain_inds = confs > self.det_thresh
        dets = output_results[remain_inds]

        # generate dict for each unique class in the detections
        dets_dict = {class_id: np.array([det for det in dets if det[-1] == class_id]) for class_id in set(det[-1] for det in dets)}
        # list that outputs the results for multiple classes
        final_ret = []
    
        for class_id in dets_dict:
            if class_id not in self.trackers:
                self.trackers[class_id] = []
            # get predicted locations from existing trackers.
            dets = dets_dict[class_id]
            trks = np.zeros((len(self.trackers[class_id]), 5))
            to_del = []
            ret = []
            for t, trk in enumerate(trks):
                pos = self.trackers[class_id][t].predict()[0]
                trk[:] = [pos[0], pos[1], pos[2], pos[3], 0]
                if np.any(np.isnan(pos)):
                    to_del.append(t)
            trks = np.ma.compress_rows(np.ma.masked_invalid(trks))
            for t in reversed(to_del):
                self.trackers[class_id].pop(t)

            velocities = np.array(
                [trk.velocity if trk.velocity is not None else np.array((0, 0)) for trk in self.trackers[class_id]])
            last_boxes = np.array([trk.last_observation for trk in self.trackers[class_id]])
            k_observations = np.array(
                [k_previous_obs(trk.observations, trk.age, self.delta_t) for trk in self.trackers[class_id]])

            """
                First round of association
            """
            matched, unmatched_dets, unmatched_trks = associate(
                dets, trks, self.iou_threshold, velocities, k_observations, self.inertia)
            for m in matched:
                self.trackers[class_id][m[1]].update(dets[m[0], :5], dets[m[0], 5])

            """
                Second round of associaton by OCR
            """
            # BYTE association
            if self.use_byte and len(dets_second) > 0 and unmatched_trks.shape[0] > 0:
                u_trks = trks[unmatched_trks]
                iou_left = self.asso_func(dets_second, u_trks)          # iou between low score detections and unmatched tracks
                iou_left = np.array(iou_left)
                if iou_left.max() > self.iou_threshold:
                    """
                        NOTE: by using a lower threshold, e.g., self.iou_threshold - 0.1, you may
                        get a higher performance especially on MOT17/MOT20 datasets. But we keep it
                        uniform here for simplicity
                    """
                    matched_indices = linear_assignment(-iou_left)
                    to_remove_trk_indices = []
                    for m in matched_indices:
                        det_ind, trk_ind = m[0], unmatched_trks[m[1]]
                        if iou_left[m[0], m[1]] < self.iou_threshold:
                            continue
                        self.trackers[class_id][trk_ind].update(dets_second[det_ind, :5], dets_second[det_ind, 5])
                        to_remove_trk_indices.append(trk_ind)
                    unmatched_trks = np.setdiff1d(unmatched_trks, np.array(to_remove_trk_indices))

            if unmatched_dets.shape[0] > 0 and unmatched_trks.shape[0] > 0:
                left_dets = dets[unmatched_dets]
                left_trks = last_boxes[unmatched_trks]
                iou_left = self.asso_func(left_dets, left_trks)
                iou_left = np.array(iou_left)
                if iou_left.max() > self.iou_threshold:
                    """
                        NOTE: by using a lower threshold, e.g., self.iou_threshold - 0.1, you may
                        get a higher performance especially on MOT17/MOT20 datasets. But we keep it
                        uniform here for simplicity
                    """
                    rematched_indices = linear_assignment(-iou_left)
                    to_remove_det_indices = []
                    to_remove_trk_indices = []
                    for m in rematched_indices:
                        det_ind, trk_ind = unmatched_dets[m[0]], unmatched_trks[m[1]]
                        if iou_left[m[0], m[1]] < self.iou_threshold:
                            continue
                        self.trackers[class_id][trk_ind].update(dets[det_ind, :5], dets[det_ind, 5])
                        to_remove_det_indices.append(det_ind)
                        to_remove_trk_indices.append(trk_ind)
                    unmatched_dets = np.setdiff1d(unmatched_dets, np.array(to_remove_det_indices))
                    unmatched_trks = np.setdiff1d(unmatched_trks, np.array(to_remove_trk_indices))

            for m in unmatched_trks:
                self.trackers[class_id][m].update(None, None)

            # create and initialise new trackers for unmatched detections
            for i in unmatched_dets:
                trk = KalmanBoxTracker(dets[i, :5], dets[i, 5], delta_t=self.delta_t)
                self.trackers[class_id].append(trk)
            i = len(self.trackers[class_id])
            for trk in reversed(self.trackers[class_id]):
                if trk.last_observation.sum() < 0:
                    d = trk.get_state()[0]
                else:
                    """
                        this is optional to use the recent observation or the kalman filter prediction,
                        we didn't notice significant difference here
                    """
                    d = trk.last_observation[:4]
                if (trk.time_since_update < 1) and (trk.hit_streak >= self.min_hits or self.frame_count <= self.min_hits):
                    # +1 as MOT benchmark requires positive
                    ret.append(np.concatenate((d, [trk.id+1], [trk.conf], [trk.cls])).reshape(1, -1))
                    ## add this to the final_ret list as well
                    final_ret.append(np.concatenate((d, [trk.id+1], [trk.conf], [trk.cls])).reshape(1, -1))
                i -= 1
                # remove dead tracklet
                if(trk.time_since_update > self.max_age):
                    self.trackers[class_id].pop(i)
        
        if(len(final_ret) > 0):
                return np.concatenate(final_ret)
        return np.array([])
        
Thanks!

### Are you willing to submit a PR?

- [x] Yes I'd like to help by submitting a PR!

**Comment by mikel-brostrom** [comment]
Makes total sense to use a dict to keep each class separate from another and then run the association process for each isolated class. This would give some metrics boosts to multi-class tracking datasets. I see you are willing to submit a PR :smile:. I would be more than happy to review it :smile:

**Comment by Pieterm93** [comment]
I'll submit a pr soon then :)

**Comment by lpc-eol** [comment]
looking forward to seeing it 👍 

> I'll submit a pr soon then :)

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/yolo_tracking/pull/983
