### ISSUE TITLE
Custom weights for feature extractor for re-identification using DeepOCSORT

### ISSUE THREAD

**Issue by ElNoSabe322** [mikel-brostrom/yolo_tracking#988]
Have you tried to rename you model to something like `resnet18_yourdataset.pt` and load it by
`python track.py --source 0 --reid-weights resnet18_yourdataset.pt`?

_Originally posted by @mikel-brostrom in https://github.com/mikel-brostrom/yolo_tracking/issues/841#issuecomment-1537829622_

Hello @mikel-brostrom, I tried to load my custom feature extractor weights by using the method you described above, but I still face an issue. Would you kindly help me out?

Here is a code snippet of what I have been trying to run:
```python
# Define the type and parameters of the tracker used
def load_tracker():
    # Define the tracker object
    tracker = DeepOCSORT(
        # model_weights=Path("osnet_x0_25_msmt17.pt"),  # which ReID model to use
        model_weights=Path("resnet101_Drone-Turtle-1.pt"),
        device="cuda:0",  # 'cpu', 'cuda:0', 'cuda:1', ... 'cuda:N'
        fp16=True,  # whether to run the ReID model with half precision or not
        det_thresh=0.3,
        max_age=40,
        min_hits=3,
        iou_threshold=0.3,
    )
    return tracker
```
And this is the error I received:
```
ERROR ❌: "Unknown model: None. Must be one of ['resnet18', 'resnet34', 'resnet50', 'resnet101', 'resnet152', 'resnext50_32x4d', 'resnext101_32x8d', 'resnet50_fc512', 'se_resnet50', 'se_resnet50_fc512', 'se_resnet101', 'se_resnext50_32x4d', 'se_resnext101_32x4d', 'densenet121', 'densenet169', 'densenet201', 'densenet161', 'densenet121_fc512', 'inceptionresnetv2', 'inceptionv4', 'xception', 'resnet50_ibn_a', 'resnet50_ibn_b', 'nasnsetmobile', 'mobilenetv2_x1_0', 'mobilenetv2_x1_4', 'shufflenet', 'squeezenet1_0', 'squeezenet1_0_fc512', 'squeezenet1_1', 'shufflenet_v2_x0_5', 'shufflenet_v2_x1_0', 'shufflenet_v2_x1_5', 'shufflenet_v2_x2_0', 'mudeep', 'resnet50mid', 'hacnn', 'pcb_p6', 'pcb_p4', 'mlfn', 'osnet_x1_0', 'osnet_x0_75', 'osnet_x0_5', 'osnet_x0_25', 'osnet_ibn_x1_0', 'osnet_ain_x1_0', 'osnet_ain_x0_75', 'osnet_ain_x0_5', 'osnet_ain_x0_25', 'lmbn_n']"
```    

The pre-trained weights are being loaded successfully. But the problem arises when I try to use custom feature extractor weights.

**Comment by mikel-brostrom** [comment]
Fixed. `resnet101` was not available previously: 

https://github.com/mikel-brostrom/yolo_tracking/blob/3e079890decbbe49f6ab4daa4a80ffaba49eb64d/boxmot/appearance/reid_model_factory.py#L8

Let me know it it works for you now.

**Comment by ElNoSabe322** [comment]
Thank you @mikel-brostrom. It works now! 👍
