### ISSUE TITLE
BotSort impelementation

### ISSUE THREAD

**Issue by oljikeboost** [mikel-brostrom/yolo_tracking#993]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi! I have read the paper of BotSort, but found that your implementation of association algorithm is different from what they propose. Also, you have [commented](https://github.com/mikel-brostrom/yolo_tracking/blob/ad4670861a2ea7afe75cc6848d3b356ef7264d8f/boxmot/trackers/botsort/bot_sort.py#L342) the part which is similar to their implementation and idea. Could you please explain why?

**Comment by mikel-brostrom** [comment]
Thanks for pointing this out. Will take back the original implementation

**Comment by lyy0095** [comment]
the same question as above!
I just ran the 'botsort' method with yolox_x.pt, but in  boxmot\motion\botsort_kf.py, there is no implementation of         **multi_predict** function, the following function of boxmot\trackers\botsort\bot_sort.py  will lead to error:
    _@staticmethod
    def multi_predict(stracks):
        if len(stracks) > 0:
            multi_mean = np.asarray([st.mean.copy() for st in stracks])
            multi_covariance = np.asarray([st.covariance for st in stracks])
            for i, st in enumerate(stracks):
                if st.state != TrackState.Tracked:
                    multi_mean[i][6] = 0
                    multi_mean[i][7] = 0
            **multi_mean, multi_covariance = STrack.shared_kalman.multi_predict(multi_mean, multi_covariance)  #***this will cause error*****
            for i, (mean, cov) in enumerate(zip(multi_mean, multi_covariance)):
                stracks[i].mean = mean
                stracks[i].covariance = cov_

**Comment by mikel-brostrom** [comment]
`pull`. This was updated in master

**Comment by mikel-brostrom** [comment]
Should be working again :smile:. I took back the original implementation.
