### ISSUE TITLE
YoloV8 Error, ValueError: too many values to unpack (expected 13) with TensorRT

### ISSUE THREAD

**Issue by YOOHYOJEONG** [mikel-brostrom/yolo_tracking#994]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi, Thank you for your constant code update.

I'm running the code on the Jetson TX2.
So, I converted yolov8n_custom.pt to TensorRT(.engine).
When I inference the code with the .engine file(converted to TensorRT), an error occurs in yolov8 part.

error : 
Ultralytics YOLOv8.0.133 🚀 Python-3.8.0 torch-1.11.0a0+gitbc2c6ed CUDA:0 (NVIDIA Tegra X2, 7850MiB)
Traceback (most recent call last):
  File "track.py", line 401, in <module>
    main(opt)
  File "track.py", line 396, in main
    run(**vars(opt))
  File "/home/user/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 111, in run
    model = AutoBackend(yolo_weights, device=device, dnn=dnn, fp16=half)
  File "/home/user/workspace/yolov8/ultralytics/nn/autobackend.py", line 81, in __init__
    pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)
ValueError: too many values to unpack (expected 13)

Is this error the error of yolov8? I don't know how to solve it.

Thank you.

**Comment by mikel-brostrom** [comment]
Could you try to push the ultralytics pacakge version?

`pip install --upgrade ultralytics`

**Comment by YOOHYOJEONG** [comment]
Yes... I upgraded the ultralytics.
my ultralytics version is ultralytics-8.0.134.

Is it right to ask yolov8 repo for this?

**Comment by mikel-brostrom** [comment]
Try it with the ultralytics repo only. Then we would know which side the error is on.

**Comment by YOOHYOJEONG** [comment]
I didn't have a problem when I just turned ultralytics repo only with tensorrt engine file.

**Comment by YOOHYOJEONG** [comment]
There was no problem when I only used the ultralytics repo only. Does that mean that the tracking part is wrong because there is no problem with the ultralytics repo?

**Comment by YOOHYOJEONG** [comment]
Ok.. I solved.
Thank you.

**Comment by mikel-brostrom** [comment]
What was the issue?

**Comment by YOOHYOJEONG** [comment]
@mikel-brostrom 

yolov8/ultralytics/nn/autobackend.py", line 81, in init
pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton = self._model_type(w)

Here, 
self._model_type(w) was 14 in length. So I added '_' after the triton to adjust the length.

After :
pt, jit, onnx, xml, engine, coreml, saved_model, pb, tflite, edgetpu, tfjs, paddle, triton, _ = self._model_type(w)

**Comment by mikel-brostrom** [comment]
But that must a package version issue right?

**Comment by YOOHYOJEONG** [comment]
Yes... I tried to : `pip install --upgrade ultralytics`
But, It didn't worked. Because ultralytics was already the latest version.

It's a mystery.... 🤣

Thank you for always answering kindly.
