### ISSUE TITLE
Issue running test examples on Python 3.10.6 and Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by duane-edgington** [mikel-brostrom/yolo_tracking#998]
### Search before asking

- [X] I have searched the Yolo Tracking [issues](https://github.com/mikel-brostrom/yolo_tracking/issues) and found no similar bug report.

### Question

Hi Mikel. I am trying to get your repository working on your test data, before attempting to use on our underwater video.

I am having trouble with the simple test examples

I run: 
**python examples/track.py --yolo-model yolov8n**

and get
**Missing packages: "yolox==0.3.0" 
Atempting installation...
2023-07-14 14:51:05.604 | ERROR    | boxmot.utils.checks:check_packages:31 - Command 'pip install --no-cache "yolox==0.3.0"  ' returned non-zero exit status 1.**

In my environment, I am running 
Python 3.10.6

and have installed all the packages by running
git pull
pip install -v -e .

I am running on Ubuntu 22.04 LTS Desktop
I can run
Ultralytics YOLOv8.0.134 for detection

and it reports
🚀 Python-3.10.6 torch-2.0.1 CUDA:0 (NVIDIA GeForce GTX 1080 Ti, 11169MiB)
Setup complete ✅ (12 CPUs, 31.0 GB RAM, 120.0/937.3 GB disk)

I cannot install yolox 0.3.0 using pip; it fails dependencies. 

Any ideas how I can address this?? Do I need to step back to python 3.8.17 for this environment??

thanks

**Comment by duane-edgington** [comment]
Hi Mikel. I was able to address this problem by building a new conda environment with Python 3.8.17

I then ran
**python examples/track.py --tracking-method deepocsort --source test.avi** 

which worked fine. 

Do you want to put a python version specifications on your page? 

Thank you.

**Comment by mikel-brostrom** [comment]
Hi @duane-edgington . We test our software for python 3.8, 3.9 and 3.10 (3.10.12 to be more specific). We do not however officially support conda and we encourage our users to install environment dependencies with pip. Pip installations are tested in our CI and are guaranteed to work for python>=3.8

**Comment by duane-edgington** [comment]
Hi Mikel. Thank you. I am doing the installations with pip, just setting the base environment with miniconda. Do you all have a different way to isolate the environments from the base Ubuntu; maybe venv, that you recommend?

**Comment by mikel-brostrom** [comment]
I  always use 

python -m venv /path/to/new/virtual/environment

for project specific dependencies isolation. I recommed to use this for this project as well. Then install the needed packages with pip.

**Comment by duane-edgington** [comment]
Hi Mikel. I appreciate the quick response.

I tried doing exactly as you said above, making a venv environment, absolutely clean, python 3.10.6
**source bin/activate**

I then cloned the repo, and installed the dependencies into the environment
**git clone https://github.com/mikel-brostrom/yolo_tracking.git
pip install -v -e .**

No drama. Totally clean.

However, then when I ran
**python examples/track.py --tracking-method deepocsort --source test.avi** 
I got the error message
2023-07-16 19:30:27.866 | WARNING  | boxmot.utils.checks:check_packages:27 - 
_Missing packages: "yolox==0.3.0" 
Atempting installation...
2023-07-16 19:30:38.490 | ERROR    | boxmot.utils.checks:check_packages:31 - Command 'pip install --no-cache "yolox==0.3.0"  ' returned non-zero exit status 1._

I got exactly the same error message when running my copy of your colab notebook
https://colab.research.google.com/drive/18nIqkBr68TkK8dHdarxTco6svHUJGggY?usp=sharing

So I think the installation of yolox is broken.

As I mentioned earlier, I was able to install pip install yolox 0.3.0 on a 3.8.17 python environment, but even there the track.py will no longer run (throws the same error message).

I got around this by blocking the check on yolox==0.3.0 in boxmot/utils/checks.py and
by commenting out the lines regarding yolox in examples/detectors/strategy/__init__.py and
by commenting out the block associated with yolox in examples/detectors/strategy/yolox.py

Of course, now I can't try yolox models, but I am happy with working with yolov8 models and yolo-nas models.

When you have a chance, you all might want to look at the yolox so others don't hit the same problem.

Best regards. Thank you for all your work.

**Comment by 2eroad** [comment]
Hi I had same issue. 

try this..

in examples/detectors/strategy/__init__.py 

# from .yolox import YoloXStrategy <-
from .yolov8 import Yolov8Strategy
from .yolonas import YoloNASStrategy

YOLO_SWITCH = {
    # 'yolox': YoloXStrategy, <-
    'yolov8': Yolov8Strategy,
    'yolo_nas': YoloNASStrategy
}


It works for me

**Comment by mikel-brostrom** [comment]
Hmmm. Weird. It is working in the CI. WiIl have a look at it right away.

**Comment by mikel-brostrom** [comment]
It seems like some of the yolox dependencies were conflicting with the ones in this repo. For some reason in CI it was possible to be resolved automatically.
